### ISSUE TITLE
process-dependency-links flag not found

### ISSUE THREAD

**Issue by cyfra** [google-research/football#1]
process-dependency-links flag is missing from the new pip release.
(we're currently using it to fetch the newest version of openai baselines code).

If you hit this error - the current workaround is:
replace:

`    
        'baselines>=0.1.6',
`

with
`
        'baselines @ git+git://github.com/openai/baselines.git@master#egg=baselines',
`

and remove the dependency_links section.

Sorry for the hassle - we're working on the better long term solution.

**Comment by TianhongDai** [comment]
It can also be solved by downgrading `pip` to `18.1`.

**Comment by cyfra** [comment]
Here's the longer description of the issue: maybe someone from the community could help us solve it better (as I'm far from the pip/setup.py expert :-)


- Our code depends on openai/baselines library.
- That library is available in pypi, but is very old (> 1 year old) - version 0.1.5
- We depend on the features that were added more recently.

Therefore, in order to use the football library, the user must have installed the openAI baselines **FROM github** and not from pypi.

Now, our problem is: how to do it in the best way:
- just depending on the "baselines" in setup.py doesn't work (pip will download the old 0.1.5 version from pypi)
- we've added the dependency_links section (which seems to work in pip < 18), but this forced us to introduce the "fake" 0.1.6 dependency - so that we're sure that system takes the contents from the dependency_link part (rather than from pypi)
- for pip > 18 - seems that you can specify the "baselines @ git+git:XXX" which should download it from github. Unfortunately  the earlier versions of pip don't understand that notion (and they would happily install the old 0.1.5 from pypi).

Any ideas for a better solution that could work across multiple pypi versions ?

**Comment by nczempin** [comment]
one good (step towards a?) solution would be to ask openai to update their version on pypi.

**Comment by gumush** [comment]
Newer version of pip did not support dependency links. 
You can install baseline 0.1.6 manually. 

```
git clone https://github.com/openai/baselines.git
cd baselines
pip install -e .
```

**Comment by cyfra** [comment]
Good news - openAI has increased their version in github repo to 0.1.6.

So people who install from github, should see the correct version now.

**Comment by ZechenLiu** [comment]
Here‘s my problem.Could you please help me solve it?Thank you very much.
pip3 install gfootball[tf_cpu] --process-dependency-links
Collecting gfootball[tf_cpu]
  Downloading https://files.pythonhosted.org/packages/d1/ab/bed5b7692e8af0cdc0b6fff7a976a69c4e8951146ab492811ef815a2b006/gfootball-0.2.tar.gz (11.0MB)
    100% |████████████████████████████████| 11.0MB 51kB/s 
  DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.
Collecting pygame==1.9.6 (from gfootball[tf_cpu])
  Using cached https://files.pythonhosted.org/packages/1d/c2/9a27669dc9f25978d70593d62405cf883b62cedf631ca996a10673000ab1/pygame-1.9.6-cp35-cp35m-manylinux1_x86_64.whl
Collecting opencv-python (from gfootball[tf_cpu])
  Using cached https://files.pythonhosted.org/packages/fe/c8/421eeac942ebc89552a5c90c2141b936be9cfde24dc3c6eeb472c62d1f8e/opencv_python-4.1.0.25-cp35-cp35m-manylinux1_x86_64.whl
Collecting scipy (from gfootball[tf_cpu])
  Using cached https://files.pythonhosted.org/packages/14/49/8f13fa215e10a7ab0731cc95b0e9bb66cf83c6a98260b154cfbd0b55fb19/scipy-1.3.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting gym (from gfootball[tf_cpu])
  Using cached https://files.pythonhosted.org/packages/8a/2d/d4ad0ef5159e87d66339f1dfaa4736687bf2699c3b8ce9e57998f28bb5a1/gym-0.13.0.tar.gz
Collecting baselines>=0.1.6 (from gfootball[tf_cpu])
  Cloning https://github.com/openai/baselines.git (to master) to /tmp/pip-build-7756pe7x/baselines
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/baselines.egg-info
    writing pip-egg-info/baselines.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/baselines.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/baselines.egg-info/requires.txt
    writing top-level names to pip-egg-info/baselines.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/baselines.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/baselines.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/baselines.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7756pe7x/baselines/setup.py", line 58, in <module>
        assert tf_pkg is not None, 'TensorFlow needed, of version above 1.4'
    AssertionError: TensorFlow needed, of version above 1.4
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7756pe7x/baselines/
You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


However,my pip version has been 19.1.1 before the mistake;and my TensorFlow's  version has  been above 1.4 before AssertionError.It's really ridiculous.

**Comment by qstanczyk** [comment]
We just pushed a new release, process-dependency-links is not used anymore.

**Comment by ZechenLiu** [comment]
Well，thank you so much.I solved it recently.
However，I’m meeting another challenges.Could you please help me solve it? Meanwhile,I also wrote an issue on your own github.


Running experiments:


root@lzc-virtual-machine:/home/lzc/football# python3 -m gfootball.examples.run_ppo2 --level=academy_empty_goal_close
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
import(pkg_name)
File "/home/lzc/football/gfootball/init.py", line 23, in 
for env_name in scenario_builder.all_scenarios():
File "/home/lzc/football/gfootball/env/scenario_builder.py", line 37, in all_scenarios
return [m.name for m in pkgutil.iter_modules([path])]
File "/home/lzc/football/gfootball/env/scenario_builder.py", line 37, in 
return [m.name for m in pkgutil.iter_modules([path])]
AttributeError: 'tuple' object has no attribute 'name'
—————————————————
Playing game yourself:


root@lzc-virtual-machine:/home/lzc/football# python3 -m gfootball.play_game
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
import(pkg_name)
File "/home/lzc/football/gfootball/init.py", line 23, in 
for env_name in scenario_builder.all_scenarios():
File "/home/lzc/football/gfootball/env/scenario_builder.py", line 37, in all_scenarios
return [m.name for m in pkgutil.iter_modules([path])]
File "/home/lzc/football/gfootball/env/scenario_builder.py", line 37, in 
return [m.name for m in pkgutil.iter_modules([path])]
AttributeError: 'tuple' object has no attribute 'name'


| |
刘泽辰
|
|
邮箱：15611877789@163.com
|

签名由 网易邮箱大师 定制

On 07/19/2019 22:27, qstanczyk wrote:

Closed #1.

**Comment by qstanczyk** [comment]
This issue is due to Python version, between Python 3.5 and Python 3.6 there was a change in pkgutil API which we use:
https://docs.python.org/3.6/library/pkgutil.html#pkgutil.iter_modules
https://docs.python.org/3.5/library/pkgutil.html#pkgutil.iter_modules

You can work around it by changing

> return [m.name for m in pkgutil.iter_modules([path])]

to:

> return [m[2] for m in pkgutil.iter_modules([path])]

In gfootball/env/scenario_builder.py

**Comment by qstanczyk** [comment]
I have just pushed a new version with the workaround to the problem, so alternatively you can just sync to head.
