### ISSUE TITLE
Question about wrappers which convert raw observation to a different form

### ISSUE THREAD

**Issue by JiaweiTian** [google-research/football#100]
play_game dumps full episode traces,  then by using "dump_to_txt.py", a txt file that contains the raw observations can be generated. But I am confused about how to convert these raw data to other forms like simple115 state vectors. Do I need to change any parameter inside play_game.py to make it generate simple115 states vector instead of raw observation, or handling the dump file by using functions in wrappers?  I am not sure how to process dump files by the wrappers. Do I need to add some functions in wrappers to "dump_to_txt.py" to process it or other methods?
I really appreciate it if someone can help me with it.

**Comment by kkurach** [comment]
Hi,

wrappers are used to process raw observations, like here:
https://github.com/google-research/football/blob/0c9dae10322aeb20368b59e5a189961207366898/gfootball/env/__init__.py#L51

If you'd like to convert this raw observation into simple115 / SMM / etc, probably the easiest would be to create a Fake environment that just reads the dump from the file and returns raw observation.
Then, you can use any wrapper on your Fake env to get the representation you'd like.

**Comment by qstanczyk** [comment]
Closing this issue, please reopen if you have some more questions.
