### ISSUE TITLE
Disable render in run_multiagent_rllib.py

### ISSUE THREAD

**Issue by Caiderkoujiao** [google-research/football#101]
I change render to false in run_multiagent_rllib.py
but it still shows up.
How can i disable render, I am confused.

Thanks!

**Comment by kkurach** [comment]
Hi @Caiderkoujiao,

could you please provide a repro case? (how you are running the code [command line with params], which version, any local changes, and a screenshot of what's happening?)
We'll look into it.

**Comment by Caiderkoujiao** [comment]
version='1.5'

The simple example of training multi-agent can be found in examples/run_multiagent_rllib.py.
I change render to false
`

    self.env = football_env.create_environment(
        env_name='test_example_multiagent', stacked=False,
        logdir='/tmp/rllib_test',
        write_goal_dumps=True, write_full_episode_dumps=True, render=False,
        dump_frequency=0,
        representation='extracted',
        dump_frequency = 50,
        number_of_left_players_agent_controls=num_agents,
        channel_dimensions=(42, 42))`

and 

> MESA_GL_VERSION_OVERRIDE=3.2 MESA_GLSL_VERSION_OVERRIDE=150 python -m run_multiagent_rllib.py

I set the **_render_**  to **_False_**, but the video still shows up.

**Comment by Caiderkoujiao** [comment]
Thanks a lot!
I should do that

> dump_frequency=50 if FLAGS.render and seed == 0 else 0.

Thank you for all your assistance.
