### ISSUE TITLE
Recommend not to continue development?

### ISSUE THREAD

**Issue by moonsh** [google-research/football#105]
I saw that the author of the football engine advised not to continue developing this engine.
(https://github.com/google-research/football/tree/master/third_party/gfootball_engine)

However, I would like to add some simple other actions or functions.
Are you still advising me to use another engine?

For example, I want to add a power gauge for pass or shooting.

Thank you,

**Comment by gkkurach** [comment]
Hi @moonsh,

well... we (Google Brain team) kind of ignored this warning and are developing this code for the last year :)  GRF is based on the original GameplayFootball engine, but there's a lot of changes --> we removed a ton of unused code, simplified the design, speed up many crucial parts, updated libraries, and many more.

In general, if you would like to do anything to the game itself, I'd recommend to start from the GRF code.

**Comment by yoanisgil** [comment]
@gkkurach maybe the GameplayFootball should be factored out as a external dependency? Just saying, in case some folks want to work only on that.

**Comment by qstanczyk** [comment]
GFootball engine is in third_party/gfootball_engine directory and can be compiled independently from Python environment in case someone needs it that way.
