### ISSUE TITLE
Cmake, Boost, python, and Fedora

### ISSUE THREAD

**Issue by FAMILIAR-project** [google-research/football#108]
Hi, 

I'm using Fedora and get the following compilation error: 

```
-- Could NOT find Boost (missing: python3-py37) (found version "1.69.0")
    python3-py37 not found. Trying other names.
    CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:2006 (message):
      No header defined for python-py37; skipping header check (note: header-only
      libraries have no designated component)
    Call Stack (most recent call first):
      CMakeLists.txt:61 (FIND_PACKAGE)
    
    
    -- Could NOT find Boost (missing: python-py37) (found version "1.69.0")
    python-py37 not found. Trying other names.
    -- Could NOT find Boost (missing: python37) (found version "1.69.0")
    CMake Error at CMakeLists.txt:72 (message):
      Python boost not found
```
After investigating a bit, `third_party/gfootball_engine/CMakeLists.txt` does not properly manage specificities of Python and Boost on Fedora. 

```
 # Some other distributions.                                                                                                                  
    FIND_PACKAGE(Boost COMPONENTS python${PYTHON_MAJOR}${PYTHON_MINOR})
    if (Boost_PYTHON${PYTHON_MAJOR}${PYTHON_MINOR}_FOUND)
      set(BOOST_PYTHON_VERSION python${PYTHON_MAJOR}${PYTHON_MINOR})
    else()
      message(FATAL_ERROR "Python boost not found")
```
Unfortunately, I don't have a solution/fix though I suspect there could be some workaround with cmake https://cmake.org/cmake/help/latest/module/FindBoost.html

**Comment by ZhangNYG** [comment]
same error

**Comment by samuro95** [comment]
same error

**Comment by Cyril-JZ** [comment]
same error

**Comment by Matyyas** [comment]
I had the same error (on MacOX) and managed to solve it by uninstalling boost-python which I had installed following the READ.me with `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/527d96f84d4632d30b281ef5b26717e0a75edcb4/Formula/boost-python3.rb`

In short, uninstall boost-python: `brew unlink boost-python3`, then reinstall it using `brew install boost-python3`

You can have a look the original issue #188

**Comment by vi3itor** [comment]
Yes, this works on Mac OS X. But on Fedora (unfortunately, I don't have Fedora installed), it can be fixed by installing the correct version of `boost-python3`. [A quick search](https://rpmfind.net/linux/rpm2html/search.php?query=boost-python3) shows that the latest version with Python 3.7 is [1.69.0-12](https://rpmfind.net/linux/RPM/fedora/updates/31/x86_64/Packages/b/boost-python3-1.69.0-12.fc31.x86_64.html). It installs `libboost_python37.so.1.69.0` file (see the list of files at the end of the page). In case it doesn't work, try adding [`elseif` condition](https://cmake.org/cmake/help/latest/command/if.html) to the CMakeList.txt. 
@FAMILIAR-project @ZhangNYG @ZhaoYi1031 @samuro95 @Cyril-JZ Please try it.

**Comment by GoingMyWay** [comment]
Try this for Python3.7

`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/e8cce4e8ede23f546ee3063dba559ba06f135e44/Formula/boost-python3.rb `

**Comment by GoingMyWay** [comment]
> Yes, this works on Mac OS X. But on Fedora (unfortunately, I don't have Fedora installed), it can be fixed by installing the correct version of `boost-python3`. [A quick search](https://rpmfind.net/linux/rpm2html/search.php?query=boost-python3) shows that the latest version with Python 3.7 is [1.69.0-12](https://rpmfind.net/linux/RPM/fedora/updates/31/x86_64/Packages/b/boost-python3-1.69.0-12.fc31.x86_64.html). It installs `libboost_python37.so.1.69.0` file (see the list of files at the end of the page). In case it doesn't work, try adding [`elseif` condition](https://cmake.org/cmake/help/latest/command/if.html) to the CMakeList.txt.
> @FAMILIAR-project @ZhangNYG @ZhaoYi1031 @samuro95 @Cyril-JZ Please try it.

Failed on Python3.7 MacOS. The same error again.

**Comment by GoingMyWay** [comment]
I think the key issue is on macOS, what is the name of boost-python3?

**Comment by GoingMyWay** [comment]
Sorry to bother, I found the cmake was seeking the include path of Boost in `/usr/local/include/` however, normally, the include of boost is in `/usr/local/Cellar/boost/1.72.0/include` is that a issue? 

I think maybe it is an issue.

**Comment by GoingMyWay** [comment]
@vi3itor Dear Vi3itor, thanks. I will try it.

**Comment by GoingMyWay** [comment]
After struggling for a while, I found the main issue on macOS is after installing 1.72 of boost and boost-python3, the `LDFLAGS` and `CPPFLAGS` are not correctly set, here is my solution

1.  Install boost and boost-python3 1.73

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/032f1b7082183f7e3428e2de0e6c435b8ed8db15/Formula/boost.rb
```

and

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/032f1b7082183f7e3428e2de0e6c435b8ed8db15/Formula/boost-python3.rb 
```

2. setup `LDFLAGS` and `CPPFLAGS`

```
export CPPFLAGS="-I/usr/local/Cellar/boost/1.72.0/include/"  
```
and
```
export LDFLAGS="-L/usr/local/Cellar/boost-python3/1.72.0/lib/":"-L/usr/local/Cellar/boost/1.72.0/lib/"
```

3. Installation

```
pip3.7 install gfootball
```

4. Done
![image](https://user-images.githubusercontent.com/9346460/90582184-b05cc000-e1ff-11ea-950c-027cad84bdbb.png)
