### ISSUE TITLE
 Reopening Issue: [Rendering] Black-and-white rendering on ubuntu laptop

### ISSUE THREAD

**Issue by EnnaSachdeva** [google-research/football#109]
I am also having the same issue (https://github.com/google-research/football/issues/64) on Ubuntu 16.04, with GTX-1080, OpenGL ES 3.2 NVIDIA 384.130. However, the current answers on Issue # 64 do not seem to work. Any help would be appreciated.
The screenshot is attached below-

![football](https://user-images.githubusercontent.com/15670305/71611779-b149c000-2b50-11ea-9713-eb559a0ef42b.png)

**Comment by zengsh-cqupt** [comment]
I have the same issue. ubuntu16.04, vmvare ,visual env(anaconda),laptop. football1.2 and latest version football have the same issues:
1.When I have installed football, I run whth command "python3 -m gfootball.play_game",the result is following:
(gfootball_v12_python35) zengsh@ubuntu:~/football$ python3 -m gfootball.play_game
/home/zengsh/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/zengsh/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/zengsh/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/zengsh/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/zengsh/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/zengsh/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/zengsh/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/zengsh/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/zengsh/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/zengsh/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/zengsh/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/zengsh/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Sat Jan  4 02:53:39 2020 [Warning] in [OpenGLRenderer3D::CreateContext]: OpenGL version not equal to or higher than 3.2 (or not reported as such)
shader compilation error (media/shaders/simple.vert)
Sat Jan  4 02:53:39 2020 [Warning] in [::LoadGLShader]: shader compilation error (media/shaders/simple.vert)
shader compilation info: 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Sat Jan  4 02:53:39 2020 [Warning] in [::LoadGLShader]: shader compilation info (media/shaders/simple.vert):
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

0 1
Sat Jan  4 02:53:39 2020 [FATAL ERROR !!! N00000 !!!] in [OpenGLRenderer3D::LoadShader]: 1Could not compile vertex program: simple
2. When I run with command `MESA_GL_VERSION_OVERRIDE=3.2 MESA_GLSL_VERSION_OVERRIDE=150 python3 -m gfootball.play_game`, the result is black and white ,as following:
![image](https://user-images.githubusercontent.com/59502320/71764642-a3969080-2eea-11ea-8bdb-cb320f931064.png)
3. I run with command "python3 -m gfootball.examples.run_ppo2 --level=academy_empty_goal_close", likely it works, the result is floowing:

![image](https://user-images.githubusercontent.com/59502320/71764720-a776e280-2eeb-11ea-84ba-00d243b1b237.png)

How to fix the issue? thanks.

**Comment by songhappy** [comment]
I have the same issue as zengsh-cqupt

**Comment by qstanczyk** [comment]
Yes, there is no known solution ATM, but  I guess we can look for solution there.

**Comment by qstanczyk** [comment]
Might be also worth trying out within the Docker image.
