### ISSUE TITLE
Unable to start an environment instance for second time (gpu version)

### ISSUE THREAD

**Issue by ChintanTrivedi** [google-research/football#11]
I'm starting an environment (gpu) using the following code-

`import gfootball.env as football_env`
`env = football_env.create_environment(env_name=’academy_corner’,render=True)`
`env.reset()`

It renders successfully and runs as expected.

However, if I terminate this python process and initiate another with the terminal and run the same code again, `env.reset()` throws the following error:-

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/chintan/anaconda3/lib/python3.7/site-packages/gym/core.py", line 254, in reset
>     observation = self.env.reset(**kwargs)
>   File "/home/chintan/anaconda3/lib/python3.7/site-packages/gfootball/env/football_env.py", line 150, in reset
>     self._env.reset(config)
>   File "/home/chintan/anaconda3/lib/python3.7/site-packages/gfootball/env/football_env_wrapper.py", line 50, in reset
>     self._env.reset(config, self._trace)
>   File "/home/chintan/anaconda3/lib/python3.7/site-packages/gfootball/env/football_env_core.py", line 63, in reset
>     _engine.start_game(self._config.GameConfig())
>   File "/home/chintan/anaconda3/lib/python3.7/site-packages/gfootball/env/config.py", line 120, in GameConfig
>     cfg.high_quality = self['render']
> Boost.Python.ArgumentError: Python argument types in
>     None.None(GameConfig, str)
> did not match C++ signature:
>     None(GameConfig {lvalue}, bool)

Rebooting the OS seems to fix this issue, so I'm assuming it has something to do with the GPU being locked from the first run or something similar? I'm not too familiar with CPP.

Using Ubuntu 18.04, GTX1070 (driver 410), cuda 10.0, TF-gpu 1.13.1. Thanks!

**Comment by qstanczyk** [comment]
From stack trace it looks like 'render' parameter in the config of the environment is not Boolean, but a string. Are you sure you set it to True/False everywhere?

I assume you still see this issue when you start from a new terminal window (hence you need to reboot)?

**Comment by qstanczyk** [comment]
Also, how do you kill the environment? Are you sure all processes are properly destroyed? Maybe there is some leftover process pending.

**Comment by cyfra** [comment]
You can also try running **nvidia-smi** program to see which processes are using your GPU.
