### ISSUE TITLE
Question about Table 2 in the paper

### ISSUE THREAD

**Issue by jlim13** [google-research/football#117]
I have a question about the Multiplayer experiments you ran where you show the lack of transitivity (Table 2). What combination of reward function/RL algorithm did you use for these experiments? Assuming you used the "Scoring" reward function, does that indicate that different reward functions could lead to generalizability?

**Comment by AntonRaichuk** [comment]
For such questions I'd recommend using google-research-football@google.com.

To answer your questions, for this experiment we have used OpenAI Baseline's PPO with checkpoint reward.

We have not performed this experiment with different rewards, so cannot be certain.
But my personal opinion, is that it will not generalize for other rewards too. The policy simply overfits to the opponent and as soon as you change the opponent the policy is likely to perform much worse.
