### ISSUE TITLE
Google Research Football compilation failed

### ISSUE THREAD

**Issue by binmom** [google-research/football#118]
I got a build fail issue

/usr/bin/ld: /usr/local/lib/libpython3.6m.a(ceval.o): relocation R_X86_64_PC32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
    CMakeFiles/game.dir/build.make:398: recipe for target 'libgame.so' failed
    make[2]: *** [libgame.so] Error 1
    CMakeFiles/Makefile2:298: recipe for target 'CMakeFiles/game.dir/all' failed
    make[1]: *** [CMakeFiles/game.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    gfootball/build_game_engine.sh: line 27: pushd: third_party/gfootball_engine: No such file or directory
    error: Google Research Football compilation failed
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/mbkim/anaconda3/envs/maml_gpu/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-d1i0bufd/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-d1i0bufd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dplvq2ev/install-record.txt --single-version-externally-managed --compile --install-headers /home/mbkim/anaconda3/envs/maml_gpu/include/python3.6m/gfootball Check the logs for full command output.

how can i fix this problem?

Thank you

**Comment by BaozCWJ** [comment]
I also meet the same failure while using docker
`    [ 54%] Built target menulib
    [ 55%] Building CXX object CMakeFiles/scenelib.dir/src/scene/resources/geometrydata.cpp.o
    [ 55%] Built target baselib
    [ 55%] Built target scenelib
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    gfootball/build_game_engine.sh: line 27: pushd: third_party/gfootball_engine: No such file or directory
    error: Google Research Football compilation failed
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-wyr_qxik/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-wyr_qxik/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-u7y3oj7c/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/gfootball Check the logs for full command output.
The command '/bin/sh -c cd /gfootball && pip3 install .' returned a non-zero code: 1`

**Comment by AntonRaichuk** [comment]
I'm not sure the problem is related to GRF.

Could you try applying some of the fixes after searching for this issue online.
For example:
https://stackoverflow.com/questions/42582712/relocation-r-x86-64-32s-against-py-notimplementedstruct-can-not-be-used-when

**Comment by BaozCWJ** [comment]
> I'm not sure the problem is related to GRF.
> 
> Could you try applying some of the fixes after searching for this issue online.
> For example:
> https://stackoverflow.com/questions/42582712/relocation-r-x86-64-32s-against-py-notimplementedstruct-can-not-be-used-when

THX! But I skipped this failure via prebuilt library. See #86

**Comment by AntonRaichuk** [comment]
@binmom: could you try either what I or @BaozCWJ suggested and let us know what/if worked

**Comment by binmom** [comment]
Oh my god @AntonRaichuk 's solution save me from a huge pain. So Thankyou Thankyou very much

**Comment by chrisyrniu** [comment]
@binmom I met the same problem. How do you solve it in the end?
