### ISSUE TITLE
[question] GRF Competition Observation

### ISSUE THREAD

**Issue by yutaizhou** [google-research/football#121]
Hello,

What is the observation representation for the tournament competition? Pixel? SMM? Floats? 

I am interested in the multi-agent track. If the representation is floats, does each agent have the full state, or is it partially observed for each agent (local observation)? 

Thank you!

**Comment by binmom** [comment]
I also want to participate in multiagent track. Representation option is on our hands. Defaults is SMM

**Comment by yutaizhou** [comment]
Yes I see that we can specify the representation when we create an environment as seen here: https://github.com/google-research/football/blob/master/gfootball/eval_server/example_client.py

So I guess the game state is handled by the engine, and the two competing teams can have different/same representations depending on choice when creating the environment?

**Comment by qstanczyk** [comment]
That is correct guys, each side can do whatever it wants.
