### ISSUE TITLE
Is there anyway to set up a customized scenario without a Goalkeeper?

### ISSUE THREAD

**Issue by Mohan-Zhang-u** [google-research/football#122]
Thanks for your great work! When I'm working on setting up customized scenes, it seems that each team needs to have a player with the role "e_PlayerRole_GK", otherwise the game won't start.
I'm wondering, is it possible to set up a customized scene without any GK?

**Comment by qstanczyk** [comment]
Hi, yes, goalkeeper is required, but you can position him outside of the field and mark as lazy:
https://github.com/google-research/football/blob/75e88e49c552f3e096ae4054a1dd1a7ccbfb837b/gfootball/env/scenario_builder.py#L98
