### ISSUE TITLE
Display issue of simulation

### ISSUE THREAD

**Issue by Muhammad-Talha-MT** [google-research/football#123]
I am facing an Issue about colors, the whole game is black and white including ground and players except score strip.

**Comment by qstanczyk** [comment]
I guess this is similar to #109 ?

**Comment by muhammadtalha112** [comment]
> I guess this is similar to #109 ?

I didn't find any solution there

**Comment by qstanczyk** [comment]
Most likely this is due to old graphics drivers not supporting required rendering mode. Maybe trying with software rendering would help.
