### ISSUE TITLE
What is the "active_player" observation when doing multiagent

### ISSUE THREAD

**Issue by julienroyd** [google-research/football#127]
Hi,

We are using the `academy_3_vs_1_with_keeper`  task for multi-agent learning. We initialise it as follows:

```
self.env = football_env.create_environment(
            env_name='academy_3_vs_1_with_keeper',
            stacked=False,
            representation='simple115',
            rewards='scoring',
            logdir=str(seed_dir / 'football_dumps'),
            enable_goal_videos=False,
            enable_full_episode_videos=bool(dump_freq),
            render=render,
            write_video=True,
            dump_frequency=dump_freq,
            number_of_left_players_agent_controls=3,
            number_of_right_players_agent_controls=0,
            enable_sides_swap=False,
            channel_dimensions=(
                observation_preprocessing.SMM_WIDTH,
                observation_preprocessing.SMM_HEIGHT)
        )
```

We have a few questions:

### Question 1: Why simple115 can't be used for other tasks than 11v11?

In your documentation in `gfootball/env/__init__.py` it is written that the representation `simple115`:

> "Can only be used when the scenario is a flavor of normal game (i.e. 11 versus 11 players)"

Why is that? We understand that the vector will be wastefully long as coordinates and velocities of absent players will be constant (set to -1 from what I inspected), but these can be easily removed from the agent's observations. Is there anything else that would pose problem with using `representation="simple115"` for `env_name="academy_3_vs_1_with_keeper"` ?

### Question 2: What is the meaning of active_player one-hot vector in observation in a multi-agent setting?

At each time-step, the environment returns us 3 observation vectors, for our 3 agents. However, we were surprised to notice that not all values of those 3 vectors are the same. We expected them to be since all positions and velocities are in absolute coordinates. The only indexes for which we noticed differences between the 3 agents observation vectors are the indexes corresponding to `active_player` (97 to 108).

Even more puzzling is that each agent seem associated to one of these indexes, but not all the time. For example, our agent-1 will in most cases have the index 98 of its observation vector activated, agent-2 will have index 99 and agent-3 will have index 100. However, sometimes (maybe 5 to 10% of episodes) they will have another of those three index activated, or even index 97 (which is counter-intuitive since there are only 3 controllable agents for this task). 

These observations raise several questions:

  * What do active_player exactly mean? (player controlled by the agent?, player with the ball?)
  * How are active_player indexes ordered? (the values are not the same for all agents)
  * Why are agents sometimes switching of active_player, even though we have 3 agents for 3 players?
  * Who is the fourth active_player (index 97) in "academy_3_vs_1_with_keeper"?

**Comment by AntonRaichuk** [comment]
q1: yeah, i guess you could use it too, i think that comment came before we added backfilling logic. 
btw, just checked the backfilling logic and it looks broken if the first team has red cards. will try to fix it soon.

q2: i believe there is also a goalkeeper (so the game is actually 4 vs 1). when it has a ball it becomes active. that's why i think you see index 97 being activated sometimes.
- active_player: player that is being controlled

**Comment by julienroyd** [comment]
Ok thanks. May I ask what is backfilling and what looks broken in the backfilling logic?

**Comment by AntonRaichuk** [comment]
backfilling: setting missing values to -1

what's broken: we append data for left team, then for right, and then we backfill
what should happen: we append data for left team, backfill, then for right, backfill.

currently if a player on the left team gets a red card, the data for the right team will get shifted, which is very likely not desirable from ML perspective
