### ISSUE TITLE
Should keeper rush be part of the default action set?

### ISSUE THREAD

**Issue by ollieperree** [google-research/football#129]
From [the paper](https://arxiv.org/pdf/1907.11180.pdf):

![image](https://user-images.githubusercontent.com/26961541/77576055-654ab500-6ecc-11ea-85ca-fab17d97131d.png)

Here there are 20 actions, but I only see 19 in the action space exposed by the gym API.

I see that in gfootball/env/football_action_set.py, `action_set_dict["default"]` doesn't contain `action_keeper_rush`. Is this intended?

**Comment by AntonRaichuk** [comment]
Hey Ollie,

Thanks for bringing this up. You are right about the discrepancy between the code and the paper.
You can see that v1 version of the github code did indeed have keeper rush as an action in the default action set. But after some experiment and analysis we decided to drop it and for v2 version it is not there anymore.
We forgot to update the paper on arxiv when pushing v2 version of a code, which creates this discrepancy.
We'll update the paper on arxiv ASAP

**Comment by AntonRaichuk** [comment]
The paper was update today. Now it should be consistent with the code.
