### ISSUE TITLE
Is there any API to control multiple player?

### ISSUE THREAD

**Issue by Da-Capo** [google-research/football#13]
I want to control multiple player by different policy at same time, and I find this 
 line `self._env.perform_action(action, self._home_team, self._player_id)` in the `football_env_core.py`,  but it seems not work to change the self._player_id.

**Comment by qstanczyk** [comment]
Have a look at play_game.py. It has home_players and away_players command line params controlling set of controlled players in both teams. You can add your own implementation of players (see env/players) and enable them by setting away_players and home_players parameters.

We are also looking into adding support for multi-agent training, stay tuned for this.

**Comment by kkurach** [comment]
We will update the README to show how to control all players in the env (it's already supported). In the meantime, we're currently experimenting with multi-agent setup. We will include an example of running multi-agent training in a future release (ETA 1-2 weeks)

**Comment by Da-Capo** [comment]
That sounds great, thanks.
