### ISSUE TITLE
About VS

### ISSUE THREAD

**Issue by yumianhuli2** [google-research/football#137]
How do I set up if I want to try two trained teams of high-level NPCS against each other?

Is there a tutorial where you can download and use anyone's contributed AI?

**Comment by qstanczyk** [comment]
You can use play_game script with --players= flag specifying different trained agents to control left/right teams.  See here: https://github.com/google-research/football/#play-vs-pre-trained-agent
There is no official repo to download "anyones" contributed AI.

**Comment by qstanczyk** [comment]
Please reopen if you have any followup questions.

**Comment by qstanczyk** [comment]
Also https://github.com/google-research/football/blob/master/gfootball/doc/multi_agent.md
