### ISSUE TITLE
Get status from script

### ISSUE THREAD

**Issue by yumianhuli2** [google-research/football#138]
Hello!
There is  state = get_state() from Environment API,But I looked up the play_game.py script and I didn't find the usage of the environment API, was it in another script?
Are there any relevant documents or tutorials?

For EXAMPLE:
Is there a minimal  easy script:

1. Choose reinforcement learning algorithm

2. Start the engine

3. Get the list and description of environment variables, such as player's position, status and all other variables that can be obtained?

THANK YOU!

**Comment by qstanczyk** [comment]
get_state / set_state is meant to save/restore environment state. State is opaque and immutable. Simple use case is when you want to verify outcomes of different actions given current environment state. You can get_state(), do a sequence of actions, set_state() to restore to the previous state and do a different sequence of actions.
See documentation here: https://github.com/google-research/football/blob/master/gfootball/doc/api.md

**Comment by qstanczyk** [comment]
Please reopen if you have followup questions.
