### ISSUE TITLE
@Question - Export exposed observations ? 

### ISSUE THREAD

**Issue by gumush** [google-research/football#14]
According to documentation there are some observations like coordinates of players and ball etc. 
--dump_full_episodes=True works for dumping data. Is there any flag to export these observations ?

**Comment by qstanczyk** [comment]
What do you mean by exposing observations? Dumped data (trace dumps) contain observations and additional debug info. You can watch the replays with replay.py. You can alternatively load them with Python interpreter and analyze by hand:

  with open(FLAGS.trace_file, 'rb') as f:
    replay = six.moves.cPickle.load(f)
    print(replay)
    ....

**Comment by gumush** [comment]
Thanks for quick response , i'm looking for exporting 

Ball information:
ball - [x, y, z] position of the ball.
ball_direction - [x, y, z] ball movement vector.
ball_rotation - [x, y, z] rotation angles in radians.
ball_owned_team - {-1, 0, 1}, -1 = ball not owned, 0 = home team, 1 = away team.
ball_owned_player - {0..N-1} integer denoting index of the player owning the ball.
Home team:
home_team - N-elements vector with [x, y] positions of players.
home_team_direction - N-elements vector with [x, y] movement vectors of players.
home_team_tired_factor - N-elements vector of floats in the range {0..1}. 0 means player is not tired at all.
home_team_yellow_card - N-elements vector of integers denoting number of yellow cards a given player has (0 or 1).
home_team_active - N-elements vector of Bools denoting whether a given player is playing the game (False means player got a red card).
home_team_roles - N-elements vector denoting roles of players. The meaning is:
0 = e_PlayerRole_GK - goalkeeper,
1 = e_PlayerRole_CB - centre back,
2 = e_PlayerRole_LB - left back,
3 = e_PlayerRole_RB - right back,
4 = e_PlayerRole_DM - defence midfield,
5 = e_PlayerRole_CM - central midfield,
6 = e_PlayerRole_LM - left midfield,
7 = e_PlayerRole_RM - right midfield,
8 = e_PlayerRole_AM - attack midfield,
9 = e_PlayerRole_CF - central front,
Away team:
away_team - same as for home team.
away_team_direction - same as for home team.
away_team_tired_factor - same as for home team.
away_team_yellow_card - same as for home team.
away_team_active - same as for home team.
away_team_roles - same as for home team.

i tried to export replay as json ( it looks like json ) but it gives an error. I'll try to export another way.

**Comment by qstanczyk** [comment]
Hi Hikmet, looks like you are good on this one. I will close this issues, please reopen if you have any further questions.
