### ISSUE TITLE
Missing dependency in README

### ISSUE THREAD

**Issue by Cptweirdo** [google-research/football#143]
For a successful install user also needs to run: `pip3 install wheel`

This is not referenced in the installation guide

**Comment by vi3itor** [comment]
What distro are you running and how did you install python3 and pip? As far as I can tell, wheel (and setuptools) are installed automatically with pip. 
Did you start from a fresh Linux setup or did you use a virtual environment to check that wheel installation is indeed required?

**Comment by vi3itor** [comment]
It was addressed in version 2.0.7 on April 21. The issue can be closed.
