### ISSUE TITLE
About add joystick

### ISSUE THREAD

**Issue by yumianhuli2** [google-research/football#144]
A great work！
Have a plan to add support for joystick in the future?

**Comment by qstanczyk** [comment]
I think joystick should be supported through:
python3 -m gfootball.play_game --players=gamepad

**Comment by yumianhuli2** [comment]
> I think joystick should be supported through:
> python3 -m gfootball.play_game --players=gamepad

Thank you！By the way,Where can I set the buttons for the gamepad？

**Comment by qstanczyk** [comment]
Mapping is defined here:
https://github.com/google-research/football/blob/0c9dae10322aeb20368b59e5a189961207366898/gfootball/env/players/gamepad.py#L26

**Comment by yumianhuli2** [comment]
very nice！
