### ISSUE TITLE
what is the meaning of player_direction

### ISSUE THREAD

**Issue by yumianhuli2** [google-research/football#145]
Hello！
I read the source code for gfootball and there was one line of code I didn't quite understand below：
info.player_direction =
          (movement / GetGameConfig().physics_steps_per_frame).coords;
And I printed it，got like --
x:-0.553865,y:-0.007866,z:0.000000 
x:-0.000000,y:-0.000000,z:0.000000

So what I want to ask is the relationship between this data and Euler angles or Quaternion,and
how to switch from one to the other？
Thank you very much！

**Comment by qstanczyk** [comment]
Direction is represented in a form of movement vector, not angles / quaternions. When game engine does rendering and has to perform rotations etc. it operates on a different representations. Classes have helper methods to convert between them.

**Comment by yumianhuli2** [comment]
> helper

I am sorry,I just found:
info.player_direction =
          (movement / GetGameConfig().physics_steps_per_frame).coords;

Could you show me the  "helper methods"?Thank you!

**Comment by qstanczyk** [comment]
What do you mean by helper methods? Why are you looking at internal state
instead of just using public observations documented here:
https://github.com/google-research/football/blob/master/gfootball/doc/observation.md

**Comment by yumianhuli2** [comment]
Because there was something wrong with the python script, I chose to type it directly in the C++ football engine

**Comment by qstanczyk** [comment]
Then have a look how this is mapped to Python:
https://github.com/google-research/football/blob/0c9dae10322aeb20368b59e5a189961207366898/third_party/gfootball_engine/ai.cpp#L97

and

https://github.com/google-research/football/blob/9de1a8a9d0b7d50175c50b225e5d010ab79435f8/gfootball/env/football_env_core.py#L325

That should answer what is the connection between publicly exposed  observations ad internal value.

**Comment by yumianhuli2** [comment]
Hello! I know this  .def_readonly("direction", &PlayerInfo::player_direction) mapping
so I found this:
![Selection_001](https://user-images.githubusercontent.com/39210837/80054405-bdb7b580-8551-11ea-9489-fae6f41fe324.png)
But you said this is wrong for player_direction?So I want to know where is the player_direction value in the C++ football engine.
Thank you for your help!
