### ISSUE TITLE
Can I use colab to train the model and play the model on local Ubuntu?

### ISSUE THREAD

**Issue by LeonIdeal** [google-research/football#151]
I installed a virtual-machine on my mac OS system, and because of the lack of computing resources, I can only train the model on colab, I wonder if I can train the model on colab and then download and apply the model to play the game in order to watch the play visually? If it is supported, please give me a guide, thanks!

**Comment by cyfra** [comment]
Hey @LeonIdeal  - yes, this is possible.

Once you train the model, you can 'save the weights' - and then on load them on your local machine and run the inference.

For example, if you use tensorflow:

On colab, after training, you could call something like this:
  tf.saved_model.save(model, "my_saved_model")

Then download the files to your local machine, and there you can load the model with:
model = tf.saved_model.load(PATH_TO_MODEL)
And run it against the environment.

**Comment by LeonIdeal** [comment]
> Hey @LeonIdeal - yes, this is possible.
> 
> Once you train the model, you can 'save the weights' - and then on load them on your local machine and run the inference.
> 
> For example, if you use tensorflow:
> 
> On colab, after training, you could call something like this:
> tf.saved_model.save(model, "my_saved_model")
> 
> Then download the files to your local machine, and there you can load the model with:
> model = tf.saved_model.load(PATH_TO_MODEL)
> And run it against the environment.
Thanks! I added a save_model() method in my DQN class, but on colab it turned out 
`/tensorflow-1.15.2/python3.6/tensorflow_core/python/saved_model/save.py in save(obj, export_dir, signatures)
    830   if not isinstance(obj, base.Trackable):
    831     raise ValueError(
--> 832         "Expected a Trackable object for export, got {}.".format(obj))
    833 
    834   checkpoint_graph_view = _AugmentedGraphView(obj)

ValueError: Expected a Trackable object for export, got <tensorflow.python.client.session.Session object at 0x7f8659e2c400>.`

I wonder if this format can be debugged and how, thanks.

**Comment by dave7895** [comment]
hey @LeonIdeal would it be possible to get the colab notebook? Would love to take a look at it.
