### ISSUE TITLE
How can I render the game on ubuntu after trained and saved the checkpoint on colab?

### ISSUE THREAD

**Issue by LeonIdeal** [google-research/football#152]
I have already trained and saved model on colab using tensorflow=1.5. And Saving uses method 
`saver = tf.train.Saver() 
  saver.save(self.sess, './model.ckpt')`
It downloaded 4 checkpoint files
![image](https://user-images.githubusercontent.com/19504637/80061721-a1714400-8564-11ea-8277-e8216346da08.png)
I localized the checkpoints to Ubuntu, but I only saw the command 
<img width="993" alt="image" src="https://user-images.githubusercontent.com/19504637/80061798-c6fe4d80-8564-11ea-8278-8877947be4cc.png">
It has different checkpoint format .dms from my .ckpt
I wonder what command can I use to apply the checkpoint to my local ubuntu and render the game. Thanks

**Comment by AntonRaichuk** [comment]
Checkout implementation of football/gfootball/env/players/ppo2_cnn.py and how it load checkpoints. You could try changing that so it can also read your checkpoint.

Please also consider doing a PR so that other people could benefit from this too.

**Comment by qstanczyk** [comment]
Closing, please reopen if some questions are pending
