### ISSUE TITLE
Running results in "Error: signal 11"

### ISSUE THREAD

**Issue by rafvasq** [google-research/football#154]
It seems like I receive a few errors during installation (first screenshot), yet when I try again all requirements are satisfied (top of second screenshot). However, when I try to play nothing happens except some output and a non-descriptive error. Any idea what's going on here?
![image](https://user-images.githubusercontent.com/11052762/80154549-c928d200-858d-11ea-8ac0-076b8e6f2192.png)

![image](https://user-images.githubusercontent.com/11052762/80154232-2cfecb00-858d-11ea-8cf9-21f4f50080ac.png)

**Comment by vi3itor** [comment]
You should upgrade `pip` (as suggested in your terminal) before proceeding with `pip3 install .`:   
`pip3 install --upgrade pip setuptools wheel`

Concerning your second screenshot (`Error: signal 11`) it looks like SDL is failing to load the image. 
Consider reinstalling sdl2-image (and probably sdl2):
`sudo apt-get install --reinstall libsdl2-dev libsdl2-image-dev`
Please provide the output of the command above.

After reinstalling sdl2-image, repeat the full installation. I recommend to start from the beginning and remove the folder with virtual environment:
`rm -r football-env`
create a new one:
`python3 -m venv football-env`
activate it:
`source football-env/bin/activate`  
upgrade pip:
`pip3 install --upgrade pip setuptools wheel`
and install the game: 
`pip3 install .`

**Comment by rafvasq** [comment]
@vi3itor, I've reinstalled sdl2-image/sdl-2 as you recommended. The output is below:
![image](https://user-images.githubusercontent.com/11052762/80767990-34871c80-8b17-11ea-8fb7-6865a32e6f3b.png)

After repeating the full installation, I received a new, long error during the build which included: 
![image](https://user-images.githubusercontent.com/11052762/80768199-bd9e5380-8b17-11ea-9b06-82267390e248.png) and followed the solution from #116. 

Lastly, I have to set environment variables for MESA driver as mentioned in the [FAQ](set environment variables for MESA driver). 

All working now! Thanks for your help.

**Comment by kaustubhsridhar** [comment]
Hey, I get the same error with a docker on a mac (and a docker on a remote server runnign Debian). I've tried reinstalling sdl2 as mentioned above and then reinstalling gfootball. I still get "Error: signal 11". Any help would be really appreciated.
