### ISSUE TITLE
Could you release the model.py code within IMPALA and PPO which estimated in the paper?

### ISSUE THREAD

**Issue by LeonIdeal** [google-research/football#155]
I read the paper and saw some rewards after training several RL algorithms like PPO and IMPALA and DQN, and meanwhile I want to re-construct the results of the figure below. Could you please release the code of these model and run.py please?
<img width="842" alt="image" src="https://user-images.githubusercontent.com/19504637/80191547-7102d600-8648-11ea-8c24-b70885f19098.png">

**Comment by AntonRaichuk** [comment]
Please check the following:
 - football/gfootball/examples/repro_checkpoint_easy.sh
 - football/gfootball/examples/repro_scoring_easy.sh
 - https://towardsdatascience.com/reproducing-google-research-football-rl-results-ac75cf17190e
 - https://github.com/google-research/seed_rl/tree/master/football
