### ISSUE TITLE
grpc connect failed when using remote_football_env.py

### ISSUE THREAD

**Issue by yjp999** [google-research/football#157]
Hi,

I was encoutered with a problem when executing remote_football_env.py script, it appears the server(ipv4:34.90.21.55:50002) is not stable enough? The error message as follows,

W0428 20:32:05.604286 140269714593600 remote_football_env.py:163] Exception during request: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Connect Failed"
        debug_error_string = "{"created":"@1588077125.603978734","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2715,"referenced_errors":[{"created":"@1588077111.574142321","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":456,"referenced_errors":[{"created":"@1588077111.574078476","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":963,"grpc_status":14,"referenced_errors":[{"created":"@1588077111.573997500","description":"Failed to connect to remote host: FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.cc","file_line":194,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1588077111.573975260","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":119}],"target_address":"ipv4:34.90.21.55:50002"}]}]}]}"

I have encountered this problem twice, I ’m not sure if it ’s my client ’s network problem.

**Comment by AntonRaichuk** [comment]
When has this happened to you? Exact date(timestamp) would help me figure out if the problem was on our or your side.
Also what is your username?

**Comment by yjp999** [comment]
Thanks，It's my client network issue.
