### ISSUE TITLE
[bug] MacOS dump_to_video script not working

### ISSUE THREAD

**Issue by AZJaffe** [google-research/football#167]
I'm trying to generate the `.avi` file from a dump generated during training on my Macbook using the `gfootball.dump_to_video` script, however no file is generated. I'm not sure why this is not working.

```
python3 -m gfootball.dump_to_video --trace_file ${dump_path}/score_20200505-205015965164.dump -v 1
I0508 14:30:53.965121 4782609856 observation_processor.py:403] Dump "episode_done": too frequent
```

On another machine running Ubuntu 16.04, the same command outputs the following:
```
python3 -m gfootball.dump_to_video --trace_file=${dump_path}/score_20200505-205015965164.dump -v 1
I0508 14:23:41.365184 139922614441728 observation_processor.py:269] Video written to ${dump_path}/episode_done_20200508-142341117979.avi
I0508 14:23:41.365384 139922614441728 observation_processor.py:280] Dump written to ${dump_path}/episode_done_20200508-142341117979.dump
```
Any help would be appreciated.

**Comment by vi3itor** [comment]
I have the same issue on macOS. But when I try debugging, everything works. It looks like the script should sleep for some time to wait until some library has been loaded.

**Comment by qstanczyk** [comment]
Can you check what timeit.default_timer() returns here:
https://github.com/google-research/football/blob/master/gfootball/env/observation_processor.py#L477

"too frequent" means video wasn't written as the previous one was recorded recently, but from your log it looks like it should be the first one to be written.... so I guess maybe timeit.default_timer() counts in your setup from 0 on the task start?

**Comment by vi3itor** [comment]
I printed out the values:
`timeit.default_timer(): 0.263254923`
`config._last_dump_time: 0`
`config._min_frequency: 10`
Yes, it looks like it counts from 0. The values are different on each run, but never bigger than 1.
In fact, when I `import time` and put 
`time.sleep(10)`
before line 477, it works fine and outputs the video.

**Comment by qstanczyk** [comment]
Ok, thanks for checking. I made a change to fix this in our internal repository - will push a fix with the next release.
To fix this locally you can just initialize config._last_dump_time to -10.
