### ISSUE TITLE
Error while trying to play with trained agent

### ISSUE THREAD

**Issue by k4rth33k** [google-research/football#169]
I've created a custom action set and trained with it. Even when I've passed the action_set attribute it says there is a mismatch in shapes.
I ran the following command
`python3 -m gfootball.play_game --action_set custom --players "ppo2_cnn:left_players=1,policy=cnn,checkpoint=../dumps/openai-2020-05-10-10-06-02-235576/checkpoints/01900" --level=academy_single_goal_versus_lazy`
And I get
`ValueError: Dimension 1 in both shapes must be equal, but are 19 and 4. Shapes are [512,19] and [512,4]. for 'Assign_8' (op: 'Assign') with input shapes: [512,19], [512,4].`
Any help is appreciated.

**Comment by AntonRaichuk** [comment]
Could you try changing "self._action_set = 'default'" in ppo2_cnn.py to
"self._action_set = env_config.get('action_set', 'default')"

Let us know if that works

**Comment by k4rth33k** [comment]
@AntonRaichuk Yes, it worked. I named the custom action set as 'custom' so I used that instead of default in ppo2_cnn.py. Apologies for the late response.
