### ISSUE TITLE
freezing of ubuntu system

### ISSUE THREAD

**Issue by kmeagle1515** [google-research/football#17]
waited for half an hour,happens exactly while running setup.py for gfootball
![Screenshot from 2019-06-15 02-10-34](https://user-images.githubusercontent.com/46345142/59537237-a496af00-8f13-11e9-9a37-6019851dde5e.png)

**Comment by qstanczyk** [comment]
Does it unfreeze later on? How many cores your CPU has?
Try reducing parallelism of gfootball compilation in football/gfootball/build_game_engine.sh
by changing `make -j10`

**Comment by kmeagle1515** [comment]
NO, my laptop hangs so i need to restart my laptop. 
i have a quad core processor, so should i try -j5 according to this https://blog.kitware.com/cmake-building-with-all-your-cores/

**Comment by qstanczyk** [comment]
Freeze can be caused by compilation process taking too much RAM, so if you keep getting this issue then trying lower value than -j5 might be needed.

**Comment by kmeagle1515** [comment]
okay thanks i'll inform you how it goes

**Comment by kmeagle1515** [comment]
@qstanczyk thanks it worked.
