### ISSUE TITLE
About the Court data

### ISSUE THREAD

**Issue by yumianhuli2** [google-research/football#172]
what about the length and width of the court？Thank you！

**Comment by qstanczyk** [comment]
What do you mean exactly. Coordinate ranges are described here https://github.com/google-research/football/blob/master/gfootball/doc/observation.md

**Comment by yumianhuli2** [comment]
> What do you mean exactly. Coordinate ranges are described here https://github.com/google-research/football/blob/master/gfootball/doc/observation.md
Hello！I do not want to know the pixel of Court,I want to know the actual length and width of Court in the game.Thank u!

**Comment by andrewchou** [comment]
@yumianhuli2 
https://github.com/google-research/football/blob/master/third_party/gfootball_engine/src/gamedefines.hpp#L243
Confusingly the measurements are in meters tho, so for example the penalty box is not 18

**Comment by yumianhuli2** [comment]
> @yumianhuli2
> https://github.com/google-research/football/blob/master/third_party/gfootball_engine/src/gamedefines.hpp#L243
> Confusingly the measurements are in meters tho, so for example the penalty box is not 18

Thank you very much for your help
