### ISSUE TITLE
About dump_to_txt.py

### ISSUE THREAD

**Issue by yumianhuli2** [google-research/football#174]
1、python dump_to_txt.py --dump=/tmp/input.dump --output=/tmp/output.txt
Traceback (most recent call last):
  File "dump_to_txt.py", line 27, in <module>
    from gfootball.env import script_helpers
ImportError: No module named gfootball.env

2、 And is there a example like python3 -m gfootball.examples.XXX --dump_full_episodes=True --render=True for a 11vs11 match？

**Comment by vi3itor** [comment]
@yumianhuli2 Did you try `python3` instead? `No module named gfootball.env` probably means that you have used a different version of python to install the project. It might be the same issue #62 as you reported 10 months ago and it's more likely connected with your system set-up.

**Comment by qstanczyk** [comment]
Please reopen if problem is still there.
