### ISSUE TITLE
Evaluation Protocol of Table 5, 6

### ISSUE THREAD

**Issue by IouJenLiu** [google-research/football#176]
Hi 
Thanks for this great environment!
For fair comparison, I would like to make sure I follow your evaluation protocol exactly. 
In GFootball paper, Table 5 and Table 6 reported average scores of 5 runs. I was wondering if the scores are from training episode or evaluation episode. How many episode scores are averaged for each run?  Thanks so much!

**Comment by AntonRaichuk** [comment]
We average the score of the last 100 episodes before the corresponding threshold (20/50/500M). And those episodes are coming from training data.

**Comment by IouJenLiu** [comment]
Thanks!
