### ISSUE TITLE
ModuleNotFoundError: No module named 'gfootball_engine'

### ISSUE THREAD

**Issue by LightHouse2000** [google-research/football#177]
I have been training my own modle on colab for a period of time. Recently I tried to build your environment on my own remote server. After I installed the required packages:
`apt-get install git cmake build-essential libgl1-mesa-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libboost-all-dev libdirectfb-dev libst-dev mesa-utils xvfb x11vnc libsdl-sge-dev python3-pip`
 I tried the commands in colab sample:
`git clone -b v2.0.7 https://github.com/google-research/football.git`
`mkdir -p football/third_party/gfootball_engine/lib`
`wget https://storage.googleapis.com/gfootball/prebuilt_gameplayfootball_v2.0.7.so -O football/third_party/gfootball_engine/lib/prebuilt_gameplayfootball.so`
`cd football && GFOOTBALL_USE_PREBUILT_SO=1 pip3 install .`
it shows that gfootball is sucessfully installed，but when I used `import gfootball.env as football_env` I got the mistake:
`Traceback (most recent call last):`
`  File "train.py", line 1, in <module>`
`    import gfootball.env as football_env`
`  File "/football/gfootball/__init__.py", line 17, in <module>`
`    from gfootball.env import scenario_builder`
`  File "/football/gfootball/env/__init__.py", line 21, in <module>`
`    from gfootball.env import config`
`  File "/football/gfootball/env/config.py", line 27, in <module>`
`    import gfootball_engine as libgame`
`ModuleNotFoundError: No module named 'gfootball_engine'`

**Comment by qstanczyk** [comment]
Did you use the right version of Python when trying to run environment?
Please also give Docker a try in case problem persists: https://github.com/google-research/football/blob/master/gfootball/doc/docker.md

**Comment by qstanczyk** [comment]
Please reopen if this is still an issue

**Comment by LightHouse2000** [comment]
The problem persists and I finally trained my model through COLAB to complete my assignment.
Still hope you can refine it.

**Comment by qstanczyk** [comment]
Why do you try to use prebuilt binary on your local machine? Can't you use Docker / local installation as described [here](https://github.com/google-research/football/)?
