### ISSUE TITLE
PIP Install error 

### ISSUE THREAD

**Issue by Zaakir-Kamar** [google-research/football#178]
Everything works fine on my Ubuntu 18.04, with all deps. But, 'pip3 install' command fails because of SSL/TLS error

**Comment by vi3itor** [comment]
A proxy might be your problem. Try: `pip3 install --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org --upgrade pip`
As found [here](https://python-forum.io/Thread-Cannot-update-or-install-anything-with-pip-SSL-error) or [here](https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi). Try searching online for a problem that is not connected to football itself. I suggest closing the issue.

**Comment by Zaakir-Kamar** [comment]
Thank you very much for your support
