### ISSUE TITLE
where can I look at the python binding  for cpp?

### ISSUE THREAD

**Issue by chakpongchung** [google-research/football#18]
I am debugging some issues, how to is the python binding generated? Is it using swig or pybind or other technique? How does the python code here interact with cpp engine?

**Comment by qstanczyk** [comment]
Have a look at football/third_party/gfootball_engine/ai.cpp
It uses boost::python.

**Comment by kkurach** [comment]
@chakpongchung Did you find it? Can we close this issue?

**Comment by kkurach** [comment]
Please re-open if you have any further questions about the bindings!
