### ISSUE TITLE
How to modify per agent's speed and accuracy?

### ISSUE THREAD

**Issue by Cranial-XIX** [google-research/football#187]
Hi,

I didn't find where to specify each agent's speed and accuracy. In addition, is there a full list of customizable attributes for each agent? Thanks a lot in advance.

**Comment by vi3itor** [comment]
Hi, 
to experiment with different attributes you might try changing them [in playerdata.cpp](https://github.com/google-research/football/blob/c14661121711109f70b043310fe7d5f9d96fb030/third_party/gfootball_engine/src/data/playerdata.cpp#L77). The names of the players are updated [later](https://github.com/google-research/football/blob/c14661121711109f70b043310fe7d5f9d96fb030/third_party/gfootball_engine/src/data/matchdata.cpp#L53).
To see how speed is calculated, search for `velocity` in `third_party/gfootball_engine`

**Comment by qstanczyk** [comment]
Depending on what you want to achieve there is also left/right team difficulty defined in each scenario file, for example: https://github.com/google-research/football/blame/master/gfootball/scenarios/11_vs_11_competition.py#L25
It controls all players on a given team that are controlled by the built-in AI.

**Comment by Cranial-XIX** [comment]
@vi3itor Hi, I tried to modify the attributes as you specified, but it seems even if I manually create different agents with different attributes and include them in teamdata.cpp, there's no effect on the actual agent, though when I print out the playerdata those properties are indeed different.
