### ISSUE TITLE
Failed to build baselines

### ISSUE THREAD

**Issue by wbhstudy** [google-research/football#19]
root@f869a41fc79e:/home/baselines# pip3 install "git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6"
Collecting baselines-0.1.6 from git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6
  Cloning https://github.com/openai/baselines.git (to revision master) to /tmp/pip-install-fai6zwi2/baselines-0.1.6
  Running command git clone -q https://github.com/openai/baselines.git /tmp/pip-install-fai6zwi2/baselines-0.1.6
  WARNING: Generating metadata for package baselines-0.1.6 produced metadata for project name baselines. Fix your #egg=baselines-0.1.6 fragments.
Requirement already satisfied (use --upgrade to upgrade): baselines from git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6 in /home/baselines
Requirement already satisfied: click in /usr/local/lib/python3.6/dist-packages (from baselines) (7.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.6/dist-packages (from baselines) (1.2.1)
Requirement already satisfied: gym<1.0.0,>=0.10.0 in /usr/local/lib/python3.6/dist-packages/gym-0.12.5-py3.6.egg (from baselines) (0.12.5)
Requirement already satisfied: joblib in /usr/local/lib/python3.6/dist-packages (from baselines) (0.13.2)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.6/dist-packages/opencv_python-4.1.0.25-py3.6-linux-x86_64.egg (from baselines) (4.1.0.25)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages/scipy-1.3.0-py3.6-linux-x86_64.egg (from baselines) (1.3.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from baselines) (4.32.1)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.6/dist-packages (from gym<1.0.0,>=0.10.0->baselines) (1.16.4)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python3.6/dist-packages (from gym<1.0.0,>=0.10.0->baselines) (1.3.2)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from gym<1.0.0,>=0.10.0->baselines) (1.11.0)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from pyglet>=1.2.0->gym<1.0.0,>=0.10.0->baselines) (0.17.1)
Building wheels for collected packages: baselines, baselines
  Building wheel for baselines (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-1vc90d02/wheels/47/4b/a3/0a25aebc24e2f3302802b56aef9855b3bc7bb051cc5bc3debd
  Building wheel for baselines (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-fai6zwi2/baselines/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', op
en)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-48qo3hxs --python-tag cp36:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.6/tokenize.py", line 452, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-fai6zwi2/baselines/setup.py'
  ----------------------------------------
  ERROR: Failed building wheel for baselines
  Running setup.py clean for baselines
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-fai6zwi2/baselines/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', op
en)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.6/tokenize.py", line 452, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-fai6zwi2/baselines/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for baselines
Successfully built baselines
Failed to build baselines

**Comment by cyfra** [comment]
Which version of pip are you using ?

Can you double check that you've uninstalled any other "baselines" versions that you could have installed before ?

**Comment by wbhstudy** [comment]
HI，
root@f869a41fc79e:/# pip3 uninstall baselines
Can't uninstall 'baselines'. No files were found to uninstall.



i have run uninstall .


root@f869a41fc79e:/# pip --version
pip 19.1.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
root@f869a41fc79e:/#





thank you.




------------------ 原始邮件 ------------------
发件人: "Marcin Michalski"<notifications@github.com>;
发送时间: 2019年6月17日(星期一) 下午2:05
收件人: "google-research/football"<football@noreply.github.com>;
抄送: "宝华"<88214839@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [google-research/football] Failed to build baselines (#19)




Which version of pip are you using ?
 
Can you double check that you've uninstalled any other "baselines" versions that you could have installed before ?

**Comment by wbhstudy** [comment]
root@1631c988b0e9:/gfootball# pip3 uninstall baselines
Uninstalling baselines-0.1.5:
  /usr/local/lib/python3.6/dist-packages/baselines-0.1.5-py3.6.egg
Proceed (y/n)? y
  Successfully uninstalled baselines-0.1.5
root@1631c988b0e9:/gfootball# pip3 install "git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6"
Collecting baselines-0.1.6 from git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6
  Cloning https://github.com/openai/baselines.git (to master) to /tmp/pip-build-v2hm5zsu/baselines-0.1.6
  Running setup.py (path:/tmp/pip-build-v2hm5zsu/baselines-0.1.6/setup.py) egg_info for package baselines-0.1.6 produced metadata for project name baselines. Fix your #egg=baselines-0.1.6 frag
ments.
Collecting click (from baselines)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |################################| 81kB 5.3kB/s
Collecting cloudpickle (from baselines)
  Downloading https://files.pythonhosted.org/packages/09/f4/4a080c349c1680a2086196fcf0286a65931708156f39568ed7051e42ff6a/cloudpickle-1.2.1-py2.py3-none-any.whl
Requirement already satisfied: gym<1.0.0,>=0.10.0 in /usr/local/lib/python3.6/dist-packages/gym-0.12.5-py3.6.egg (from baselines)
Collecting joblib (from baselines)
  Downloading https://files.pythonhosted.org/packages/cd/c1/50a758e8247561e58cb87305b1e90b171b8c767b15b12a1734001f41d356/joblib-0.13.2-py2.py3-none-any.whl (278kB)
    100% |################################| 286kB 73kB/s
Requirement already satisfied: opencv-python in /usr/local/lib/python3.6/dist-packages/opencv_python-4.1.0.25-py3.6-linux-x86_64.egg (from baselines)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages/scipy-1.3.0-py3.6-linux-x86_64.egg (from baselines)
Collecting tqdm (from baselines)
  Downloading https://files.pythonhosted.org/packages/45/af/685bf3ce889ea191f3b916557f5677cc95a5e87b2fa120d74b5dd6d049d0/tqdm-4.32.1-py2.py3-none-any.whl (49kB)
    100% |################################| 51kB 67kB/s
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.6/dist-packages (from gym<1.0.0,>=0.10.0->baselines)
Collecting pyglet>=1.2.0 (from gym<1.0.0,>=0.10.0->baselines)
  Downloading https://files.pythonhosted.org/packages/1c/fc/dad5eaaab68f0c21e2f906a94ddb98175662cc5a654eee404d59554ce0fa/pyglet-1.3.2-py2.py3-none-any.whl (1.0MB)
    100% |################################| 1.0MB 137kB/s
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from gym<1.0.0,>=0.10.0->baselines)
Collecting future (from pyglet>=1.2.0->gym<1.0.0,>=0.10.0->baselines)
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
    100% |################################| 829kB 86kB/s
Building wheels for collected packages: future
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/0c/61/d2/d6b7317325828fbb39ee6ad559dbe4664d0896da4721bf379e
Successfully built future
Installing collected packages: click, cloudpickle, joblib, tqdm, baselines, future, pyglet
  Running setup.py install for baselines ... done
Successfully installed baselines-0.1.5 click-7.0 cloudpickle-1.2.1 future-0.17.1 joblib-0.13.2 pyglet-1.3.2 tqdm-4.32.1

**Comment by wbhstudy** [comment]
baselines.bench.__pycache__.benchmarks.cpython-36: module references __file__
creating /usr/local/lib/python3.6/dist-packages/baselines-0.1.5-py3.6.egg
Extracting baselines-0.1.5-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Adding baselines 0.1.5 to easy-install.pth file

Installed /usr/local/lib/python3.6/dist-packages/baselines-0.1.5-py3.6.egg
error: The 'baselines>=0.1.6' distribution was not found and is required by gfootball

**Comment by cyfra** [comment]
Please see #1 for explanation for 0.1.6 version.

**Comment by wbhstudy** [comment]
Cloning git://github.com/openai/baselines.git (to master) to /tmp/pip-build-dehpmyt3/baselines
  Requested baselines>=0.1.6 from git+git://github.com/openai/baselines.git@master#egg=baselines>=0.1.6, but installing version None

**Comment by wbhstudy** [comment]
**Successfully uninstalled baselines-0.1.5
root@1631c988b0e9:/home# pip3 install "git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6"**
Collecting baselines-0.1.6 from git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6
  Cloning https://github.com/openai/baselines.git (to master) to /tmp/pip-build-1gi4z238/baselines-0.1.6
  **Running setup.py (path:/tmp/pip-build-1gi4z238/baselines-0.1.6/setup.py) egg_info for package baselines-0.1.6 produced metadata for project name baselines. Fix your #egg=baselines-0.1.6 frag
ments.**
Requirement already satisfied: click in /usr/local/lib/python3.6/dist-packages (from baselines)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.6/dist-packages (from baselines)
Requirement already satisfied: gym<1.0.0,>=0.10.0 in /usr/local/lib/python3.6/dist-packages/gym-0.12.5-py3.6.egg (from baselines)
Requirement already satisfied: joblib in /usr/local/lib/python3.6/dist-packages (from baselines)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.6/dist-packages/opencv_python-4.1.0.25-py3.6-linux-x86_64.egg (from baselines)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages/scipy-1.3.0-py3.6-linux-x86_64.egg (from baselines)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from baselines)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.6/dist-packages (from gym<1.0.0,>=0.10.0->baselines)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python3.6/dist-packages (from gym<1.0.0,>=0.10.0->baselines)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from gym<1.0.0,>=0.10.0->baselines)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from pyglet>=1.2.0->gym<1.0.0,>=0.10.0->baselines)
Installing collected packages: baselines
  Running setup.py install for baselines ... done
**Successfully installed baselines-0.1.5**
root@1631c988b0e9:/home#

**Comment by cyfra** [comment]
@wbhstudy  - do I understand correctly, that it worked now ? Does the environment run fine ?

**Comment by wbhstudy** [comment]
i can't install baseline0.1.6 ,
just install 0.1.5
Successfully installed baselines-0.1.5


but gfootball need baseline-0.1.6.




------------------ 原始邮件 ------------------
发件人: "Marcin Michalski"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 凌晨5:50
收件人: "google-research/football"<football@noreply.github.com>;
抄送: "宝华"<88214839@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [google-research/football] Failed to build baselines (#19)




@wbhstudy  - do I understand correctly, that it worked now ? Does the environment run fine ?

**Comment by wbhstudy** [comment]
pip3 install "git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6"
this don't work， it finally install baseline-0.1.5

**Comment by alew3** [comment]
I'm trying to run python3 -m gfootball.play_game inside the Docker and also get an error that baseline wasn't installed. 
ImportError: No module named 'baselines'

I can install it with the command above pip3 install "git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6"

**Comment by cyfra** [comment]
Good news - the openAI approved the PR that increases the version to 0.1.6 - which means that now, installing from github should result with 0.1.6
