### ISSUE TITLE
KeyError: 'ppo2_model/pi/c1/w:0'

### ISSUE THREAD

**Issue by RyanLHU** [google-research/football#191]
When I try to run the program with pre-trained PPO checkpoint
python3 -m gfootball.play_game --players "keyboard:left_players=1;ppo2_cnn:right_players=1,checkpoint=$YOUR_PATH"

The script shows an error "KeyError: 'ppo2_model/pi/c1/w:0'"

**Comment by max37400** [comment]
@RyanLHU Hello!
Is there any cnance that you have already found the solution?
Thank you!

**Comment by qstanczyk** [comment]
Please reopen if this is still an issue

**Comment by randomwalker8** [comment]
I am having the same error with tensorflow 1.5. any updates?
