### ISSUE TITLE
Conda support on MacOS

### ISSUE THREAD

**Issue by OshriHalimi** [google-research/football#192]
Hey, 
Thank you for your great work!

I want to configure this project on my MacBook and I want to make the installations in a dedicated conda environment.
Is it possible? How should I install the dependencies and the setup procedure?

Thanks!

**Comment by vi3itor** [comment]
Hey again. It should be possible, but I don't have `conda` installed to check. There were some reports of errors, but it was probably because of boost-python3 installed with `brew` rather than with `conda`. Keep that in mind when choosing packages.

**Comment by backpropper** [comment]
Hi, Is there an update on this? Would be great to have this issue sorted out soon.

**Comment by vi3itor** [comment]
Have you tried it yet? Are you experiencing any problems with installation/running?

**Comment by backpropper** [comment]
Yeah I did try it and had issues installing it. I am using macOS 10.15.6 and python 3.7 (via `conda`). All the listed libraries in the instructions are installed via `brew`.
Here's the build log file: 
[log.txt](https://github.com/google-research/football/files/5255736/log.txt)

**Comment by vi3itor** [comment]
> Yeah I did try it and had issues installing it. I am using macOS 10.15.6 and python 3.7 (via `conda`). All the listed libraries in the instructions are installed via `brew`.
> Here's the build log file:
> [log.txt](https://github.com/google-research/football/files/5255736/log.txt)

The provided log states that the SDL2_image library is missing, make sure that you have it installed:
> Could NOT find SDL2_image (missing: SDL2_IMAGE_LIBRARIES

But overall, if you want to run the project with `anaconda` and use Python 3.7, you should probably install compatible `boost` and `boost-python3` not via `brew` but via `anaconda` (as far as I remember, the same way as you install other packages). 

You can also try installing a compatible version of `boost-python3` with `brew` as explained in this [comment](https://github.com/google-research/football/issues/108#issuecomment-675802842).

**Comment by backpropper** [comment]
Thanks so I installed those libraries and was able to install the package successfully. But now have another issue that I found is already open #156
