### ISSUE TITLE
Issue with pixel representation

### ISSUE THREAD

**Issue by shehrum** [google-research/football#195]
### Mac OS Catalina 10.15.4

I get the following error when I change the representation to pixels, or grayscale pixels.

```
Traceback (most recent call last):

  File "train.py", line 4, in <module>
    env.reset()
  File "/Users/shehrum/Documents/football/football-env/lib/python3.7/site-packages/gym/core.py", line 230, in reset
    return self.env.reset(**kwargs)
  File "/Users/shehrum/Documents/football/football-env/lib/python3.7/site-packages/gym/core.py", line 258, in reset
    return self.observation(observation)
  File "/Users/shehrum/Documents/football/football-env/lib/python3.7/site-packages/gfootball/env/wrappers.py", line 209, in observation
    frame = observation['frame']
KeyError: 'frame'
```

Code: 

```
import gfootball.env as football_env
import numpy as np
env = football_env.create_environment(representation='pixels',env_name="11_vs_11_hard_stochastic", stacked=False, logdir='logs', write_goal_dumps=False, write_full_episode_dumps=False,write_video=False ,render=False,number_of_left_players_agent_controls=1 ,number_of_right_players_agent_controls=1,rewards='scoring,checkpoints')
env.reset()
steps = 0
n_episodes=1
print(env.observation_spaces.shape)
```

It works fine if I use the default representation 'extracted'.

**Comment by shehrum** [comment]
I tried with and without `render=True` but that didn't help

**Comment by vi3itor** [comment]
I can reproduce it on Mac and Ubuntu. The problem is gone if you control only one team:
`number_of_left_players_agent_controls=1, number_of_right_players_agent_controls=0`

@qstanczyk is it designed to be so? Or is it a bug? 
 
@shehrum BTW, you have to use `render=True` with `pixels` representation.

**Comment by qstanczyk** [comment]
Yes, pixel representation depends on the rendering and game renders only a single view. As observations for the right team are mirrored for convenience, we would have to render the scene twice as well. I will update the implementation adding more descriptive error.
