### ISSUE TITLE
"no matches found: gfootball[tf_cpu]" - possible problem with Conda environment?

### ISSUE THREAD

**Issue by GaurangTandon** [google-research/football#20]
Hi, I was just trying out the repo, and I got stuck at a simple point. Could someone please help me figure the problem out? I did the following:

1. Do step 1 from under [Installation](https://github.com/google-research/football#installation). This prompted me to do `sudo dpkg --configure -a` which I did first, and then did that `sudo apt install`.
2. That works, then since we are installing python packages, I thought it to be a good idea to create a new environment for step 2. So, I did:

    ```
    conda create -n googlefootball python=3.7 anaconda
    conda activate googlefootball
    ```

3. Finally I did the step 2, `pip3 install gfootball[tf_cpu] --process-dependency-link`. But it gives this error:

    ```
    zsh: no matches found: gfootball[tf_cpu]
    ````

Where did I do wrong? Am I not supposed to use conda environments for this? Thanks!

**Comment by cyfra** [comment]
This seems to be related to zsh (we usually use bash :-)

Try adding quotes:
pip3 install "gfootball[tf_cpu]" --process-dependency-link

**Comment by GaurangTandon** [comment]
Ah, but now on changing that I get a new error :P

```
Usage:   
  /home/gt/anaconda3/envs/googlefootball/bin/python3.7 -m pip install [options] <requirement specifier> [package-index-options] ...
  /home/gt/anaconda3/envs/googlefootball/bin/python3.7 -m pip install [options] -r <requirements file> [package-index-options] ...
  /home/gt/anaconda3/envs/googlefootball/bin/python3.7 -m pip install [options] [-e] <vcs project url> ...
  /home/gt/anaconda3/envs/googlefootball/bin/python3.7 -m pip install [options] [-e] <local project path> ...
  /home/gt/anaconda3/envs/googlefootball/bin/python3.7 -m pip install [options] <archive url/path> ...

no such option: --process-dependency-link
```

**Comment by gumush** [comment]
It's about version of PIP , 18.01 version works with --process-dependency-link. 
You can downgrade 

`pip install --upgrade pip==18.01 `
