### ISSUE TITLE
Question on _retrieve_observation function in football_env_core  file

### ISSUE THREAD

**Issue by cookie-yang** [google-research/football#206]
![image](https://user-images.githubusercontent.com/17507081/90610120-9212b680-e237-11ea-9dfe-fb902924c1c0.png)

I have a shape question on line 272, why the parameters in reshape is [3,720,1280]? And could you please explain what these lines do from line 271 to 276.

Thanks a lot

**Comment by qstanczyk** [comment]
Game renders in 1280x720, so the same dimension is used here (3 is for R,G,B). Game returns data in [R,G,B], [R,G,B] sequence, while for processing inside Python [GGGGGG....], [BBBBB....], [RRRRR...] is used, so data is reordered in the lines below.

**Comment by cookie-yang** [comment]
Thanks for replying, but I wonder in line 272, np.reshape(np.concatencate([frame[...,0],frame[...,1],frame[...,2]]),[3,720,1280])
why the shape here is [3,720,1280]?  I thought is [3,1280,720]

**Comment by qstanczyk** [comment]
There are 1280 consecutive pixels in the buffer for each Y coordinate, so the most inner dimension is 1280. The other shape should actually be [720,1280], not [1280, 720].
