### ISSUE TITLE
PIP Install GFootball - error 

### ISSUE THREAD

**Issue by ahmadshahrokhi** [google-research/football#208]
i am a master student at AI & Robotics.
my thesis is based on google football research environment. so i really need to install this env.
i am using ubuntu 20.04.
i tried to install the env with your steps to install it on linux, so:
1. Install required packages: this step was done perfectly.
and then i tried:
2a. From PyPi package:
pip3 install gfootball.
this resulted in an error. this a the error: 

base) kingface@kingface-Lenovo-ideapad-520-15IKB:~/football$ pip3 install gfootball
Collecting gfootball
  Using cached gfootball-2.1.tar.gz (8.7 MB)
Collecting pygame==1.9.6
  Using cached pygame-1.9.6.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/kingface/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jtra5syu/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jtra5syu/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-w_sajxzg
         cwd: /tmp/pip-install-jtra5syu/pygame/
    Complete output (18 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    
    Hunting dependencies...
    SDL     : found 1.2.15
    FONT    : not found
    IMAGE   : not found
    MIXER   : not found
    PNG     : found
    JPEG    : found
    SCRAP   : found
    PORTMIDI: not found
    PORTTIME: not found
    FREETYPE: found 23.1.17
    Missing dependencies
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

so i tried the : 2b. Installing from sources using GitHub repository:
git clone https://github.com/google-research/football.git
cd football

these two lines was done fine. then:

python3 -m venv football-env
source football-env/bin/activate

these two lines was done fine. then:

pip3 install .

with this line i get the error once again, this is the error:

(football-env) (base) kingface@kingface-Lenovo-ideapad-520-15IKB:~/football$ pip3 install .
Processing /home/kingface/football
Collecting pygame==1.9.6
  Using cached pygame-1.9.6.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/kingface/football/football-env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jz2tou29/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jz2tou29/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-c25vnicc
         cwd: /tmp/pip-install-jz2tou29/pygame/
    Complete output (18 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    
    Hunting dependencies...
    SDL     : found 1.2.15
    FONT    : not found
    IMAGE   : not found
    MIXER   : not found
    PNG     : found
    JPEG    : found
    SCRAP   : found
    PORTMIDI: not found
    PORTTIME: not found
    FREETYPE: found 23.1.17
    Missing dependencies
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

i had this error on ubuntu 19.04 and i thought if i upgrade my ubuntu to 20.04 this problem would be fixed, but it's not.

**Comment by ahmadshahrokhi** [comment]
the error was because of the pygame.

**Comment by simratsingh14** [comment]
> the error was because of the pygame.

I am getting the same error. Could you tell exactly what fixed your problem
