### ISSUE TITLE
[Question] Reward logging for goal only

### ISSUE THREAD

**Issue by yutaizhou** [google-research/football#210]
I am training agents using both the `scoring` and `checkpoints` wrapper. I would like to understand how the different wrappers used can impact the reward logging. 

In the multiagent setting, the default behavior is that every agent shares the same reward. This means if the team advances 10% of field length, every agent gets 0.1 point, if the team scores a goal, every agent gets 1 point. Is that correct?

If `checkpoints` wrapper is used, does the logged reward include the checkpoints rewards? If so, how can I log a goal-based only reward metric in addition to a goal+distance based reward metric?

**Comment by qstanczyk** [comment]
That is correct.
Trace dump contains 'score_reward' field which is reward part just for the score.
