### ISSUE TITLE
The problem of not accepting other actions after performing a pass

### ISSUE THREAD

**Issue by lich14** [google-research/football#215]
First, this is an amazing environment. However, when our lab wants to train RL algorithms, we find out that our agent will not listen to us after we let him to pass the ball. The action we give will only be executed after the pass is over. Actually I think this is a fundamental issue for training RL algorithms. Because our algorithms will reinforce exactly wrong action with environment external rewards. Seeing this, I feel pessimistic to train sufficient intelligence. I think there may or may not be some solutions. Always here for help.

**Comment by lich14** [comment]
Any opinions are good for me. In fact, it is strange to me that no one raised this question. Do I miss anything in this environment? When I train SC2, there is something called the available operation set. Is there such a thing in this environment? I am waiting humbly for your suggestions.

**Comment by qstanczyk** [comment]
Hi, there is no "available operation set" in the environment, however we managed to train RL agents with this environment just fine. Might be the case that "agent not listening" during the pass causes training to be less efficient, but this can be one of the scenarios in real world and making RL algorithms work in this setup is valuable from research perspective.

**Comment by lich14** [comment]
> Hi, there is no "available operation set" in the environment, however we managed to train RL agents with this environment just fine. Might be the case that "agent not listening" during the pass causes training to be less efficient, but this can be one of the scenarios in real world and making RL algorithms work in this setup is valuable from research perspective.

Okay, although I am not sure what kind of result is just fine, I will try to update my algorithm. Thanks for your attention. ^_^
