### ISSUE TITLE
Docker: can't open file 'gfootball.ppo_train.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Gimi456** [google-research/football#216]
Hello I have an issue, where my own python script cannot be found.
The ppo-train.py file is in the same directory as the dockerfile.

My dockerfile:
```
.
.
RUN pip3 install --use-feature=2020-resolver --no-cache-dir git+https://github.com/openai/baselines.git@master
COPY . /gfootball        # <--- This line here should copy every file in the same directory as the dockerfile to the docker directory gfootball, but in the end, I cant access my own file. But i can access examples!
RUN cd /gfootball && pip3 install --use-feature=2020-resolver .
WORKDIR '/gfootball'
```

I only use the cpu docker version. So, how can I fix this issue? Thanks in advance!

**Comment by qstanczyk** [comment]
File (gfootball.ppo_train.py) name is suspicious. Don't you try to load it with -m (in which case you should not provide .py suffix?).
