### ISSUE TITLE
WSL Ubuntu 20 Installation error

### ISSUE THREAD

**Issue by MrNeo28** [google-research/football#220]
I am using Win 10 Wsl2.0 Ubuntu

```
Collecting gfootball
  Using cached gfootball-2.5.tar.gz (8.7 MB)
Requirement already satisfied: absl-py in ./.local/lib/python3.8/site-packages (from gfootball) (0.9.0)
Requirement already satisfied: gym>=0.11.0 in ./.local/lib/python3.8/site-packages (from gfootball) (0.17.3)
Requirement already satisfied: opencv-python in ./.local/lib/python3.8/site-packages (from gfootball) (4.2.0.34)
Requirement already satisfied: pygame==1.9.6 in /usr/lib/python3/dist-packages (from gfootball) (1.9.6)
Requirement already satisfied: scipy in ./.local/lib/python3.8/site-packages (from gfootball) (1.4.1)
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (from gfootball) (0.34.2)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from absl-py->gfootball) (1.14.0)
Requirement already satisfied: numpy>=1.10.4 in ./.local/lib/python3.8/site-packages (from gym>=0.11.0->gfootball) (1.19.0)
Requirement already satisfied: pyglet<=1.5.0,>=1.4.0 in ./.local/lib/python3.8/site-packages (from gym>=0.11.0->gfootball) (1.5.0)
Requirement already satisfied: cloudpickle<1.7.0,>=1.2.0 in ./.local/lib/python3.8/site-packages (from gym>=0.11.0->gfootball) (1.6.0)
Requirement already satisfied: future in ./.local/lib/python3.8/site-packages (from pyglet<=1.5.0,>=1.4.0->gym>=0.11.0->gfootball) (0.18.2)
Building wheels for collected packages: gfootball
  Building wheel for gfootball (setup.py) ... |

```
More than one hour  I am stuck on building wheels, any solutions ?

**Comment by Arpit-Gole** [comment]
I have Ubuntu 20.04.1 running in Virtual Box on Windows 10.
I am following steps to install as directed [here](https://github.com/google-research/football).

My screen gets frozen here and then ends with an error. Please find the ![screenshot](https://user-images.githubusercontent.com/37917285/94980681-92e27c00-0549-11eb-8ad1-fa04d373868a.png).

**Comment by xincui-math** [comment]
It looks like you are running WSL. There is no output device on it? On my side, when compiling on Ubuntu 20.04, the only thing is to reinstall pythonlib38, then compile is successful.

**Comment by sczfaker** [comment]
> It looks like you are running WSL. There is no output device on it? On my side, when compiling on Ubuntu 20.04, the only thing is to reinstall pythonlib38, then compile is successful.

How to reinstall pythonlib38 on Ubuntu 20.04?

**Comment by qstanczyk** [comment]
It could be due to low memory. Compilation uses multiple cores and for systems with low memory it can cause issues. What is your CPU / memory setup? Please reopen with the update.

**Comment by simratsingh14** [comment]
I am getting the same error I am using Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz. with 8 gb ram.  Please tell the solution
