### ISSUE TITLE
Ubuntu 20.04.1 installation error

### ISSUE THREAD

**Issue by Arpit-Gole** [google-research/football#222]
I have Ubuntu 20.04.1 running in Virtual Box on Windows 10.
I am following steps to install as directed [on the main page](https://github.com/google-research/football).

My screen gets frozen on **Building wheel for gfootball** and then ends with an error.
**ERROR: Failed building wheel for gfootball.**
Please find the screenshots below:
![photo1](https://user-images.githubusercontent.com/37917285/94981840-15bc0480-0553-11eb-8f2c-5fc898ffc50b.png)
![photo2](https://user-images.githubusercontent.com/37917285/94981842-181e5e80-0553-11eb-82c1-f87d9d01810c.png)
Can you please list down easy to install steps for this project?

**Comment by antyj1994** [comment]
same error happens for me.

i7 920, 6gb ram, nvidia 1060

**Comment by tisttsf** [comment]
> same error happens to me.
> 
> i7 920, 6gb ram, nvidia 1060

Do you solve that problem?

**Comment by antyj1994** [comment]
Yes, it is memory problem.
Installation creates a large number of threads to install it faster and this causes memory leakage in low RAM machines.
I just solved this by going in the .sh installation file (don't remember exact name but should be something like setup.sh or build.sh) inside main gfootball directory and change the make... "-j [N-THREADS]" into "-j 1"

**Comment by qstanczyk** [comment]
Making a change to limit parallelism based on memory available. Will be out in the next release.
