### ISSUE TITLE
Get error "Couldn't load GL function glBegin: Video subsystem has not been initialized" when I try to set `--render=True`.

### ISSUE THREAD

**Issue by stephenllh** [google-research/football#223]

**Comment by pnxenopoulos** [comment]
Is this in Docker? See https://github.com/google-research/football/issues/44#issuecomment-512720206

**Comment by stephenllh** [comment]
> Is this in Docker? See [#44 (comment)](https://github.com/google-research/football/issues/44#issuecomment-512720206)

I installed all packages in a virtual environment. Doesn't work too.

**Comment by vi3itor** [comment]
Check out other open (and closed) issues, there is a chance that your system doesn't support OpenGL 3.2.

**Comment by qstanczyk** [comment]
Do you have DISPLAY environment variable set? Please try 2.8 release which adds support for off-screen rendering. Please reopen if the problem still exists.
