### ISSUE TITLE
Docker on MacOS error: XDG_RUNTIME_DIR not set in the environment

### ISSUE THREAD

**Issue by mikhail-vlasenko** [google-research/football#224]
I set up a CPU docker with 4gb RAM on my mac but when I try to play the game with 
`python3 -m gfootball.play_game --action_set=full`
it gives the `error: XDG_RUNTIME_DIR not set in the environment.`
Issue #44 (from 2019) has the same problem. The answer there is that it is not possible to render in Docker. However, since Jun 8, 2020 the docker set up [page](https://github.com/google-research/football/blob/master/gfootball/doc/docker.md) in the readme states the opposite 

> Inside the Docker image you can interact with the environment the same way as in case of local installation. For example, to play the game yourself you can run:

Is there a way to fix it?

**Comment by vi3itor** [comment]
No, it's not possible to render in Docker on macOS. See #188.
