### ISSUE TITLE
TypeError: __init__() should return None, not 'NoneType'

### ISSUE THREAD

**Issue by asappia** [google-research/football#226]
Error:
(football-env) ➜  football git:(master) python -m gfootball.play_game --action_set=full 
Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/xxx/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/xxx/dev/football/gfootball/play_game.py", line 70, in <module>
    app.run(main)
  File "/Users/xxx/dev/football/football-env/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Users/xxx/dev/football/football-env/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/xxx/dev/football/gfootball/play_game.py", line 46, in main
    cfg = config.Config({
  File "/Users/xxx/dev/football/gfootball/env/config.py", line 98, in __init__
    self.NewScenario()
  File "/Users/xxx/dev/football/gfootball/env/config.py", line 153, in NewScenario
    self._scenario_cfg = scenario_builder.Scenario(self).ScenarioConfig()
  File "/Users/xxx/dev/football/gfootball/env/scenario_builder.py", line 62, in __init__
    scenario.build_scenario(self)
  File "/Users/xxx/dev/football/gfootball/scenarios/11_vs_11_stochastic.py", line 33, in build_scenario
    builder.AddPlayer(-1.000000, 0.000000, e_PlayerRole_GK)
  File "/Users/xxx/dev/football/gfootball/env/scenario_builder.py", line 108, in AddPlayer
    player = Player(x, y, role, lazy, controllable)
TypeError: __init__() should return None, not 'NoneType'

Step to reproduce:
brew install git python3 cmake sdl2 sdl2_image sdl2_ttf sdl2_gfx boost boost-python3
brew install sdl sdl_image sdl_mixer sdl_ttf portmidi
cd dev
git clone https://github.com/google-research/football.git
cd football
python3 -m venv football-env
source football-env/bin/activate
pip3 install .
python3 -m gfootball.play_game --action_set=full

Env:
MacOs Catalina 10.15.7
Use of pyenv in place

**Comment by vi3itor** [comment]
Your error is very similar to one that other folks have when using `Anaconda` (e.g. #156). Did your try using `brew`'s version of Python 3.8 instead of `pyenv` to create a virtual environment as I noted [here](https://github.com/google-research/football/issues/156#issuecomment-663548057):
```$(brew --prefix python3)/bin/python3.8 -m venv football-env```

**Comment by audunae** [comment]
Runnnig $(brew --prefix python3)/bin/python3.8 -m venv football-env gives "syntax error near unexpected token `/bin/python3.8"

**Comment by vi3itor** [comment]
What version of `python` do you have? What is the result of command `python3 -V`?

**Comment by audunae** [comment]
I have version 3.8.6.

**Comment by audunae** [comment]
I have deleted Anaconda, reinstalled everything with reboot and tried with python 3.7.5 too. Tried with and without the virtual environments. My error message is identical to the one "asappia" get

**Comment by vi3itor** [comment]
It's quite hard to give any advice without knowing the whole picture. If you uninstalled Anaconda, you should've installed `python3` using `brew`? I'm wondering how you can get python 3.7.5 if the default major version in `brew` is 3.8. As I explained earlier, in my opinion, the error `TypeError: __init__() should return None, not 'NoneType'` happens when someone installs `boost-python3` with `brew`, but for installing football uses `python3` that doesn't come from `brew`.

**Comment by audunae** [comment]
Ah ok, that is probably the case then. Just thought the packages had to be installed with brew not Python it self. Thanks for your help, I really appreciate it.

**Comment by dtinblack** [comment]
I get the same error after following the instructions with Catalina 10.15.7 and python3 version 3.8.5. I have deleted and reinstalled all of the modules to create the environment but I still get the same errors as "asappia". Anaconda is not installed. I have used brew to install boost ( version 1.73.0 ) and boost-python3 ( version 1.73.0 ).  Do I need to install python3 using brew ?

**Comment by vi3itor** [comment]
@dtinblack Yes, as per instruction in readme.

**Comment by audunae** [comment]
It's been resolved for me now. Uninstalling the python3 versions that where installed from other sources did the trick.  Thank you so much @vi3itor

**Comment by dtinblack** [comment]
Thanks @vi3itor for your help. Like @audunae I deleted all of the packages that were installed from other sources and the package is now working.

**Comment by qstanczyk** [comment]
Could you propose a note to the readme to address this problem (and make a pull request)?

**Comment by yanxue7** [comment]
> Your error is very similar to one that other folks have when using `Anaconda` (e.g. #156). Did your try using `brew`'s version of Python 3.8 instead of `pyenv` to create a virtual environment as I noted [here](https://github.com/google-research/football/issues/156#issuecomment-663548057):
> `$(brew --prefix python3)/bin/python3.8 -m venv football-env`

@vi3itor Hi, I create a virtual env through `$(brew --prefix python3)/bin/python3.8 -m venv football-env` , and how can I list and revisit this env?

**Comment by vi3itor** [comment]
Hi @yanxue7, the command you executed created `football-env` directory inside the directory where you ran the command in the Terminal. To revisit (reactivate) the environment after you closed the Terminal window or rebooted Mac, open Terminal window again, navigate to the same directory (where `football-env` is located) and run `source football-env\bin\activate` to activate the environment.

**Comment by yanxue7** [comment]
> Hi @yanxue7, the command you executed created `football-env` directory inside the directory where you ran the command in the Terminal. To revisit (reactivate) the environment after you closed the Terminal window or rebooted Mac, open Terminal window again, navigate to the same directory (where `football-env` is located) and run `source football-env\bin\activate` to activate the environment.

Thanks for your help, I learn it.
