### ISSUE TITLE
Compilation error Python 3.8.5: relocation R_X86_64_PC32 against symbol `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by tragamota** [google-research/football#229]
Hi There, im getting a `relocation R_X86_64_PC32 against symbol _Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC` error while building the environment with python 3.8.5.

Tried multiple versions of python: 3.7.5, 3.6.3 -> not working.

Can someone help me? thanks 

Logs included -> [log.txt](https://github.com/google-research/football/files/5359170/log.txt)

**Comment by qstanczyk** [comment]
Have you tried adding fPIC [here](https://github.com/google-research/football/blob/7a5ae3b5c849beb69d15a7c0028f16d7297b1d9f/third_party/gfootball_engine/CMakeLists.txt#L21)?
Will try to drop those overrides to always use -fPIC.

**Comment by qstanczyk** [comment]
Will make fPIC the default in the next release.
