### ISSUE TITLE
running the game on deterministic mode

### ISSUE THREAD

**Issue by gekinci** [google-research/football#23]
Hi,

I would like to run the game in deterministic mode, as described in the blog post:

> Second, to investigate the impact of randomness, it can be run in both a stochastic mode (enabled by default), in which there is randomness in both the environment and opponent AI actions, and in a deterministic mode, where there is no randomness. 

How can I enable this? Thanks in advance.

**Comment by davidskuza** [comment]
https://github.com/google-research/football/blob/master/gfootball/scenarios/11_vs_11_stochastic.py#L25

You have to modify or create your own scenario and change that flag.
