### ISSUE TITLE
CMake Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)

### ISSUE THREAD

**Issue by scottmaran** [google-research/football#233]
I'm trying to install gFootball in a virtual environment created by pyenv but run into this error when I try `pip3 install gfootball`:

CMake Error at /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
      Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
      (Required is at least version "3")
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
      /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      CMakeLists.txt:44 (find_package)

It looks like the most common solution is to specify certain environment variables (https://stackoverflow.com/questions/44601548/cmake-could-not-find-pythonlibs/44601549). I'm not very familiar with CMake though and am not sure how to do this exactly.

Any help or suggestions is appreciated

**Comment by qstanczyk** [comment]
Could you try with Docker instead. I always works for me out of the box.

**Comment by qstanczyk** [comment]
PR #277 is not merged, Windows support added to the environment. Thanks @vi3itor for your great contribution. Closing this issue.

**Comment by nrodriguez-tupaca** [comment]
This is happening in OSX with Apple Silicon too!

```
    CMake Error at /opt/homebrew/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
      Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
      (Required is at least version "3")
    Call Stack (most recent call first):
      /opt/homebrew/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
      /opt/homebrew/Cellar/cmake/3.22.1/share/cmake/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      CMakeLists.txt:65 (find_package)
```

**Comment by nrodriguez-tupaca** [comment]
Found the solution for Apple (maybe only for Apple Silicon M1 - ARM- ? Not sure!)

Replace in third_party/gfootball_engine/CMakeLists.txt
```
if(UNIX)
  find_package(PythonLibs 3 REQUIRED)
else()
  set(PYTHONLIBS_VERSION_STRING $ENV{PY_VERSION})
endif()

message("Using Python: ${PYTHONLIBS_VERSION_STRING}")
string(REPLACE "." ";" VERSION_LIST ${PYTHONLIBS_VERSION_STRING})
list(GET VERSION_LIST 0 PYTHON_MAJOR)
list(GET VERSION_LIST 1 PYTHON_MINOR)
```

With
```
if(APPLE)
  find_package(Python 3 COMPONENTS Interpreter Development REQUIRED)
  set(PYTHON_MAJOR $ENV{Python_VERSION_MAJOR})
  set(PYTHON_MINOR $ENV{Python_VERSION_MINOR})
  set(PYTHONLIBS_VERSION_STRING ${Python_VERSION})
  set(PYTHON_INCLUDE_DIR ${Python_INCLUDE_DIRS})
  set(PYTHON_LIBRARIES ${Python_LIBRARIES})
  message("Apple - Using Python:${Python_VERSION_MAJOR} - Libraries:${PYTHON_LIBRARIES} - IncludeDirs: ${PYTHON_INCLUDE_DIR}")
elseif(UNIX)
  find_package(PythonLibs 3 REQUIRED)
else()
  set(PYTHONLIBS_VERSION_STRING $ENV{PY_VERSION})
endif()
```

**Comment by vi3itor** [comment]
Hi @nrodriguez-tupaca, 

Back in November, I [commited a fix](https://github.com/vi3itor/football/commit/922cfaf9d7d2d2073caabfd57d2ab9a3177fd922) in my fork to run football on Apple Silicon and tested it on 14-inch MB Pro (M1 Pro) and MB Air (M1). Unfortunately, I didn't have time to properly test it on supported Ubuntu systems and in Docker so I didn't send PR. 

I'll create a draft PR, so anyone who's facing such issue can easily get the fix.
