### ISSUE TITLE
How to create custom scenarios suing Python?

### ISSUE THREAD

**Issue by azadsalam** [google-research/football#234]
### How can I create custom scenarios programmatically using Python Code? 

I want to build scenarios dynamically in Python, similar to the [scenario](https://github.com/google-research/football/tree/master/gfootball/scenarios) files. 

I assume I will have to create a Scenario object, pass it as the `level` attribute of the config file and initialize the environment (see skeleton below), but I am not sure how to do this or, If this is the correct/easiest way).  

```
scenario = Scerio(..)

#add players to scenario
#set ball position to scenario

settings = {
    'action_set': "full",
    'dump_full_episodes': False,
    'real_time': True,
    'players': ['keyboard:left_players=1'],
    'level': <USE scenario here???>
}
cfg = config.Config(settings)


env = football_env.FootballEnv(cfg)
```

**Comment by qstanczyk** [comment]
scenario files are standard Python files, so you can generate scenarios dynamically within them. Just create a new "dynamic.py" scenario file. Does that solve your problem?

**Comment by azadsalam** [comment]
> scenario files are standard Python files, so you can generate scenarios dynamically within them. Just create a new "dynamic.py" scenario file. Does that solve your problem?

It is one way of solving the problem, which I am trying to follow. So I will be generating the scenario variables (e.g., number of players, their position, the position of ball, etc) dynamically, it would mean I will have to create a "dynamic.py" scenario file, and use it as the `level` argument?  I have one follow up question, does the "dynamic.py" scenario file has to be within the `gfootball.scenarios` module? 

What I was looking for is to not have this intermediate "dynamic.py" file at all, i.e., I generate the scenario variables dynamically and instantiate an `env = football_env.FootballEnv(...)` from that scenario.

**Comment by qstanczyk** [comment]
Currently scenario name defines a file describing scenario which is loaded. You can make a local change and accept a function as the value of the level parameter. In that case you would just call that function instead of loading scenario module.
