### ISSUE TITLE
Set trained model as opponent?

### ISSUE THREAD

**Issue by mc1893** [google-research/football#235]
Hello,
The paper says the following: _For self-play, one
can replace the opponent bot with any trained model._

How can I do this? I have trained a NN (saved as h5 or with checkpoints) with Tensorflow and want this model to take control of the right player and the left player should be controllable with  `env.step([...])`.

This might be done with `extra_players`, `number_of_left_players_agent_controls`, `number_of_right_players_agent_controls`, isn't ?

The documentation shows how to use multiagents like `--players=gamepad:left_players=1;lazy:left_players=2;bot:right_players=1;bot:right_players=1;bot:right_players=1`, but as far as I can see, these are all builtin option?

**Comment by qstanczyk** [comment]
You have 2 options:
- Specify both number_of_left_players_agent_controls and number_of_right_players_agent_controls. That way step() API method will provide you with multiple observations, one per each player. That way you can use different model for each player
- Implement your player type (see [here](https://github.com/google-research/football/tree/master/gfootball/env/players) for examples) and use --players flag.
