### ISSUE TITLE
Observations

### ISSUE THREAD

**Issue by chiravdave** [google-research/football#236]
Is it possible to get **raw positions of all the players, team having the ball possession and game mode** while **representation is set to rgb image or extracter** ? 

`env = football_env.create_environment(env_name="11_vs_11_stochastic", representation="extracted", stacked=True, 
		logdir="/logs/train_logs")`
`obs, rew, done, info = env.step(action)`

Here, **obs** is a stack of numpy arrays. **info** only shows score. Having flexibility to read both will help a lot. Please guide if there is a way to get both.

**Comment by qstanczyk** [comment]
To do that you can use "raw" observation format and use observation converters directly to generate RGB from raw.
Please reopen if you have further questions.
