### ISSUE TITLE
How to do "pressure action" as an agent?

### ISSUE THREAD

**Issue by seungeunrho** [google-research/football#240]
According to the key mapping for human player, there exists three types of "pressure" actions in defense mode 
-> pressure, team pressure, and goalkeeper pressure.

S - short pass in the attack mode, pressure in the defense mode.
D - shot in the the attack mode, team pressure in the defense mode.
W - long pass in the the attack mode, goalkeeper pressure in the defense mode.

If I want to make agents to do "pressure",  which action must be taken?

Maybe, corresponding agents actions such as bellow still works for the agents too?
action_short_pass = 11  ( for S)
action_shot = 12,   (for D )
action_long_pass = 9,   (for W)

**Comment by qstanczyk** [comment]
Pressure actions are available in [full action set](https://github.com/google-research/football/blob/7a5ae3b5c849beb69d15a7c0028f16d7297b1d9f/gfootball/env/football_action_set.py#L140) (by default v1 action set is used). You can change action set used by specifying it in [the config](https://github.com/google-research/football/blob/7a5ae3b5c849beb69d15a7c0028f16d7297b1d9f/gfootball/play_game.py#L47)
