### ISSUE TITLE
modify players

### ISSUE THREAD

**Issue by roberth11** [google-research/football#244]
Some way to improve the graphics of the game, some manual or tutorial.

**Comment by qstanczyk** [comment]
Robert, what are you asking for specifically?

**Comment by roberth11** [comment]
> Robert, what are you asking for specifically?

Thanks for answering, I would like to be able to improve the design of the players, I don't know if anyone has any idea of ​​how it can be done, since I improved the designs but when compiling this it throws me errors.

**Comment by qstanczyk** [comment]
Well, the source code of the game engine is the documentation. There is no manual for the code I am afraid. If you have some specific problem I might be able to help.
