### ISSUE TITLE
System not using gpus

### ISSUE THREAD

**Issue by lcassano** [google-research/football#246]
Hi I successfully run the installation using docker as recommended.
I can run "python3 -m gfootball.examples.run_ppo2" fine, the issue is that the system does not appear to be using the gpus on the system. I have 4 Nvidia Teslas and when I run "nvidia-smi -l 1" to be able to see gpu usage I get 0% (Output below).
Any ideas as to what might be causing this and how to fix it?

Thanks in advance for any help.

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:18:00.0 Off |                    0 |
| N/A   40C    P0    43W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   34C    P0    42W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:86:00.0 Off |                    0 |
| N/A   34C    P0    43W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:AF:00.0 Off |                    0 |
| N/A   39C    P0    41W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by qstanczyk** [comment]
HI, did you build Docker image with "GPU-training support"? Do you run "nvidia-smi" within the Docker container? To verify Docker setup you could try [this instruction](https://www.tensorflow.org/guide/gpu).

**Comment by brthor** [comment]
I also encountered this bug.

The issue is that tensorflow is installed on top of tensorflow-gpu in the `Dockerfile` and tensorflow ends up taking precedence. I will submit a PR with the changes I made to fix this.

**Comment by brthor** [comment]
I also encountered this bug.

The issue is that tensorflow is installed on top of tensorflow-gpu in the Dockerfile and tensorflow ends up taking precedence.

**Comment by brthor** [comment]
https://github.com/google-research/football/blob/master/Dockerfile#L13

Making a simple change to remove the tensorflow installation in the `Dockerfile` and using `--build-arg DOCKER_BASE=tensorflow/tensorflow:1.15.2-py3` instead of `--build-arg DOCKER_BASE=ubuntu:18.04` for the cpu version solves the problem and retains functionality when using the cpu.

**Comment by qstanczyk** [comment]
good catch, made a change to the Docker image to not override installed TF.

**Comment by qstanczyk** [comment]
Please reopen if there are further issues to address

**Comment by lcassano** [comment]
Thanks for the help @brthor @qstanczyk, I'll try this as soon as I can and report back.
