### ISSUE TITLE
AssertionError: Environment does not support multiple rendering instances in the same process

### ISSUE THREAD

**Issue by jgonik** [google-research/football#248]
Hi!

I'm trying to experiment with training on the football environment using [Dreamer](https://github.com/danijar/dreamer). However, I keeping getting an error with the following stack trace:

```
  Traceback (most recent call last):
  File "dreamer.py", line 467, in <module>
    main(parser.parse_args())
  File "dreamer.py", line 425, in main
    for _ in range(config.envs)]
  File "dreamer.py", line 425, in <listcomp>
    for _ in range(config.envs)]
  File "/home/julia/dreamer/wrappers.py", line 371, in __init__
    self._env = ctor()
  File "dreamer.py", line 424, in <lambda>
    config, writer, 'test', datadir, store=False), config.parallel)
  File "dreamer.py", line 389, in make_env
    env = football_env.create_environment(representation='pixels', env_name="academy_empty_goal_close", stacked=False, logdir="/tmp/football", write_goal_dumps=True, write_full_episode_dumps=False, render=True, number_of_left_players_agent_controls=1, number_of_right_players_agent_controls=0)
  File "/home/julia/.local/lib/python3.6/site-packages/gfootball/env/__init__.py", line 220, in create_environment
    env.render()
  File "/home/julia/.local/lib/python3.6/site-packages/gfootball/env/football_env.py", line 219, in render
    return self._env.render(mode=mode)
  File "/home/julia/.local/lib/python3.6/site-packages/gfootball/env/football_env_core.py", line 427, in render
    self._rendering_in_use()
  File "/home/julia/.local/lib/python3.6/site-packages/gfootball/env/football_env_core.py", line 125, in _rendering_in_use
    assert not _active_rendering, ('Environment does not support multiple '
AssertionError: Environment does not support multiple rendering instances in the same process.
```

Can someone please give me more context about the assertion error? That is, why could it be happening? I'm assuming that it's because `env.render()` is being called multiple times when it should only be called once with the football environment, but I can't seem to track down where that's happening in the code. Thanks so much!

**Comment by qstanczyk** [comment]
That is because you are using 'pixels' representation, which requires rendering (hence each instance of the environment tries to do full rendering). Is this what you really want to do? Rendering from 'pixels' observation is very expensive, as your algorithm needs to process and learn on all pixels of the screen.

**Comment by jgonik** [comment]
Yes, we would like to test how feasible it is to learn from pixels. Is that possible with this implementation? Alternatively, would it be better to use greyscale pixels instead of the full RGB pixel observations?

**Comment by qstanczyk** [comment]
In that case you need to start environments in independent processes or use a single environment instance. Training from 2D rendering might not make much sense, as it is basically generated from the raw observations agent gets and is quite similar to the minimap representation (just bigger in dimensions and with all objects encoded in one layer). It would be easier to just train from a minimap after increasing it's default size.

**Comment by jgonik** [comment]
Okay, thanks! I'll try that out.
