### ISSUE TITLE
Install gfootball in editable mode

### ISSUE THREAD

**Issue by mc1893** [google-research/football#249]
Hey!
I'm trying to install gfootball in editable mode.
I tried `pip3 install -e .`, `sudo pip3 install -e .`, `sudo python3 -m pip install --user -e  . `., `python3 setup.py develop`
None of them work (b.t.w. normal installation with `pip3 install .` works fine)

I get the following error:
`cp: cannot create directory 'build/lib.linux-x86_64-3.6/gfootball_engine': No such file or directory
    error: Google Research Football: Could not copy fonts to build/lib.linux-x86_64-3.6/gfootball_engine.`

Any idea how to fix this? Is it an issue of the repo or my system?
Thanks!

**Comment by qstanczyk** [comment]
PR #277 is not merged, Windows support added to the environment. Thanks @vi3itor for your great contribution. Closing this issue.
