### ISSUE TITLE
KeyError: 'ppo2_model/pi/c1/w:0'

### ISSUE THREAD

**Issue by yunanyan** [google-research/football#252]
When I tried to play with pre-trained checkpoints with the following command:

python3 -m gfootball.play_game --players "keyboard:left_players=1;ppo2_cnn:right_players=1,checkpoint=$mypath"

it raises this error: KeyError: 'ppo2_model/pi/c1/w:0'

**Comment by qstanczyk** [comment]
Where that checkpoint file is coming from? Was it generated with provided training example?

**Comment by wangjksjtu** [comment]
HI @qstanczyk, I met the same issue. I found that the loaded params of trained agent are something like this:
```
dict_keys(['ppo2_model/pi/layer_0/kernel:0', 'ppo2_model/pi/layer_0/bias:0', 'ppo2_model/pi/layer_1/kernel:0', 'ppo2_model/pi/layer_1/bias:0', 'ppo2_model/pi/layer_2/kernel:0', 'ppo2_model/pi/layer_2/bias:0', 'ppo2_model/pi/layer_3/kernel:0', 'ppo2_model/pi/layer_3/bias:0', 'ppo2_model/pi/layer_4/kernel:0', 'ppo2_model/pi/layer_4/bias:0', 'ppo2_model/pi/layer_5/kernel:0', 'ppo2_model/pi/layer_5/bias:0', 'ppo2_model/pi/layer_6/kernel:0', 'ppo2_model/pi/layer_6/bias:0', 'ppo2_model/pi/layer_7/kernel:0', ...
``` 
However, the keys of loaded_params for provided `11-vs-11-stochastic-easy` are like this:
```
dict_keys(['ppo2_model/pi/convnet/conv_2d/w:0', 'ppo2_model/pi/convnet/conv_2d/b:0', 'ppo2_model/pi/convnet/residual_0_0/conv_2d/w:0', 'ppo2_model/pi/convnet/residual_0_0/conv_2d/b:0', 'ppo2_model/pi/convnet/residual_0_0/conv_2d_1/w:0', 'ppo2_model/pi/convnet/residual_0_0/conv_2d_1/b:0', 'ppo2_model/pi/convnet/residual_0_1/conv_2d/w:0', 'ppo2_model/pi/convnet/residual_0_1/conv_2d/b:0', 'ppo2_model/pi/convnet/residual_0_1/conv_2d_1/w:0', 'ppo2_model/pi/convnet/residual_0_1/conv_2d_1/b:0', 'ppo2_model/pi/convnet/conv_2d_1/w:0', 'ppo2_model/pi/convnet/conv_2d_1/b:0', 'ppo2_model/pi/convnet/residual_1_0/conv_2d/w:0', ...
```

I followed the README.md and used the `gfootball/examples/repro_checkpoint_easy.sh` to train the agent. Moreover, I found that the size of my checkpoint is larger than the provided ones (13.4M vs 4.6M). The length of loaded_params' keys is not the same as well (110 vs 140) For your reference, I also attached the trained agent here:[https://drive.google.com/file/d/1M1xC7AEgZ3sW97K9XkMPC7x9K8On0Mj9/view?usp=sharing](https://drive.google.com/file/d/1M1xC7AEgZ3sW97K9XkMPC7x9K8On0Mj9/view?usp=sharing). 

Any thoughts about this? Thanks a lot in advance!

**Comment by qstanczyk** [comment]
I think this is due to TF version incompatibility. I have updated the [Readme](https://github.com/google-research/football/blob/master/README.md#trained-checkpoints) with a note on how to run it the easiest. Does it work for you?
