### ISSUE TITLE
Neccessary modification for scenario "Run, Pass and Shoot with Keeper"?

### ISSUE THREAD

**Issue by ReinholdM** [google-research/football#255]
Hi, all!
    I wanna switch to the 2 vs 2 scenario   "academy_run_pass_and_shoot_with_keeper", but that makes me so confused about the settings. I changed the arguments env as "academy_run_pass_and_shoot_with_keeper" and wish to control two players from left team, but the observation represent three players which are two players and a keepers. The default argument "active " of `env.observation` changes like "[0, 2], [1, 2]" rather than fixed like "[1, 2]" without keeper. What else should I change for adapting this multi-agent scenario? Thanks!

**Comment by qstanczyk** [comment]
You can either control 3 players and use [build_in](https://github.com/google-research/football/blob/master/gfootball/doc/observation.md#v2-action-set) action for goalkeeper or change scenario by setting [controllable](https://github.com/google-research/football/blob/0856c8b730fffb12451a9470541755a715d73ece/gfootball/env/scenario_builder.py#L99) bit to the goalkeeper.

**Comment by ReinholdM** [comment]
I changed the setting in the `__init__ .py` of this scenario and delete the parameter of the goalkeeper and set the `number_of_left_players_agent_controls=2`. Then I can control the fixed two players.

**Comment by qstanczyk** [comment]
Does removing of the goalkeeper work at all? Game engine requires goalkeeper to be on the field. I think be doing that the game swapped one of your players for a goalkeeper.

**Comment by ReinholdM** [comment]
Sorry for my mistake, we deleted one of the original two players and maintained the goalkeeper and one player.

**Comment by ReinholdM** [comment]
I still have a question about using the build-in action. How can I endow the goalkeeper with the build-in action to create the environment?

**Comment by qstanczyk** [comment]
You create the environment the normal way, just make sure to use a full/v2
action set (example
<https://github.com/google-research/football/blob/0856c8b730fffb12451a9470541755a715d73ece/gfootball/play_game.py#L47>).
Then for the goalkeeper keep generating build-in action
<https://github.com/google-research/football/blob/master/gfootball/doc/observation.md#v2-action-set>

**Comment by qstanczyk** [comment]
If you use create_environment then you can use other_config_options
<https://github.com/google-research/football/blob/0856c8b730fffb12451a9470541755a715d73ece/gfootball/env/__init__.py#L105>
to
set up action set.

**Comment by ReinholdM** [comment]
When I create the environment with `env = football_env.create_environment(env_name=args.football_env, number_of_left_players_agent_controls=3, representation="raw", stacked=False, logdir='/tmp/football', write_goal_dumps=False, write_full_episode_dumps=False, render=False, other_config_options={'action_set': 'full'})`. And I wanna know whether the order of actions for stepping into the env is fixed like keeper, the first player and the other player over states.

**Comment by qstanczyk** [comment]
If you control all the players on the team then order is fixed (still, you
need to check the initial order by processing observations returned by the
env.reset()). If not all players are controlled then the order can change
when a controlled player switch happens.

**Comment by ReinholdM** [comment]
I got it! Great thanks for your clear demonstration.
