### ISSUE TITLE
Is it possible to extract the actions of each AI player?

### ISSUE THREAD

**Issue by HaziqRazali** [google-research/football#259]
I ran the command `python3 -m gfootball.play_game --players=""` to let the AI play against itself. Is it possible to extract the actions such as long shot or pass performed by each player? The observations do not provide this.

**Comment by nhoma** [comment]
Hi, I'm also really curious about this? @HaziqRazali did you find a solution? Or @qstanczyk are there pointer where to look in the code?
I'm would like to record the actions of each player for an imitation learning project. 
Thank you.

**Comment by qstanczyk** [comment]
For imitation learning I would suggest using provided trained checkpoints
(see here
<https://github.com/google-research/football/blob/master/README.md#trained-checkpoints>
for example). Built-in AI doesn't use public action set (there are more
actions internally), so it might be problematic even if you extract those
actions.

**Comment by qstanczyk** [comment]
Actually, even better way to go would be to use data from the Kaggle
competition: https://www.kaggle.com/c/google-football/leaderboard
You can download replays from the games of any team and process them
accordingly.

**Comment by qstanczyk** [comment]
You might find this <https://www.kaggle.com/felipebihaiek/1211scrape>
interesting
- Dataset from the Kaggle competition. Here is the episode scrapper
<https://www.kaggle.com/robga/google-football-episode-scraper> notebook.

**Comment by nhoma** [comment]
I see. Thanks for the pointers.

**Comment by qstanczyk** [comment]
You might also find this
<https://www.kaggle.com/dott1718/grf-replays-collection> dataset useful.
