### ISSUE TITLE
[question] tactical simulation and model development

### ISSUE THREAD

**Issue by panizzopoli** [google-research/football#261]
`question`
In modern football(soccer) there is a lot of attention in tactics, in developing new tactical model approach in different match situation and  #define a playing identity of the team.
Is this project feasible to replicate or create real football tactical simulation or situation or is it more a toy/playground for testing and developing general purpose deep learning algorithm ? Or anyone try to apply "algorithm" or tactical model based on real-world tactics (like for example tiki-taka or gegen pressing) ? 
Sorry for the dumb question i just stumbled upon this project looking for a football open source serious(not videogame) simulation.

**Comment by qstanczyk** [comment]
This project is to push RL research, providing realistic football simulator is out of the scope.
