### ISSUE TITLE
Outer player order isn't consistent with gamecore inner player order in 5_vs_5?

### ISSUE THREAD

**Issue by yjp999** [google-research/football#264]
Hi, We found a little strange thing in google research football as follows,

We controlled 4 agents except for the goalkeeper in a 5_vs_5 scenario, we found the field `left_agent_controlled_player` the environment returned in observation's value is [2, 3, 1, 4], which means the action_list we passed into env.step(action_list) has a weird controller mapping, in details:

-  action[0] controls player 2 in gamecore
-  action[1] controls player 3 in gamecore
-  action[2] controls player 1 in gamecore
-  action[3] controls player 4 in gamecore

That's confused, why not a one-to-one match? But the observation player order is consistent with gamecore player order, this would cause:

- player1_obs -> trainning_network -> action[0] -> control player 2
- player2_obs -> trainning_network -> action[1] -> control player 3
- player3_obs -> trainning_network -> action[2] -> control player 1
- player4_obs -> trainning_network -> action[3] -> control player 4

In other words, if we want the actions that network outputed corresponding to each correct player, we need to reorder the action list according to the field `left_agent_controller_player`. If not, this would lead a lower efficiency to trainning and weird.

Finally, I found this reason in the following snipet in https://github.com/google-research/football/blob/v1.0/third_party/gfootball_engine/src/onthepitch/AIsupport/AIfunctions.cpp#L794:
![image](https://user-images.githubusercontent.com/10045627/109627901-10ec9280-7b7d-11eb-9e0a-6f7fbb26eabc.png)
When we controlled all agents except for goalkeeper, the controller mapping was fixed at begining. And the controller maping order is depending on internal player initial position closer to ball position. Besides, when we controlled 10 agents, the controller mapping is [6, 5, 7, 8, 10, 9, 2, 3, 1, 4], which means player 6 is closest to ball at begining.

How could fix the bug in gamecore? Maybe modify the initial position is a choice, but I'm not find the initial position snipet.

**Comment by qstanczyk** [comment]
You can modify scenario file ([example](https://github.com/google-research/football/blob/master/gfootball/scenarios/5_vs_5.py)) to get an identity mapping. Note this only works when controlling all of the controllable players, otherwise mapping can change over time.

**Comment by yjp999** [comment]
> You can modify scenario file ([example](https://github.com/google-research/football/blob/master/gfootball/scenarios/5_vs_5.py)) to get an identity mapping. Note this only works when controlling all of the controllable players, otherwise mapping can change over time.

Thanks for your reply!

I have tried to modify each player's starting position in the scenario file (5_vs_5.py) to get an identity mapping. No matter what  the starting position values are, the control mapping returned is always [2, 3, 1, 4], not the expected identity mapping [1, 2, 3, 4].

I have investigated this problem for a long time, Finally I found the controll mapping would be fixed at starting if controlling all of the controllable players, and the mapping is up to formation position in the football engine. The real starting position is fixed in the engine as follows, the magic is [here](https://github.com/google-research/football/blob/master/third_party/gfootball_engine/src/data/teamdata.cpp#L78) : 
![image](https://user-images.githubusercontent.com/10045627/110754337-ade8b300-8282-11eb-9f48-e123ade665dd.png)

The above snipets explained perfectly why the controll mapping is [2, 3, 1, 4] when controls all controllable players in 5_vs_5, and [6, 5, 7, 8, 10, 9, 2, 3, 1, 4] when controls 10 players in 11_vs_11.

One solution is that gfootball.env exposes `left_agent_controlled_player` and `right_agent_controlled_player` fields at gfootball/env/constans.py, and let users to reorder the actions passed to env.step() according to controll mapping when controll all controllable players, but this solution is unfriend for new researchers.  Maybe there are other solutions solving this problem, which is transparent to researchers if they controll all players when studying multi-agents reinforcement learning.

Looking forward to your reply, thanks a lot.

**Comment by qstanczyk** [comment]
Thanks for investigating this. You can make the order stable by adding the
code below just before this line
<https://github.com/google-research/football/blob/2bb4bd9f11686ca85926a3623a8f584eb3f70ff7/third_party/gfootball_engine/src/onthepitch/team.cpp#L172>
:

  // Sort players by the ID to provide identity mapping of controller-player
  // when controlling all players on the team.
  std::sort(result.begin(), result.end(), [](Player* a, Player* b) {
        return a->GetStableID() < b->GetStableID();
    });

Please note that [1, 2, 3, 4] order is not an identity either, as
observations / actions are indexed from 0 (while 0 player is the goal
keeper in the observations).

**Comment by yjp999** [comment]
Thank you very much, the solution you proposed is a very nice choice. That's great !
At before, we didn't notice the mismatch controller mapping when we research multi-agent learning using 5_vs_5 and controll all players except the goalkeeper. Indeed, the network learned the non-identity controlled mapping in final, but it's very unefficiency. After we adjust the actions order, the 5v5 learning efficiency achieve ~3x speedup. 

I want to know if your scheme would be updated and synchronized to the master branch，because we want to avoid other potential problems in the future,  so we need to keep our football engine the same as official git repository.

**Comment by qstanczyk** [comment]
Yes, I will push this change with the next release.
