### ISSUE TITLE
Possible bug in play_game.py

### ISSUE THREAD

**Issue by corkillj** [google-research/football#271]
Hi, I'm a student currently working with this google research football repository. (We have implemented some stuff to get multiple cameras (with their intrinsic and extrinsic matrix ) with pixel positions for the ball). We rely on running the same game deterministically multiple times to get the different camera angles. 
I think I might have found a bug that causes the game to not run deterministically when using play_game.py even when using one of the deterministic scenarios. 
When configuring the game in play_game.py :
```
cfg = config.Config({
      'action_set': FLAGS.action_set,
      'dump_full_episodes': True,
      'players': players,
      'real_time': FLAGS.real_time,
  })
  
if FLAGS.level:
    cfg['level'] = FLAGS.level
```
It first calls some sort of config constructor (sorry for my bad terminology) that, due to a lack of a defined level, uses the default '11_vs_11_stochastic' which isn't deterministic and therefor sets a random 'game_engine_random_seed'. When then in the second part the level is configured as eg. '11_vs_11_deterministic', it already has a random seed even though it is supposed to be deterministic. 
Give the same initial conditions the game sometimes runs the same way for some time even when give a different random seed, I'm guessing this is why this went unnoticed. 
I've fixed by simply moving the configuration of 'level' into the first part. 

Disclaimer: Maybe I've also misunderstood something and there was some other problem, I'm not the most seasoned programmer.

**Comment by qstanczyk** [comment]
Thanks for reporting this issue. I made a [fix](https://github.com/google-research/football/pull/272)
