### ISSUE TITLE
How do I change the formation of build-in AI's during the game?

### ISSUE THREAD

**Issue by stigeano** [google-research/football#282]
I have been able to let 2 AI's play against each other. Now I would like to have them change formation somewhere during the game (for example at half time).

**Comment by qstanczyk** [comment]
For that you would have to change the game engine's internals. Changing formation dynamically is not supported.

**Comment by stigeano** [comment]
Is there something else which can be changed dynamically? For example team playing styles (high/low pressure, defense line, attacking/defensive way of playing).

**Comment by qstanczyk** [comment]
No, scenarios apply for the entire episode.

**Comment by vi3itor** [comment]
@stigeano If you look closely at the built-in AI implementation (e.g., [AIfunctions.cpp](https://github.com/google-research/football/blob/master/third_party/gfootball_engine/src/onthepitch/AIsupport/AIfunctions.cpp)), you can notice that there are a lot of cases being considered and many constants introduced. It's a big undertaking to move them, as well as players' default positions into a config, and to add the ability for the engine to reload those values when the game is paused. 
Another thought is not to change built-in AI but to have different multi-agent AIs with various play styles and formations or the ability to change it dynamically.
