### ISSUE TITLE
Installing error:  target pattern contains no '%'.  Stop.

### ISSUE THREAD

**Issue by clouds-song** [google-research/football#283]
my system is  Ubuntu 16.04
while in the last step: build the environment, It appeared:
![image](https://user-images.githubusercontent.com/55445708/126999454-89a42880-459d-4c9e-84e7-f14b139bedcd.png)

**Comment by vi3itor** [comment]
It's hard to tell what's going on here. Quick search suggests that either [some of the libs are missing in your Ubuntu installation](https://stackoverflow.com/a/61503103/16014819) or even there is some problem with `cmake`. Your screenshot (btw, please, don't upload screenshots, use code snippets to post error messages) suggests that you're using `anaconda`, that might be another vector of errors. You can try installing a newer version of Ubuntu (18.04 or higher) and use `apt-get`'s installation of `python3` as in the example.

Every working environment is unique and often makes it very difficult to track down the source of the error. To avoid such problems, we recommend using Docker instead.
