### ISSUE TITLE
how to turn off non-active agents' default actions

### ISSUE THREAD

**Issue by Chen001117** [google-research/football#284]
In the paper, you said 

> Moreover, by default, our non-active players are also controlled by another rule-based bot. In this case, the behavior is simple and corresponds to reasonable football actions
and strategies, such as running towards the ball when we are
not in possession, or move forward together with our active
player. In particular, this type of behavior can be turned off
for future research on cooperative multi-agents if desired.

However, during the training process, I found that the agent will automatically run toward the ball (even if I give the instruction to go in the opposite direction). Are there any ways to turn off this feature? Belows are my training code:

> env = football_env.create_environment(
            env_name=all_args.scenario_name, stacked=False,
            logdir=all_args.log_dir,
            representation=all_args.representation,
            rewards=all_args.rewards,
            write_goal_dumps=False,
            write_full_episode_dumps=True and need_render,
            render=all_args.render and need_render,
            dump_frequency=1 if all_args.render and need_render else 0,
            number_of_left_players_agent_controls=all_args.num_agents,
            number_of_right_players_agent_controls=0,)

Thanks!

**Comment by vi3itor** [comment]
The paper explains that default behaviour of **non-active** players can be turned-off. To do just that, when adding players for a particular scenario, define `lazy=True` and the player will stand still. See the implementation [here](https://github.com/google-research/football/blob/5162bf5831c9ef978b2745a4b34930c8ea44a927/gfootball/env/scenario_builder.py#L99).

**Comment by Chen001117** [comment]
got it! Thanks
