### ISSUE TITLE
replay.py does not replay the same game when the environment is stochastic?

### ISSUE THREAD

**Issue by MitsukiUsui** [google-research/football#290]
First, I simulated a match between trained PPO checkpoint and build-in AI and got a dump file and a video:

```
  env = football_env.create_environment(
    env_name='11_vs_11_stochastic',
    number_of_left_players_agent_controls=0,
    number_of_right_players_agent_controls=0,
    extra_players=['ppo2_cnn:left_players=1,policy=gfootball_impala_cnn,checkpoint=/tmp/11_vs_11_easy_stochastic_v2'],
    logdir='/tmp',
    write_full_episode_dumps=True,
    write_video=True,
    render=True
  )

  while True:
    _, _, done, _ = env.step([])
    if done:
      break
```

then, I replayed the match with replay.py and got another pair of dump and video:

```
python3 replay.py --trace_file=/tmp/episode_done_20210826-153153684043.dump
```

I expected these two movies to be exactly the same, however, they were different. More specifically, actions for the left were exactly the same, but actions for the right were different and thus all other conditions (e.g. controlled player for the left-team, ball location, etc) were also different.

I'm wondering whether it's possible to also control the right-team player's action from the dump file so that we can replay the exact same match?

**Comment by qstanczyk** [comment]
Theoretically it should - dump file contains seed used by random number generator. If the replay was generated on a different machine the mismatch might be caused by different OS libs versions.

**Comment by zyp57783** [comment]
I found this problem. I have three computers, the replay AVI comes from the same dump file generated by one of the three, are different on three computers which have different OS version(Ubuntu 16,18,etc)
