### ISSUE TITLE
How to avoid out of bound?

### ISSUE THREAD

**Issue by ReinholdM** [google-research/football#292]
Hi! I have observed that there usually a player in my team can get out of bound. And how can I make the player be limited within the playground? Thanks

**Comment by qstanczyk** [comment]
I guess this happens for the player controlled by your policy, right? Maybe adding a wrapper on top of the policy to not involve "move right" when the player is already at the right bound of the field etc...?

**Comment by ReinholdM** [comment]
Oh, I got it. Thanks for your great reply!
