### ISSUE TITLE
how to get build-in ai's actions

### ISSUE THREAD

**Issue by Chen001117** [google-research/football#293]
Is there any way to get the build-in ai's actions?(For example, if I play full game and only control one agent, can I get the actions of other rule-base bot?) I want to get the action of the built-in ai and learn from it.

**Comment by Chen001117** [comment]
I found that the action_set used by build-in ai is diferrent from the normal one. To solve this problem, I set environment parameter as 'action_set':'full' then train and evaluate on this environment.

**Comment by qstanczyk** [comment]
Build-in AI uses internal action set, there is no way to expose it.
