### ISSUE TITLE
No matching distribution found for baselines>=0.1.6

### ISSUE THREAD

**Issue by ChintanTrivedi** [google-research/football#3]
Could not find a version that satisfies the requirement baselines>=0.1.6 (from gfootball[tf_gpu]) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5)

Can only install 0.1.5 even with the suggestion in [issue #1](https://github.com/google-research/football/issues/1). Using 18.04.2 LTS platform.

**Comment by nczempin** [comment]
probably a duplicate of #2

**Comment by nczempin** [comment]
wait; why is 'baselines >= 0.1.6' even still there if you applied the suggestion from #1? the suggestion is to replace the line **in setup.py, (this should probably mentioned explicitly somewhere)** with the other line

**Comment by ChintanTrivedi** [comment]
I think I was seeing message similar to gfootball requires baselines>0.1.6 but I had 0.1.5. I tried installing baselines-0.1.6 from baselines repo master branch using pip, expecting this repo's setup.py to just say requirement already satisfied.

**Comment by cyfra** [comment]
@ChintanTrivedi please install baselines from source, rather than from the pypi package (see #1 for longer explanation why).

pip3 uninstall baselines
pip3 install "git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6"

**Comment by ChintanTrivedi** [comment]
Thank you, I got it working with this.
