### ISSUE TITLE
Failed building wheel for gfootball 

### ISSUE THREAD

**Issue by siddharthkale97** [google-research/football#30]
I am getting this error while installing 

running build_ext
  'gfootball' is not recognized as an internal or external command,
  operable program or batch file.
  Google Research Football compilation failed
 ----------------------------------------
  Failed building wheel for gfootball
  Running setup.py clean for gfootball
  Running setup.py bdist_wheel for baselines ... done
  Stored in directory: C:\Users\User\AppData\Local\Temp\pip-ephem-wheel-cache-2bdp8pkh\wheels\47\4b\a3\0a25aebc24e2f3302802b56aef9855b3bc7bb051cc5bc3debd
  Running setup.py bdist_wheel for wrapt ... done
  Stored in directory: C:\Users\User\AppData\Local\pip\Cache\wheels\d7\de\2e\efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd
Successfully built baselines wrapt
Failed to build gfootball
tensorflow 1.12.0 has requirement tensorboard<1.13.0,>=1.12.0, but you'll have tensorboard 1.14.0 which is incompatible.

**Comment by Panels32** [comment]
I have the exact same issue.

**Comment by zajaczajac** [comment]
Is it coming from building the docker?
Do you try to build GPU version? If so, please try to also build CPU one and let me know if that works.

**Comment by siddharthkale97** [comment]
> Is it coming from building the docker?
> Do you try to build GPU version? If so, please try to also build CPU one and let me know if that works.

No, I am trying to install it on anaconda on a windows machine. And I am having the same problem with the CPU version.

**Comment by zajaczajac** [comment]
Unfortunately for direct installation we support only Linux. For other platforms, you can try using Docker.

**Comment by Hallam-Liu** [comment]
I have the same issue on Linux

**Comment by Fmijsters** [comment]
Did you manage to install on a windows machine?

**Comment by vi3itor** [comment]
Hi @fighting-zz, can you post your error log and the OS information?

**Comment by fighting-zz** [comment]
> Hi @fighting-zz, can you post your error log and the OS information?

hello! @vi3itor , i am very glad to receive your reply. 
the OS imformation : windows 10
the error log is here :  
[log.txt](https://github.com/google-research/football/files/9125168/log.txt)
Can i compile the engine without using Docker?
