### ISSUE TITLE
Models not being saved

### ISSUE THREAD

**Issue by Ujwal2910** [google-research/football#31]
I have been trying to run an A3C chainer script on the environment and although the learning is taking place and is evident in the rendering but the model is not being saved.
When I replace the environment with Cartpole it works fine and the model gets saved.
Could you please update?

**Comment by Ujwal2910** [comment]
I ran the a3c script from chainerRL - https://github.com/chainer/chainerrl
The problem is that when any other different environment is chosen the checkpointing of models works perfectly fine.
In my log, I keep getting the message that the model is being saved but actually nothing is being saved or written.
We have been using this code- https://github.com/Ujwal2910/RL-in-Football
If you could help us figure why only with this environment such an issue is happening it would help us a lot in the research.

**Comment by AntonRaichuk** [comment]
Could you share how the log looks like when you run Cartpole vs GFootball?
Also please share "ls -l" output of the outdir for both cases.

**Comment by Ujwal2910** [comment]
for the Cartpole models the log returns-
![Screenshot from 2019-07-01 16-19-05](https://user-images.githubusercontent.com/19718533/60431147-adc69200-9c1c-11e9-85b1-d0430141842f.png)
and for the Football  env it returns-
![Screenshot from 2019-07-01 16-20-42](https://user-images.githubusercontent.com/19718533/60431185-cafb6080-9c1c-11e9-8064-d617462504c2.png)

For the result of ls -I the result is as follows-
```
(base) ujwal@ujwal-Precision-7920-Tower:~/PycharmProjects/Gfootball/football_models$ ls -l
total 4
(base) ujwal@ujwal-Precision-7920-Tower:~/PycharmProjects/Gfootball/football_models$ 
```
and for cartpole it gives-
```
(base) ujwal@ujwal-Precision-7920-Tower:~/PycharmProjects/Gfootball/cartpole_models$ ls -l
total 620
drwxr-xr-x 2 ujwal ujwal   4096 Jul  1 16:18 200_finish
drwxr-xr-x 2 ujwal ujwal   4096 Jul  1 16:18 4024_except
drwxr-xr-x 2 ujwal ujwal   4096 Jul  1 16:18 best
-rw-r--r-- 1 ujwal ujwal 310639 Jul  1 16:18 model.npz
-rw-r--r-- 1 ujwal ujwal 306909 Jul  1 16:18 optimizer.npz
-rw-r--r-- 1 ujwal ujwal    182 Jul  1 16:18 scores.txt
(base) ujwal@ujwal-Precision-7920-Tower:~/PycharmProjects/Gfootball/cartpole_models$ 
```

**Comment by AntonRaichuk** [comment]
Thanks for pointing out this issue. After debugging it is indeed a problem in our environment that it changes the current working directory. We are working on a fix.

For now I'd just recommend using absolute paths for your logging. It should work that way.

**Comment by qstanczyk** [comment]
We just pushed a new release, the fix is included.
