### ISSUE TITLE
zsh: segmentation fault  python

### ISSUE THREAD

**Issue by yanxue7** [google-research/football#312]
Hi, i install the football env in macos and python 3.8.8.
I have not encountered error when I run
brew install git python3 cmake sdl2 sdl2_image sdl2_ttf sdl2_gfx boost boost-python3
and 
pip install gfootball.

However, it shows "segmentation fault" when import gfootball

[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gfootball
zsh: segmentation fault  python

**Comment by vi3itor** [comment]
Hi @yanxue7, I've just created a PR (#313) that allows running `gfootball` in Conda environment on macOS. You can try it even before it get merged into `master`. 

Also, please check out the [documentation of compiling `gfootball` on macOS](https://github.com/vi3itor/football/blob/conda-macos/gfootball/doc/compile_engine.md#choosing-python-distribution).
