### ISSUE TITLE
If I want to apply my own multi-agent reinforcement learning algorithm on this platform,what should I do?

### ISSUE THREAD

**Issue by Gezx** [google-research/football#32]

**Comment by AntonRaichuk** [comment]
We are in process of releasing an update to this environment which will enable multi-agent feature.
There is a chance it will happen this week.

**Comment by Gezx** [comment]
Thank you very much.I hope  to apply it on my graduation project which is about  multi-agent reinforcement learning.

**Comment by GoingMyWay** [comment]
> We are in process of releasing an update to this environment which will enable multi-agent feature.
> There is a chance it will happen this week.

Dear @AntonRaichuk 

For multi-agent RL. Is it possible for each agent to get its local observation? Now I found it is global state, not local observable observation.

**Comment by AntonRaichuk** [comment]
Right now we only provide global state.
If you want to have a local observation (whatever this means to you) you can implement an environment wrapper that will restrict observations to what you'd like it to be.
