### ISSUE TITLE
Is it possible to use Long/high Pass to switch sides ?

### ISSUE THREAD

**Issue by houssemeddinebayoudha** [google-research/football#321]
Hello, I've been experimenting with the env a lot lately, and I'm confused on how to perform a Long/High pass to switch sides.
From the docs and experimenting with the game I know it's possible to perform Long/High passes (action_long_pass and action_high_pass) but the power of the pass/ to who you are passing is determined based on the direction of the player and all that. But what I'm looking for is switching sides like we see in irl games.

**Comment by vi3itor** [comment]
Hi @houssemeddinebayoudha, what do you mean by "to switch sides"?
If you are asking about the way to select the target player, as you can see in the [docs](https://github.com/google-research/football/blob/master/gfootball/doc/observation.md#default-action-set):

> action_long_pass = 9, perform a long pass to the player on your team. Player to pass the ball to is auto-determined based on the movement direction.

So if you want to manually select the target player of the pass, you have to make changes to the engine.
