### ISSUE TITLE
Float representation giving different dimensional vector for each scenario. 

### ISSUE THREAD

**Issue by vishalbidawatka** [google-research/football#33]
If you choose a particular scenario like "empty goal close", the env.observation space shows 115 as the dimension size of the float representation but the the returned state is 39-dimensional vector and the number is different for another scenario. Why is that ?

**Comment by AntonRaichuk** [comment]
That representation is indeed supposed to work only for 11 vs 11. Some of the features that it has are coordinates of 11 players on your team as well as on the opponents.
When you go to a different scenario (in terms on number of players) obviously the dimensionality wont be the same.

We can make a simple change to backfill missing slots with say -1 values.  So at least it does not crash. Expect this change in the next release (hopefully this week)

**Comment by qstanczyk** [comment]
We just pushed a new release, the fix is included.
