### ISSUE TITLE
How to control the viewpoint?

### ISSUE THREAD

**Issue by ranahanocka** [google-research/football#35]
Hi, 

I am interested in modifying the cameras viewpoint. Instead of the camera always looking at the player, to have it show the entire field (and not move..).
Any easy way to do that ? If not, any tips on which files I might need to modify?

**Comment by cyfra** [comment]
That's an interesting idea @ranahanocka 

I'd suggest to start by looking at the GraphicsCamera file:

https://github.com/google-research/football/blob/0f09bcb8b3d48ac31987e13739e21a58ef0ca405/third_party/gfootball_engine/src/systems/graphics/objects/graphics_camera.cpp#L105

Keep us updated on how it goes.

**Comment by qstanczyk** [comment]
Marking this issues as closed, please reopen if some more clarification / followup is needed.

**Comment by alexander3605** [comment]
Hi, I have noticed that there has been some updates about the camera code in the latest commit (https://github.com/google-research/football/commit/2238c1551edfd560d0cbec0ddd30faa07b54bbb4). 
Has this enhancement been considered? How can we modify the position of the camera?

**Comment by qstanczyk** [comment]
There was only a code cleanup to make environment code easier to follow, faster to compile.

**Comment by bhack** [comment]
Can we expose camera intrisic/extrinsic control in the simulation?

**Comment by qstanczyk** [comment]
We can consider this feature given it being generic enough (so that it can be found useful by many users). What is your specific use case? How would you like it to be controlled?

**Comment by soldierofhell** [comment]
Hi @qstanczyk, in general to approach traing based on pure image frames it's necessary to have gt in camera coordinates. It's probably relatively easy to obtain projection of single (x,y), but that's not enough. It would be great to have sematic segmentation like in MS AirSim. Do you think it's possible without going to deep in the code (like OpenGL)?

**Comment by jason718** [comment]
@qstanczyk can you give some advice how to compute camera intrinsic/extrinsic?

**Comment by qstanczyk** [comment]
You might want to start from looking
at gfootball_engine/src/systems/graphics/objects/graphics_camera.cpp
Not sure what would you like to obtain exactly. You could train from pure
frames in the form they are provided by default. It might be hard, but
doable.
Can you collaborate on what exactly you want to achieve?

**Comment by qstanczyk** [comment]
Got a laptop, will need HDMI connector. Thanks
