### ISSUE TITLE
QUESTION: Switching player action and auto-swtich

### ISSUE THREAD

**Issue by qiyuangong** [google-research/football#36]
According to the paper, switching action is disabled during training, because it may return control to default bot. So, active player is auto-switched in defense mode, and manually switched according to passing in attack mode. I try to switch players in defense mode of play_game, but it seems not working as I expected. 

**How does it (auto-switch) work? Can we turn off this auto-switch by modifying config or code?**

**Comment by qstanczyk** [comment]
Configuration of this feature is not controlled by the config at the moment. You can change the code, however. Please have a look at Team::UpdateSwitch inside of team.cpp:
https://github.com/google-research/football/blob/8c2230022248112e396c3feb720125d2a028123f/third_party/gfootball_engine/src/onthepitch/team.cpp#L548

**Comment by qiyuangong** [comment]
Thank you @qstanczyk . I will check that code. :)

Issue closed.

**Comment by WOWNICE** [comment]
The active player is controlled by the internal football engine and cannot be controlled by the upper python code. Then how can we train a specific strategy for a certain player since the active player keeps changing all the time?

**Comment by qstanczyk** [comment]
The default episode configuration is equivalent to playing football computer game by a human - you control the player with the ball (when attacking) or a single player selected by the computer on defense.  In case of multiple-agent setup it is possible to control all 11 players.

**Comment by WOWNICE** [comment]
Okay I get it. Thanks for your explanation.

**Comment by AntonRaichuk** [comment]
@WOWNICE we are currently running self-play experiments and making sure everything behaves nicely. in the coming weeks we should release this capability to the public

**Comment by WOWNICE** [comment]
@AntonRaichuk Thanks! Really looking forward to the coming release!
