### ISSUE TITLE
ModuleNotFoundError: No module named 'gfootball_engine'and No module named 'apt-pkg'

### ISSUE THREAD

**Issue by zhangyiru** [google-research/football#38]
I have installed the required apt packages like libgl1-mesa-dev and so on.
when I run the code "python3 -m gfootball.examples.run_ppo2 --level=academy_empty_goal_close", it has this mistake.
`Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zyr/football-master/gfootball/examples/run_ppo2.py", line 27, in <module>
    import gfootball.env as football_env
  File "/home/zyr/football-master/gfootball/env/__init__.py", line 23, in <module>
    from gfootball.env import config
  File "/home/zyr/football-master/gfootball/env/config.py", line 28, in <module>
    import gfootball_engine as libgame
ModuleNotFoundError: No module named 'gfootball_engine'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zyr/football-master/gfootball/examples/run_ppo2.py", line 27, in <module>
    import gfootball.env as football_env
  File "/home/zyr/football-master/gfootball/env/__init__.py", line 23, in <module>
    from gfootball.env import config
  File "/home/zyr/football-master/gfootball/env/config.py", line 28, in <module>
    import gfootball_engine as libgame
ModuleNotFoundError: No module named 'gfootball_engine'
'
so do you know where the bug is? thanks~

**Comment by zajaczajac** [comment]
Which command did you use to install gfootball package? Was it successful?
It looks like game engine was not compiled and copied to the right place.

**Comment by zhangyiru** [comment]
thanks for your reply!
firstly, I run this code to install packages and it was successful.

then I run the code "python3 -m gfootball.examples.run_ppo2 --level=academy_empty_goal_close" and it has the error...
do the engine need to complie?
------------------ 原始邮件 ------------------
发件人: "zajaczajac"<notifications@github.com>;
发送时间: 2019年7月8日(星期一) 下午4:31
收件人: "google-research/football"<football@noreply.github.com>;
抄送: "877061968"<877061968@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [google-research/football] ModuleNotFoundError: No module named'gfootball_engine'and No module named 'apt-pkg' (#38)




Which command did you use to install gfootball package? Was it successful?
 It looks like game engine was not compiled and copied to the right place.

**Comment by zhangyiru** [comment]
after the installation, what steps I need to do? where do the game engine need to copy? thanks~

**Comment by zajaczajac** [comment]
First, you need to install Ubuntu packages (as you did).
Then you install our Python package with either `pip3 install gfootball[tf_cpu] --process-dependency-links` or `pip3 install .[tf_cpu] --process-dependency-links` from inside the repo (to use with CPU tensorflow) - which one did you use?

Game engine is compiled and copied automatically by the script that is called when you do these installation steps.

Also, which Ubuntu do you use?

**Comment by zhangyiru** [comment]
I have a query and what do the "[tf_cpu]" mean? is it version of tensorflow?

my ubuntu is here.
zyr@hy02:~$ cat /proc/version
Linux version 4.15.0-29-generic (buildd@lcy01-amd64-024) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018

thanks

**Comment by zajaczajac** [comment]
It means additional dependency which is set in setup.py file. If you already have tensorflow, you can drop it. 
So did you use one of those commands?

**Comment by zhangyiru** [comment]
I have already tensorflow.
I run the "pip3 install .[tf_gpu] --process-dependency-links"
but ...
zyr@hy02:~/football-master$ pip3 install .[tf_gpu] --process-dependency-links

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --process-dependency-links

**Comment by zhangyiru** [comment]
the baselines have already installed, so I think I do not run "pips install...."

**Comment by zajaczajac** [comment]
You need to run it since it builds and copies the game engine, and installs some other dependencies if there is need.
For --process-dependency-links issue, please follow the advice from https://github.com/google-research/football/issues/1 (the first post). Note that you have to have 0.1.6 version of baselines, which is newer than the version installed simply with "pip3 install baselines".

**Comment by zhangyiru** [comment]
`zyr@hy02:~/football-master$ pip3 install setup.py
Processing /home/zyr/football-master
Collecting setup.py
  ERROR: Could not find a version that satisfies the requirement setup.py (from versions: none)
ERROR: No matching distribution found for setup.py
`
the version of my baselines is 0.1.6 , do you know where error is? thanks~

**Comment by zhangyiru** [comment]
pygame is 1.9.6
opencv-python , scipy and gym have installed...

**Comment by zajaczajac** [comment]
You need the recent version of the baselines package, from github. So can you please try the following:
- install tensorflow
- `pip3 install git+git://github.com/openai/baselines.git@master#egg=baselines`
- comment out line `'baselines>=0.1.6',`, and lines
    `extras_require={
        'tf_cpu': ['tensorflow<2.0'],
        'tf_gpu': ['tensorflow-gpu<2.0'],
    },`
in setup.py,
- `pip3 install .`

**Comment by qstanczyk** [comment]
Please reopen if the problem is still not resolved.

**Comment by EnnaSachdeva** [comment]
Make sure your pip is less than 19, the lastest version of pip will disable --process-dependency-links.
Source: https://github.com/TianhongDai/google-football-pytorch

**Comment by messi10hitu** [comment]
> You need the recent version of the baselines package, from github. So can you please try the following:
> 
> * install tensorflow
> * `pip3 install git+git://github.com/openai/baselines.git@master#egg=baselines`
> * comment out line `'baselines>=0.1.6',`, and lines
>   `extras_require={ 'tf_cpu': ['tensorflow<2.0'], 'tf_gpu': ['tensorflow-gpu<2.0'], },`
>   in setup.py,
> * `pip3 install .`

i did the same thing but it is throwing some errors like
 Running setup.py install for gfootball ... error
