### ISSUE TITLE
c++: internal compiler error: Killed (program cc1plus)

### ISSUE THREAD

**Issue by barunhalderkolkata** [google-research/football#39]
> [ 82%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/humangamer.cpp.o
>     [ 83%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/ball.cpp.o
>     [ 83%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/match.cpp.o
>     c++: internal compiler error: Killed (program cc1plus)
>     Please submit a full bug report,
>     with preprocessed source if appropriate.
>     See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
>     CMakeFiles/menulib.dir/build.make:566: recipe for target 'CMakeFiles/menulib.dir/src/menu/mainmenu.cpp.o' failed
>     make[2]: *** [CMakeFiles/menulib.dir/src/menu/mainmenu.cpp.o] Error 4
>     make[2]: *** Waiting for unfinished jobs....
>     [ 84%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/referee.cpp.o
>     Scanning dependencies of target blunted2
>     [ 85%] Building CXX object CMakeFiles/blunted2.dir/src/blunted.cpp.o
>     /tmp/pip-7rh1cz4t-build/third_party/gfootball_engine/src/onthepitch/match.cpp: In member function 'void Match::RandomizeAdboards(boost::intrusive_ptr<blunted::Node>)':
>     /tmp/pip-7rh1cz4t-build/third_party/gfootball_engine/src/onthepitch/match.cpp:512:103: warning: format '%i' expects argument of type 'int', but argument 2 has type 'std::vector<boost::intrusive_ptr<blunted::Resource<blunted::Surface> > >::size_type {aka long unsigned int}' [-Wformat=]
>        if (Verbose()) printf("%i adboards loaded (out of %i files)\n", adboardSurfaces.size(), files.size());
>                                                                        ~~~~~~~~~~~~~~~~~~~~~~              ^
>     /tmp/pip-7rh1cz4t-build/third_party/gfootball_engine/src/onthepitch/match.cpp:512:103: warning: format '%i' expects argument of type 'int', but argument 3 has type 'std::vector<std::__cxx11::basic_string<char> >::size_type {aka long unsigned int}' [-Wformat=]
>     /tmp/pip-7rh1cz4t-build/third_party/gfootball_engine/src/onthepitch/match.cpp:520:79: warning: format '%i' expects argument of type 'int', but argument 2 has type 'std::__cxx11::list<boost::intrusive_ptr<blunted::Geometry> >::size_type {aka long unsigned int}' [-Wformat=]
>        if (Verbose()) printf("number of stadium objects: %i\n", stadiumGeoms.size());
>                                                                 ~~~~~~~~~~~~~~~~~~~^
>     [ 86%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/AIsupport/mentalimage.cpp.o
>     [ 86%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/AIsupport/AIfunctions.cpp.o
>     [ 87%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/proceduralpitch.cpp.o
>     [ 87%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/team.cpp.o
>     CMakeFiles/Makefile2:377: recipe for target 'CMakeFiles/menulib.dir/all' failed
>     make[1]: *** [CMakeFiles/menulib.dir/all] Error 2
>     make[1]: *** Waiting for unfinished jobs....
>     [ 88%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/teamAIcontroller.cpp.o
>     [ 88%] Linking CXX static library libblunted2.a
>     [ 88%] Built target blunted2
>     [ 88%] Linking CXX static library libgamelib.a
>     [ 88%] Built target gamelib
>     Makefile:83: recipe for target 'all' failed
>     make: *** [all] Error 2
>     gfootball/build_game_engine.sh: line 19: pushd: third_party/gfootball_engine: No such file or directory
>     Google Research Football compilation failed
> 
>     ----------------------------------------
> Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-7rh1cz4t-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-r6242ms6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-7rh1cz4t-build/
> The command '/bin/sh -c cd /gfootball && pip3 install .[tf_$DEVICE] --process-dependency-links' returned a non-zero code: 1

**Comment by zajaczajac** [comment]
Please provide details on what operating system you use and what command you run (is it direct installation, or in Docker?)

**Comment by qstanczyk** [comment]
Please reopen with platform details.

**Comment by DavidBert** [comment]
Hi, I'm having the exact same error on Ubuntu 18.04, running the pip3 command.
Is there anyway to fix it?
