### ISSUE TITLE
[Mac OS] Failed building wheel for gfootball 

### ISSUE THREAD

**Issue by tranhoangkhuongvn** [google-research/football#4]
OS: MACOS 10.14
I got process-dependency-links flag at first, then downgraded pip to 18.1 as one of the suggestion, I then got the error failed building wheel for gfootball due to this (probably):
`gfootball 0.2 has requirement baseslines>=0.1.6, but you'll have baselines 0.1.5 which is incompatible` although I have just installed openai baseline from github. 

[install.log](https://github.com/google-research/football/files/3270578/install.log)

**Comment by cyfra** [comment]
If you're sure that you've installed the baselines from git - then go ahead and change the setup.py from football to remove the >=0.1.6 requirement and try again.

**Comment by tranhoangkhuongvn** [comment]
Hi, I remove that baseline req and this error comes up
`Running setup.py bdist_wheel for gfootball: finished with status 'error'`
I attached here the installation log 
[install.log](https://github.com/google-research/football/files/3271731/install.log)

**Comment by cyfra** [comment]
Seems that the error is:
    CMake Error at CMakeModules/FindPackageHandleStandardArgs.cmake:110 (MESSAGE):
      Could NOT find SDL2_image (missing: SDL2_IMAGE_LIBRARIES
      SDL2_IMAGE_INCLUDE_DIRS)

Can you check that you've installed all the apt-get packages ? (for example libsdl2-image-dev)

Try running this:
sudo apt-get install git cmake build-essential libgl1-mesa-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libboost-all-dev libdirectfb-dev libst-dev mesa-utils xvfb x11vnc libsqlite3-dev glee-dev libsdl-sge-dev python3-pip


If it still doesn't work: please let me know what version of linux you're running.

**Comment by szho42** [comment]
got the same issue. On the official openai baselines, the master branch is 0.1.5. Which branch is for 0.1.6?

**Comment by TianhongDai** [comment]
@cyfra I think he uses the macos system. @tranhoangkhuongvn I think you can sovle this problem by using `brew install sdl2_image sdl2_ttf sdl2_gfx`, but I was stuck when I was trying to solve `boost-python` dependencies. Maybe better to use Docker for this environment?

**Comment by tranhoangkhuongvn** [comment]
> @cyfra I think he uses the macos system. @tranhoangkhuongvn I think you can sovle this problem by using `brew install sdl2_image sdl2_ttf sdl2_gfx`, but I was stuck when I was trying to solve `boost-python` dependencies. Maybe better to use Docker for this environment?

Thanks for your suggestion @TianhongDai ! Mine is the same, after resolving the SDL2 libraries then hitting the Python boost not found error. I will look into the Docker solution then.

**Comment by TianhongDai** [comment]
@tranhoangkhuongvn You're welcome! That's cool! So you install it successfully on macos? Could I know what is the version of your `boost-python3`? It seems my `boost-python3` is the latest version and it has removed the `boost_threads` and `boost_signals`.

**Comment by cyfra** [comment]
@TianhongDai  - thanks, I've missed the comment that this is on Mac.

**Comment by TianhongDai** [comment]
@cyfra you're welcome

**Comment by TianhongDai** [comment]
> @tranhoangkhuongvn You're welcome! That's cool! So you install it successfully on macos? ~Could I know what is the version of your `boost`? It seems my `boost` is the latest version and it has removed the `boost_threads` and `boost_signals`.~

I solved it by installing `boost` from source code. But still struggle with some boost problems. Will have a look in the future. Now, I can use it with docker and train it with Ubuntu system.

**Comment by kkurach** [comment]
@tranhoangkhuongvn Can this issue be closed or there's still sth ?

**Comment by tranhoangkhuongvn** [comment]
Hi, the problem is still there, I just change to install using Docker. I don't know if there is any effort to support for Mac install?

**Comment by kkurach** [comment]
We chatted in the team, and adding a native mac install would be probably too much work, so for now the supported default is Docker. That being said, we're happy to take a pull request that would make it work on Mac directly.

**Comment by yoanisgil** [comment]
@kkurach can you please take a look at https://github.com/google-research/football/pull/106 ?

I was able to successfully compile and install the project on my Macbook Pro, however I'm facing a runtime issue which I'm not entirely sure how to fix. 

Also, even if we make this work, do you guys want to *officially* support ` OSX`? If the answer is NO then there is no point in investigating the issue I'm facing.

BTW,  I will totally understand if you guys do not want to support `OSX` because of the level of commitment that i requires or just because there is no real value in it.
