### ISSUE TITLE
Question: GameFPS/FPS/physics_frametime/graphics_frametime ?

### ISSUE THREAD

**Issue by WOWNICE** [google-research/football#41]
There are two different FPS shown in the logging info. If I understand it correctly according to the code in https://github.com/google-research/football/blob/master/gfootball/env/football_env_wrapper.py#L84, 

FPS = episode-step-count / total-episode-time
GameFPS = episode-step-count / time-past-in-game-engine

They are called F(rames)PS but they actually represent the step per second. 

But there is also another variable in the engine code called 'physics_frametime' and 'graphics3d_frametime', as shown in https://github.com/google-research/football/blob/master/third_party/gfootball_engine/data/football.config#L24 

Now I have 3 questions:
1. What's the relationship between the FPS/GameFPS between the 'frametime' parameters? 
2. And how is the game interacting with the agent: does it run for certain frames and pause waiting for the action or does it run and just listening to the action as some sort of interruption? 
3. How does these parameters influence the performance of the game and the agent? 

Thank you for your patience reading this long issue. Any comment is welcomed!

**Comment by qstanczyk** [comment]
FPS / GameFPS report the speed of training / game engine respectively and it doesn't affect training in any way. If FPS is way lower than GameFPS it means performance is lost somewhere in Python / training part. Otherwise speed limiting factor is the game engine.

physics_frametime tells how many physics animations game engine does per "second of the game" and it should be 1ms. I think we should eliminate this parameter, as it should not be changed. graphics3d_frametime is not used anymore (will clean it up).

**Comment by WOWNICE** [comment]
Thanks @qstanczyk for your quick reply! 

Since FPS/GameFPS doesn't affect training, does it mean that the game engine freezes when waiting for the agent's action during training? If so, then after how many physics frames will it freeze and wait?

Thank you.

**Comment by qstanczyk** [comment]
Yes, training is synchronous. Game does 10 physics steps for a single environment step (physic step == 10ms, environment step == 100ms).

**Comment by WOWNICE** [comment]
You saved my day! Thank you @qstanczyk ! Issue closed.

**Comment by WOWNICE** [comment]
Sorry to bother you again @qstanczyk, but when I turn off the 'real_time' option in the 'play_game' mode, the environment didn't freeze and wait for the user input per 100ms. 

Is there something wrong with my understanding of 'synchronous'? Where is the interface/code controlling whether it's synchronous/asynchronous? 

Thanks again.

**Comment by qstanczyk** [comment]
Environment is always synchronous with the agent / player modules. Player modules / agents shouldn't ever wait, just perform inference and respond with the step to take as fast as possible. 'real_time' option is there to make game playable for humans. It adds additional sleep between steps to make sure humans can keep up. When you disable it game / agents / bots will just run full speed, but entire environment is always synchronous.

**Comment by WOWNICE** [comment]
Okay, but what if the player/agent can't respond fast enough, for example, the agent is so slow that it takes the whole day to inference, would the environment wait until it finishes the inference or just take 'idle' as the input action and step until the max duration is reached?  (thanks for the explanation of the 'real_time')

**Comment by qstanczyk** [comment]
Then env. will wait for a day to make a step.

**Comment by WOWNICE** [comment]
Okay, so the environment interacts synchronously with the agent but asynchronously with the human (since the game can take idle as input when human doesn't input anything)? 

Thanks for your patience!

**Comment by qstanczyk** [comment]
Exactly. Asynchronous part is not the environment itself, but the human
player implementation only.
