### ISSUE TITLE
Bug: Bots do not perform "shot" action

### ISSUE THREAD

**Issue by alexander3605** [google-research/football#43]
Hi

I am running the game only among bots with the following command
`MESA_GL_VERSION_OVERRIDE=3.2 MESA_GLSL_VERSION_OVERRIDE=150 python3 -m gfootball.play_game --home_players=bot --away_players=bot `

What I have noticed is that, when a bot has the ball and is within the shooting range defined in bot.py, the _shot_ action gets returned by the function `_get_action` but the player does not actually shoot and most of the time it just keeps running towards the goal.

Is this a known issue? How can I fix this?

**Comment by alexander3605** [comment]
Here you go (I had to add the .txt extension as GitHub does not allow for .dump files to be sent) 
[shutdown_20190718-145905363324.dump.txt](https://github.com/google-research/football/files/3406604/shutdown_20190718-145905363324.dump.txt)

I ran the game with a `bot` in the home team and a `lazy` in the away team, just so that the bot will try to shoot more frequently.
In this example you can see that the player sometime runs towards the goal (or even diagonally outside of the pitch) without shooting. There is also a case where the player actually shoots and from what I can see is when it receives the ball in the _shot range_ (i.e. it does not have it before entering it).

**Comment by qstanczyk** [comment]
Thanks for your report Alessandro. The reason why bot doesn't shot sometimes is that it doesn't deactivate pressure action when shooting. Pressure action prevents shooting. You can quickly try this out by changing this line:
https://github.com/google-research/football/blob/master/gfootball/env/players/bot.py#L178
We have a fix to the bot, will release it with the next release.

**Comment by alexander3605** [comment]
Thanks for your answer!
What should I change that line to?

**Comment by qstanczyk** [comment]
On option is for example to replace:
> if self._observation['ball_owned_team'] == (1 if is_active_left else 0):
>      if self._last_action == football_action_set.action_pressure:
>        return football_action_set.action_sprint
>      return football_action_set.action_pressure
with:
> if self._observation['ball_owned_team'] == (1 if is_active_left else 0):
>   return football_action_set.action_pressure
> if self._last_action == football_action_set.action_pressure:
>   return football_action_set.action_release_pressure
That will release pressure when owning the ball before trying to shot.

**Comment by qstanczyk** [comment]
I have just pushed a new version with the workaround to the problem, so alternatively you can just sync to head.

**Comment by alexander3605** [comment]
Thank you so much, it works perfectly now!
