### ISSUE TITLE
error: XDG_RUNTIME_DIR not set in the environment. Couldn't load GL function glBegin: Video subsystem has not been initialized

### ISSUE THREAD

**Issue by zhangyiru** [google-research/football#44]
`root@b7e2aa424caa:/gfootball# python3 -m gfootball.play_game
/usr/local/lib/python3.6/dist-packages/google/protobuf/__init__.py:37: UserWarning: Module gfootball_engine was already imported from /usr/local/lib/python3.6/dist-packages/gfootball_engine/__init__.py, but /gfootball is being added to sys.path
  __import__('pkg_resources').declare_namespace(__name__)
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
error: XDG_RUNTIME_DIR not set in the environment.
Couldn't load GL function glBegin: Video subsystem has not been initialized`

after entering images, it is ok to run python3 -m football.examples.run_ppo2,but I have error when I run python3 -m gfootball.play_game.do you know the reason? thx~

**Comment by zajaczajac** [comment]
Unfortunately we do not support rendering inside the Docker.
However if you want for example run play_game to generate some dumps without rendering, you can do it by editing config inside play_game script (change `'render'` to `False`).

**Comment by zhangyiru** [comment]
I change 'render' to False to rerun `python3 -m gfootball.examples.run_ppo2` and run `python3 -m gfootball.play_game` but it has same error...

**Comment by zajaczajac** [comment]
Right.
The thing that is failing is pygame import, which is inside keyboard/gamepad controllers. Note that keyboard controller is default for home player. But if there's no rendering, there is no point of playing with keyboard/gamepad.
`python3 -m gfootball.play_game --home_players=bot` should work.

**Comment by zhangyiru** [comment]
`root@d5e2ac45c463:/gfootball# python3 -m gfootball.play_game --home_players=bot
/usr/local/lib/python3.6/dist-packages/google/protobuf/__init__.py:37: UserWarning: Module gfootball_engine was already imported from /usr/local/lib/python3.6/dist-packages/gfootball_engine/__init__.py, but /gfootball is being added to sys.path
  __import__('pkg_resources').declare_namespace(__name__)
error: XDG_RUNTIME_DIR not set in the environment.
Couldn't load GL function glBegin: Video subsystem has not been initialized
`
i try it, but it also error...

**Comment by zajaczajac** [comment]
What docker base did you use? (What command did you use to build the image?)

**Comment by zhangyiru** [comment]
sorry,it is too late to reply you.
I used the `docker build --build-arg DOCKER_BASE=ubuntu:18.04 --build-arg DEVICE=cpu . -t gfootball` in the begining.
but my ubuntu is 16.04, so I use `docker build --build-arg DOCKER_BASE=ubuntu:16.04 --build-arg DEVICE=cpu . -t gfootball`.
now it has the new error..
`BrokenPipeError: [Errno 32] Broken pipe`
thanks

**Comment by zajaczajac** [comment]
Can you try with ubuntu:18.04? This version doesn't have to match Ubuntu version on your desktop.

**Comment by cuiguangwu** [comment]
> Unfortunately we do not support rendering inside the Docker.
> However if you want for example run play_game to generate some dumps without rendering, you can do it by editing config inside play_game script (change `'render'` to `False`).

If I want display the result, what should I do.

**Comment by AntonRaichuk** [comment]
What have helped me in a situation with this error is:

sudo apt install nvidia-utils-390
sudo apt install nvidia-driver-390
sudo reboot
