### ISSUE TITLE
Bug: ball_owned_player and ball_owned_team

### ISSUE THREAD

**Issue by alexander3605** [google-research/football#45]
I have found some bugs on the two _ball possession_ pieces of information that the system keeps track while using the system.

_**The two values are not always synced with each other. Ideally, when `ball_owned_team` is -1, so should be `ball_owned_player`. Vice-versa, when `ball_owned_player` is not -1 (i.e. a player has the ball) so should be `ball_owned_team`.**_

1. During goal kicks both values are set to -1 while the keeper is standing still. When he starts moving `ball_owned_player` gets set to 0, while `ball_owned_team` is stuck at -1. IMO the two values should point to the team and the keeper who is doing the goal kick during all the "game steps" while the `game_mode` is set to 2 (goal kick)

2. Right after the goal kick is performed, `ball_owned_team` is set to the keeper's team but `ball_owned_player` is set to -1

**I suspect a similar situation occurs also on free kicks but I have not encountered any in my usage of the system**

3. When the keeper intercepts the ball, `ball_owned_team` gets set to the keeper's team value but `ball_owned_player` gets set to -1

**Comment by qstanczyk** [comment]
Thanks for your report Alessandro. Currently these two observations have slightly different semantic. To make API cleaner we will make them consistent as you suggest. Change will be includes in the set of next changes (hopefully within a week).

**Comment by qstanczyk** [comment]
We have pushed a new release containing change for this.
