### ISSUE TITLE
Error when Playing game yourself: ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred,etc

### ISSUE THREAD

**Issue by ZechenLiu** [google-research/football#47]
Dear Sir/Madam,
After I input `MESA_GL_VERSION_OVERRIDE=3.2 MESA_GLSL_VERSION_OVERRIDE=150 python3 -m gfootball.play_game`, Google Research Football will run normally in  a period. However, the interface is grey from the beginning, not as colorful as what your paper reveals. Besides, the program will be forced to exit after a while, but it is not completed yet.

root@lzc-virtual-machine:/home/lzc/football# MESA_GL_VERSION_OVERRIDE=3.2 MESA_GLSL_VERSION_OVERRIDE=150 python3 -m gfootball.play_game
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
已杀死

What happened to my program? My platform is a ubuntu linux virtual machine. What changes need I  make？ Could you please help me solve it? Many thanks to your kind attention.

**Comment by cyfra** [comment]
Can you post a picture with how your environment looks like when it is running?
How long does it run before the crash?

The logs that you've printed are related to sound (which should be disabled) - and they should not impact the rendering.

Can you verify that other OpenGL programs (like glxgears) are working fine on your machine?

**Comment by rryswny** [comment]
I'm experiencing the same problem.

$ time python3 -m gfootball.play_game
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
I0731 06:22:37.208980 139666784499520 observation_processor.py:362] Dump "score": count limit reached / disabled
I0731 06:22:47.202156 139666784499520 observation_processor.py:362] Dump "lost_score": count limit reached / disabled
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
Killed

real	3m4.062s
user	3m59.924s
sys	1m38.788s


It runs for around 3 minutes before gameplay slows and it crashes soon after.

Memory used by the process increases as it runs until all swap space is used and just a small amount of memory is free. I have only 4gb of ram. Could this be the cause of the problem?

glxgears seems to work.

**Comment by ZechenLiu** [comment]
I sincerely appreciate your warm help.Cause I’m a little busy these days, i’ll try it later.Thank you so much again.I’ll memorize your advice.




| |
刘泽辰
|
|
邮箱：15611877789@163.com
|

签名由 网易邮箱大师 定制

On 07/31/2019 13:56, Rory Sweeney wrote:

I'm experiencing the same problem.

$ time python3 -m gfootball.play_game
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
I0731 06:22:37.208980 139666784499520 observation_processor.py:362] Dump "score": count limit reached / disabled
I0731 06:22:47.202156 139666784499520 observation_processor.py:362] Dump "lost_score": count limit reached / disabled
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
Killed

real 3m4.062s
user 3m59.924s
sys 1m38.788s

It runs for around 3 minutes before gameplay slows and it crashes soon after.

Memory used by the process increases as it runs until all swap space is used and just a small amount of memory is free. I have only 4gb of ram. Could this be the cause of the problem?

glxgears seems to work.

**Comment by qstanczyk** [comment]
The problem here is that environment records raw pixels for each step, so that it can later generate an AVI file for trace dumps. As video snapshot is disabled by default I will make a change to not hold entire video frame by default. That should help you.

**Comment by qstanczyk** [comment]
Memory reduction change was pushed with 1.2 release.

**Comment by ZechenLiu** [comment]
I've already solved it.Thanks！


| |
刘泽辰
|
|
邮箱：15611877789@163.com
|

签名由 网易邮箱大师 定制

On 08/06/2019 16:08, qstanczyk wrote:

Closed #47.

**Comment by chrybrk** [comment]
> @ZechenLiu How did you solve this?

yeah, i'm havin' this issue too, and i really am curios how to fix it, it doesn't crash or anything, it is just annoying.
