### ISSUE TITLE
Error during installation: process is killed

### ISSUE THREAD

**Issue by jorgeg96** [google-research/football#52]
Hi! I'm trying to install football for a project. I'm using VMWare with Ubuntu 18.04 (4gb RAM, 2 cores processor and 30GB of disk space). When I run pip3 install .[tf_gpu] the process gets stuck in "running setup.py install for gfootball" and after a minute it gets killed and the OS restarts. Can someone tell me why is this happening? Or if football is compatible with VMWare virtual machine. Thanks for your help.

**Comment by qiyuangong** [comment]
I think you may encounter `out of memory` in your VM. Just like #49 . Pls increase memory or reduce building thread number according to https://github.com/google-research/football/issues/49#issuecomment-517379712 .

**Comment by jorgeg96** [comment]
Thanks for the response. Can you please tell me where should I put the -j parameter? After i put pip install I can not input anything.

**Comment by Bravlin** [comment]
Hey, I saw your comment in the other issue. I don't know if you managed to fix it but here is my answer.

One of the things the command pip install does in this case is building the gfootball environment. For doing that, it has to call the script build_game_engine.sh, which found in the folder gfootball from the root of the project.

On the line number 18 of that same file, you will find make -j between &&. (&& make -j &&). That line is executing various commands, but we're interested in make in particular. That -j is telling make to build gfootball with parallelism, so it creates various threads to handle the task. The thing is, if a number is not specified after -j then the command will create as many threads as it pleases, quickly consuming the available memory. So, to fix the issue, just add a reasonable number after -j.

**Comment by jorgeg96** [comment]
Thanks for the response! That solved the issue :D

**Comment by qstanczyk** [comment]
Fix was just pushed in v1.2 release.
