### ISSUE TITLE
C++ Compilation Error with --no-pie

### ISSUE THREAD

**Issue by Shengyu-Feng** [google-research/football#53]
> c++: error: unrecognized command line option ‘-no-pie’
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/player/controller/strategies/strategy.cpp.o] Error 1
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/player/controller/elizacontroller.cpp.o
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/player/controller/strategies/offtheball/default_mid.cpp.o
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/player/controller/strategies/offtheball/default_def.cpp.o
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/player/controller/strategies/special/celebration.cpp.o
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/player/controller/strategies/offtheball/default_off.cpp.o
    c++: error: unrecognized command line option ‘-no-pie’
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/player/controller/strategies/offtheball/goalie_default.cpp.o
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/player/controller/elizacontroller.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-no-pie’
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/ball.cpp.o
    c++: error: unrecognized command line option ‘-no-pie’
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/player/controller/strategies/offtheball/default_mid.cpp.o] Error 1
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/player/controller/strategies/offtheball/default_def.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-no-pie’
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/AIsupport/AIfunctions.cpp.o
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/player/controller/strategies/special/celebration.cpp.o] Error 1
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/humangamer.cpp.o
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/match.cpp.o
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/AIsupport/mentalimage.cpp.o
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/referee.cpp.o
    c++: error: unrecognized command line option ‘-no-pie’
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/team.cpp.o
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/player/controller/strategies/offtheball/default_off.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-no-pie’
    Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/proceduralpitch.cpp.o
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/player/controller/strategies/offtheball/goalie_default.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-no-pie’
    c++: error: unrecognized command line option ‘-no-pie’
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/ball.cpp.o] Error 1
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/AIsupport/AIfunctions.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-no-pie’
    c++: error: unrecognized command line option ‘-no-pie’
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/humangamer.cpp.o] Error 1
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/AIsupport/mentalimage.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-no-pie’
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/match.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-no-pie’
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/proceduralpitch.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-no-pie’
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/referee.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-no-pie’
    make[2]: *** [CMakeFiles/gamelib.dir/src/onthepitch/team.cpp.o] Error 1
    make[1]: *** [CMakeFiles/gamelib.dir/all] Error 2
    make: *** [all] Error 2
    gfootball/build_game_engine.sh: line 19: pushd: third_party/gfootball_engine: No such file or directory
    build/lib.linux-x86_64-3.6/gfootball_engine
    Google Research Football compilation failed
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-uga3s02v/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-uga3s02v/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hj7022xr/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

The above is the snapshot of the error output, I'm running on Ubuntu14.04

**Comment by cyfra** [comment]
This compilation option is set here:
https://github.com/google-research/football/blob/2238c1551edfd560d0cbec0ddd30faa07b54bbb4/third_party/gfootball_engine/CMakeLists.txt#L22

You can try removing it - and see if the environment still works (afaik we didn't test this configuration).

**Comment by qstanczyk** [comment]
I think we can eliminate -no-pie flag fro the compilation, so please let us know if that helps you. If so we can remove it.

**Comment by Shengyu-Feng** [comment]
I've removed all 4 -no-pie flags, but new error message gives:

> building 'brainball_cpp_engine' extension
    gcc -pthread -shared -o build/lib.linux-x86_64-3.6/brainball_cpp_engine.cpython-36m-x86_64-linux-gnu.so
    gcc: fatal error: no input files
    compilation terminated.
    error: command 'gcc' failed with exit status 4

My gcc version is 4.8.4, here is the result of gcc -v

> Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1\~14.04.4' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release--build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1\~14.04.4)


Btw, since there's a SDL2 error before, I've added a [FindSDL2.cmake](https://github.com/brendan-w/collector/blob/master/cmake/FindSDL2.cmake) file by myself.

>  CMake Error at CMakeLists.txt:33 (FIND_PACKAGE):
      By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "SDL2", but
      CMake did not find one.

>   Could not find a package configuration file provided by "SDL2" with any of
      the following names:

>    SDL2Config.cmake
       sdl2-config.cmake

>   Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
      "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
      provides a separate development package or SDK, be sure it has been
      installed.

**Comment by cyfra** [comment]
> gcc: fatal error: no input files
This looks quite strange. Can you paste your whole log (for example into pastebin)?

>  I'm running on Ubuntu14.04
I'd suggest updating to the newer ubuntu if possible.

**Comment by Shengyu-Feng** [comment]
Here's the error message when I delete -no-pie: https://paste.ubuntu.com/p/5MgYDNvbBv/

And I also tried -fno-pie, the error message is a bit different: https://paste.ubuntu.com/p/RBZvQpy7pj/

**Comment by qstanczyk** [comment]
Removal of -no-pie flag was pushed in v1.2 release.

**Comment by qstanczyk** [comment]
There is a similar issues reported here:
https://github.com/explosion/spaCy/issues/734
I that case problem was in GCC version. I think the best way to go would be to try newer Ubuntu.

**Comment by qstanczyk** [comment]
Closing this for now, please reopen if still unsolved.
