### ISSUE TITLE
Coordinate in Raw Observation

### ISSUE THREAD

**Issue by Shengyu-Feng** [google-research/football#61]
Hi, I'm trying to recover the super minimap from the raw observation, but I find that the x coordinate is out of range [-1,1] as it can be -1.01102936 and 1.01102936. And I cannot get the exact same position after I scale the coordinate to 72x96, with 1-2 pixels error. Could you provide some more details about the coordinate transformation.

**Comment by qstanczyk** [comment]
Hi, x coordinate of the goals are respectively -1 and 1. If the ball goes out of the field it can be < -1 or > 1 (the same for player positions). Code that generates minimap is here: https://github.com/google-research/football/blob/master/gfootball/env/observation_preprocessing.py#L63

**Comment by qstanczyk** [comment]
Please reopen if more clarification is needed.
