### ISSUE TITLE
To run example PPO experiment on academy_empty_goal scenario

### ISSUE THREAD

**Issue by yumianhuli2** [google-research/football#62]
All previous steps were successed.
But:
To run example PPO experiment on academy_empty_goal scenario, run python3 -m gfootball.examples.run_ppo2 --level=academy_empty_goal_close

Q:
An error happened:
~/gfootball/football/gfootball/examples [had (master)]$ python3 -m run_ppo2.py--level=academy_empty_goal_close
Traceback (most recent call last):
  File "/home/XXX/anaconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/XXX/anaconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/XXX/gfootball/football/gfootball/examples/run_ppo2.py", line 23, in <module>
    from baselines import logger
ModuleNotFoundError: No module named 'baselines'
But I have already installed module 'baselines'.

Thank U!

**Comment by qstanczyk** [comment]
Are you sure you have the right version (for Python3 etc) installed?
Can you run:

pip3 install git+https://github.com/openai/baselines.git@master

**Comment by yumianhuli2** [comment]
> Are you sure you have the right version (for Python3 etc) installed?
> Can you run:
> 
> pip3 install git+https://github.com/openai/baselines.git@master

Yes pip3 install git+https://github.com/openai/baselines.git@master is ok!
And got :
Installing collected packages: numpy, six, cloudpickle, future, pyglet, scipy, gym, tqdm, joblib, click, opencv-python, baselines
  Running setup.py install for baselines ... done
Successfully installed baselines-0.1.6 click-7.0 cloudpickle-1.2.1 future-0.17.1 gym-0.10.9 joblib-0.13.2 numpy-1.16.4 opencv-python-4.1.0.25 pyglet-1.3.2 scipy-1.3.1 six-1.12.0 tqdm-4.32.1

But if run (base) XX@XX-XXX:~/gfootball/football/gfootball/examples [XX (master)]$ python3 -m run_ppo2 --level=academy_empty_goal_close
got : File "/home/XXX/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/XXX/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/XXX/gfootball/football/gfootball/examples/run_ppo2.py", line 23, in <module>
    from baselines import logger
ModuleNotFoundError: No module named 'baselines'

**Comment by qstanczyk** [comment]
Do you happen to have multiple Python3 versions installed? It could be the case that you install baselines for, say Python3.6 and then use Python3.7 for running PPO.

**Comment by qstanczyk** [comment]
Please reopen if this is still an issue.
