### ISSUE TITLE
[Rendering] Black-and-white rendering on ubuntu laptop

### ISSUE THREAD

**Issue by silentriverg** [google-research/football#64]
I installed football environment on an ubuntu laptop, with GTX 960 card. Installation is good but the rendering output is black-and-white when "play_game".

The environment is Ubuntu 16.04, nvidia driver 384. I check the OpenGL link by "ldconfig -p | grep GL" and see the libOpenGL.so links to /usr/lib/nvidia-384/libOpenGL.so.

By "glxinfo | grep OpenGL" the OpenGL version string: 4.5.0 NVIDIA 384.130.

On another machine which rendering is ok, the OpenGL version string is something like "3.0 mesa 18.0.5" and libOpenGL.so links to libOpenGL.so in mesa.

Could you please help me on good rendering on this laptop?

**Comment by ianchen28** [comment]
> I installed football environment on an ubuntu laptop, with GTX 960 card. Installation is good but the rendering output is black-and-white when "play_game".
> 
> The environment is Ubuntu 16.04, nvidia driver 384. I check the OpenGL link by "ldconfig -p | grep GL" and see the libOpenGL.so links to /usr/lib/nvidia-384/libOpenGL.so.
> 
> By "glxinfo | grep OpenGL" the OpenGL version string: 4.5.0 NVIDIA 384.130.
> 
> On another machine which rendering is ok, the OpenGL version string is something like "3.0 mesa 18.0.5" and libOpenGL.so links to libOpenGL.so in mesa.
> 
> Could you please help me on good rendering on this laptop?

same issue

**Comment by qstanczyk** [comment]
Can you provide a screenshot of the "black-and-white" rendering?

**Comment by JingbinLiu** [comment]
@qstanczyk like this:
![Screenshot from 2019-09-17 11-35-02](https://user-images.githubusercontent.com/38271512/65009434-3e209300-d93f-11e9-8e6c-e231d96f43d4.png)

**Comment by lucasb-eyer** [comment]
@JingbinLiu Why is the "X" button on your screenshot also gray? This looks like the whole window (including decoration) is greyed out, not just the OpenGL rendering.

For others facing this issue, can you post your system specs as the OP did? Do other 3D games or `glxgears` render properly on that system?

**Comment by JingbinLiu** [comment]
@lucasb-eyer My system specs are the same as the OP's, except my graphics card is GTX 1070. Actually the rendering is fine with early version 0.x. It is after I updated gfootball to version 1.4 that the rendering turned into black-and-white style.

In virtual env: 
$ pip uninstall gfootball  (0.x)
$ pip install gfootball  (1.4)
$ python -m gfootball.play_game

**Comment by qstanczyk** [comment]
Could you try to determine in which version it gets broken?

**Comment by qstanczyk** [comment]
Please reopen with more details (we can't reproduce this issue).

**Comment by DaDaCheng** [comment]
I have exactly same problem on my Macbook (now running ubuntu).

**Comment by EnnaSachdeva** [comment]
I am also having the same issue on Ubuntu 16.04, with GTX-1080, OpenGL ES 3.2 NVIDIA 384.130. The screenshot is attached below-

![football](https://user-images.githubusercontent.com/15670305/71336877-e4130900-24fd-11ea-8519-4388f3bddf4f.png)

Any help would be appreciated?
