### ISSUE TITLE
Could you please include a requirements file for the dependencies for this project?

### ISSUE THREAD

**Issue by shyamalschandra** [google-research/football#65]
Thanks!

**Comment by shyamalschandra** [comment]
Also, could you please provide a version for MacOS High Sierra or Mojave?  Thanks!

**Comment by shyamalschandra** [comment]
Also, a requirements file for the macOS homebrew packages, please?

**Comment by qstanczyk** [comment]
We don't have capacity currently to cover your wish list, but we are grateful for any pull requests adding these things. Thanks

**Comment by shyamalschandra** [comment]
Really?  Is this "official" word from Google Research?

**Comment by qstanczyk** [comment]
Currently our focus is on Linux platform, but as Football is an open-source project contributions to the code base are welcome.

**Comment by shyamalschandra** [comment]
Is that from a google.com email address?

**Comment by qstanczyk** [comment]
Yes.
