### ISSUE TITLE
Have you saved the example PPO trained model?

### ISSUE THREAD

**Issue by Caiderkoujiao** [google-research/football#66]
Have you saved the example PPO trained model?
Could you please tell me the method you used to test the trained model?
thanks！

**Comment by Caiderkoujiao** [comment]
And，how to replay the test of the academy scene, or how to convert it into a video like a trace dump

**Comment by qstanczyk** [comment]
We don't provide saved models right now. For creating videos have a look at the documentation:
https://github.com/google-research/football#trace-dumps
