### ISSUE TITLE
Could you provide ppo2's model file that could defeat easy computer player? 

### ISSUE THREAD

**Issue by caixiaofan** [google-research/football#67]
I don't know how to train the ppo2 to defeat the computer player in "11_vs_11_easy_stochastic". 
QAQ

**Comment by qstanczyk** [comment]
How many steps did you train PPO2 for on 11_vs_11_easy_stochastic? Did you perform hyperparameter search?

**Comment by caixiaofan** [comment]
> How many steps did you train PPO2 for on 11_vs_11_easy_stochastic? Did you perform hyperparameter search?

I used the hyperparameter from the Appendix and train PPO2 again. It can defeat the "11_vs_11_easy_stochastic" now. Thanks.

**Comment by qstanczyk** [comment]
Happy it worked for you.
