### ISSUE TITLE
save real game videos

### ISSUE THREAD

**Issue by dingchenwei** [google-research/football#68]
Hi, 
The replay.py script can only replay the real game video, I'm wondering if there is any way to save real game videos instead of the 2D field videos? Thanks.

**Comment by qstanczyk** [comment]
While using replay.py you need to change value of dump_full_episodes/dump_scores and write_video flags:
https://github.com/google-research/football/blob/master/gfootball/env/config.py#L107

That will make replay.py dump the real video.

**Comment by qstanczyk** [comment]
Also have a look here:
https://github.com/google-research/football#trace-dumps
