### ISSUE TITLE
How to install on cluster?

### ISSUE THREAD

**Issue by julienroy13** [google-research/football#69]
I have tried to install the environment on clusters but the program does not build correctly. Cluster support has asked to provide wheels on PyPI.

Also I am concerned that the rendering won't turn off properly, which would make the installation on clusters even more difficult (when I was running locally with `render=False`, the window would still pop open and render the first episode before training would go on headlessly).

Is using Docker the only way to run the environment on clusters?

**Comment by qstanczyk** [comment]
> I have tried to install the environment on clusters but the program does not build correctly. 
What doesn't build correctly? Can you provide some errors / commands you run?

> Also I am concerned that the rendering won't turn off properly
Can you provide exact repro steps? It shouldn't be the case that rendering starts for a short while when rendering is disabled.

**Comment by julienroy13** [comment]
```
It shouldn't be the case that rendering starts for a short while when rendering is disabled.
```

This was my mistake (sorry about that). I hadn't set `dump_frequency=0`. I expected that setting `render=False` would completely disable rendering, regardless of the states of `dump_frequency`, `enable_goal_videos`, `enable_full_episode_videos` and `write_video`. Just as a gentle suggestion, I think the documentation could be clearer w.r.t to these dump settings. It is not clear to me how much they overlap and which of these have priority. In any case, with everything to False and 0, rendering seem completely disabled as you said.

Back to the cluster installation issues:

```
What doesn't build correctly? Can you provide some errors / commands you run?
```

I ran `pip install .[tf_cpu]` and got the following error on one cluster:

```
Building wheels for collected packages: gfootball
  Building wheel for gfootball (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/username/virtualenvs/foot/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-nzvnptrm/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-nzvnptrm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-dnexoepm --python-tag cp37
       cwd: /tmp/pip-req-build-nzvnptrm/
  Complete output (957 lines):
  running bdist_wheel
  running build
```
[.....]
```
running build_ext
  /tmp/pip-req-build-nzvnptrm/third_party/gfootball_engine /tmp/pip-req-build-nzvnptrm
  -- The C compiler identification is GNU 7.3.0
  -- The CXX compiler identification is GNU 7.3.0
  -- Check for working C compiler: /cvmfs/soft.computecanada.ca/custom/bin/cc
  -- Check for working C compiler: /cvmfs/soft.computecanada.ca/custom/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/bin/c++
  -- Check for working CXX compiler: /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found OpenGL: /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libGL.so
  CMake Error at CMakeModules/FindPackageHandleStandardArgs.cmake:110 (MESSAGE):
    Could NOT find SDL2_image (missing: SDL2_IMAGE_LIBRARIES
    SDL2_IMAGE_INCLUDE_DIRS)
  Call Stack (most recent call first):
    CMakeModules/FindPackageHandleStandardArgs.cmake:301 (_FPHSA_FAILURE_MESSAGE)
    CMakeModules/FindSDL2_image.cmake:104 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    CMakeLists.txt:35 (FIND_PACKAGE)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-nzvnptrm/third_party/gfootball_engine/CMakeFiles/CMakeOutput.log".
  gfootball/build_game_engine.sh: line 19: pushd: third_party/gfootball_engine: No such file or directory
  Google Research Football compilation failed
  ----------------------------------------
  ERROR: Failed building wheel for gfootball
  Running setup.py clean for gfootball
Failed to build gfootball
```

**Comment by qstanczyk** [comment]
Looks like you libsdl2-image-dev is missing / corrupted. Can you verify it's installation?

**Comment by qstanczyk** [comment]
Please reopen if this is still an issue.

**Comment by AntonRaichuk** [comment]
@julienroy13: regarding rendering appearing first and then disappearing. it might be an effect of a flag 'dump_frequency', which is used in ppo example. In that setting it records a video of a gameplay for every 50th episode (starting with the first). If you do not want that, you can set the argument to 0.
