### ISSUE TITLE
issue with pip3 install .[tf_cpu]

### ISSUE THREAD

**Issue by Hallam-Liu** [google-research/football#70]
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
    Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
    (Required is at least version "3")
  Call Stack (most recent call first):
    /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
    /usr/local/share/cmake-3.15/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    CMakeLists.txt:45 (find_package)

  Google Research Football compilation failed
  ----------------------------------------
  ERROR: Failed building wheel for gfootball

**Comment by qstanczyk** [comment]
I have tried reproducing on a fresh Docker ubuntu:18.04 image, but it works fine (after installing git and python3-pip). Are you sure you don't have ENV variables messed up?
Have a look at https://stackoverflow.com/questions/24174394/cmake-is-not-able-to-find-python-libraries
Maybe that will help.
Also, can you try with Docker?
> docker run -ti -it --name quake --rm ubuntu:18.04
> apt-get update
> apt-get install git python3-pip
> cd football
> pip3 install .[tf_cpu]

**Comment by qstanczyk** [comment]
Current version of the environment doesn't depend on the TF, so .[tf_cpu] / .[tf_gpu] is gone. Please reopen if you still hit this problem.

**Comment by Hallam-Liu** [comment]
> Current version of the environment doesn't depend on the TF, so .[tf_cpu] / .[tf_gpu] is gone. Please reopen if you still hit this problem.

The Problem happenned because I change the python version on linux. It seems like cause the installation process cannot find python library.

**Comment by qstanczyk** [comment]
If you changes Python linux after installing Football then I guess you need to reinstall all deps for the new Python version.

**Comment by Hallam-Liu** [comment]
> If you changes Python linux after installing Football then I guess you need to reinstall all deps for the new Python version.

Not after installing Football but before it. Anyway, it fixed if I use the default python3 version 3.5.0 on linux. Seems like Football deps installation have some default options cause this if the python library changed in linux. And docker will not have this problem

**Comment by prihodulkin** [comment]
I have tried to run "pip3 install gfootball" and got this:
  ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1hn45ukb/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1hn45ukb/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-1hn45ukb/pygame/pip-egg-info
         cwd: /tmp/pip-install-1hn45ukb/pygame/
    Complete output (18 lines):


    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...


    Hunting dependencies...
    SDL     : found 1.2.15
    FONT    : not found
    IMAGE   : not found
    MIXER   : not found
    PNG     : found
    JPEG    : found
    SCRAP   : found
    PORTMIDI: not found
    PORTTIME: not found
    FREETYPE: found 23.1.17
    Missing dependencies
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command
What I should to do&

**Comment by vi3itor** [comment]
Looks like you're having a problem with `pygame` (which requires SDL 1.2).

**Comment by qstanczyk** [comment]
You could try using Docker image instead of installing directly on your
machine, it has proper version of libraries.
