### ISSUE TITLE
Remove minimap

### ISSUE THREAD

**Issue by alexander3605** [google-research/football#71]
Hi, I am trying to remove the minimap that's in the lower part of the screen during the game. 
Does anybody know where I should look in the game code?
Thanks

**Comment by qstanczyk** [comment]
Hi, You can disable minimap by not constructing Gui2Radar object here:
https://github.com/google-research/football/blob/master/third_party/gfootball_engine/src/onthepitch/match.cpp#L237

and not referencing it later on.
We can consider adding a flag to control this behavior, but we would like to better understand the use case first (maybe score board should be hidden as well?).
Can you tell us what is your use case?

Thanks.

**Comment by alexander3605** [comment]
Thank you, that worked! 
I am working on an action recognition system so I needed the game video without extra elements for training
