### ISSUE TITLE
How to store human player trajectories?

### ISSUE THREAD

**Issue by xuehy** [google-research/football#72]
I want to play the game myself with the script play_game. How can I store the trajectories of my play into files if I want the simple115 state vectors and the actions to be stored?

**Comment by qstanczyk** [comment]
play_game dumps full episode traces by default:
https://github.com/google-research/football/blob/master/gfootball/play_game.py#L46
and also dumps a trace on CTRL+C:
https://github.com/google-research/football/blob/master/gfootball/play_game.py#L61
Those traces contain actions and raw observations, which you can convert to simple115 representation yourself.

**Comment by xuehy** [comment]
Thanks! Just find that the dump file can be read by Pickle and then processed following the functions in the wrappers.
