### ISSUE TITLE
Convert actions between agent and human

### ISSUE THREAD

**Issue by xuehy** [google-research/football#73]
Is there any way to convert the actions logged from human playing with script play_game to the actions for training? Can I map actions from `action_set_dict['full'] `to `action_set_dict['default']`?

**Comment by qstanczyk** [comment]
default action set is just a subset of full action set, so when you have, say "action_keeper_rush" action it is the same object in both action sets. When training agents mainly operate on numerical actions (index in the action set list: https://github.com/google-research/football/blob/master/gfootball/env/football_action_set.py#L170), so when converting numerical actions between action sets you need to first convert number to the action object and then back to the index. For doing that you can use named_action_from_action_set method:
https://github.com/google-research/football/blob/master/gfootball/env/football_action_set.py#L218
There is no method currently to retrieve number for a given action object.

**Comment by qstanczyk** [comment]
Please reopen if some more help is needed.
