### ISSUE TITLE
After successful install 'pip3 install .[tf_gpu]' cant run 'python3 -m gfootball.play_game'  Fails to find _gameplayfootball.so'.  Please provide file location of library after successfull install

### ISSUE THREAD

**Issue by ragnarherron** [google-research/football#75]

**Comment by qstanczyk** [comment]
Location depends on the Python version you use. In my case it's /usr/local/lib/python3.6/dist-packages/gfootball_engine
Do you happen to have multiple python versions?

**Comment by qstanczyk** [comment]
Please reopen if you still have a problem with this.
