### ISSUE TITLE
For 19.04, how can we go without glee-dev?

### ISSUE THREAD

**Issue by shyamalschandra** [google-research/football#77]
For 19.04, how can we go without glee-dev?  There is no gfootball-engine as requested when running the experiments in the instructions for the code.  What's up?

**Comment by zajaczajac** [comment]
Have you tried this hack: https://askubuntu.com/a/1151135 ? Please let me know if this works for you.
Additionally, you can always install through the docker (as in readme).

**Comment by qstanczyk** [comment]
Actually, Glee is not really needed by the environment. We have a change which needs to be pushed which removes this dependency. In the meantime you can modify opengl_renderer3d.hpp by removing #include <GLee.h> and replacing GLfloat -> float, GLint -> int.

**Comment by shyamalschandra** [comment]
Thank you!

**Comment by qstanczyk** [comment]
Release 1.5 doesn't not depend on the Glee anymore.
