### ISSUE TITLE
Assertion Error max >= min

### ISSUE THREAD

**Issue by Shengyu-Feng** [google-research/football#78]
When I trained the PPO with the example code, it sometimes have this assertion error

> python: /tmp/pip-install-h8tlzzre/gfootball/third_party/gfootball_engine/src/base/math/bluntmath.cpp:29: blunted::real blunted::clamp(blunted::real, blunted::real, blunted::real): Assertion `max >= min' failed.

My command is 

> CUDA_VISIBLE_DEVICES=1 python -m gfootball.examples.run_ppo2 --level=11_vs_11_easy_stochastic  --dump_full_episodes=True --num_timesteps=20000000 --reward_experiment=scoring,checkpoints

This is not always the case, but it does happen from time to time, I'm not sure if it's the problem of my command or it's the internel error.

Any help is appreciated!

**Comment by qstanczyk** [comment]
We are looking into this problem. Thanks for reporting.

**Comment by Shengyu-Feng** [comment]
Is there any update on this issue?

**Comment by lucasb-eyer** [comment]
Yes, we recently identified and fixed it, we'll have an update very soon.

**Comment by qstanczyk** [comment]
Release 1.5 doesn't not depend on the Glee anymore.

**Comment by kkurach** [comment]
I think the comment from @qstanczyk  is unrelated to this issue. 
However,  v1.5 also contains the fix for this issue (numerical issue is fixed and the assert doesn't trigger anymore after long run), so no need to re-open.
