### ISSUE TITLE
ModuleNotFoundError: No module named 'gfootball_engine' from Docker Images

### ISSUE THREAD

**Issue by imanzano** [google-research/football#8]
I installed manually baselines from openia git repo using 

> pip3 install "git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6"

ThenI try to run the example and it fails

> root@2cf8b1eea328:/gfootball# python3 -m gfootball.play_game
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/gfootball/gfootball/play_game.py", line 18, in <module>
>     from gfootball.env import football_env
>   File "/gfootball/gfootball/env/__init__.py", line 23, in <module>
>     from gfootball.env import config
>   File "/gfootball/gfootball/env/config.py", line 28, in <module>
>     import gfootball_engine as libgame
> ModuleNotFoundError: No module named 'gfootball_engine'

How can Installed the missed module ? 
do you recommend to re-run all te pip install module by hand ?

Thanks!

**Comment by zajaczajac** [comment]
Do you run this in Docker on macOS?
`play_game` script isn't supposed to work in Docker (because of rendering issues), but `python3 -m gfootball.examples.run_ppo2` should work.

Did the docker image build properly or there were some issues?
It looks like the installation failed, can you try following steps:
- clone the repo from scratch
- comment out line baselines dependency from setup.py
- add to Dockerfile: 
RUN pip3 install "git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6"
before the line
RUN cd /gfootball && pip3 install .[tf_$DEVICE] --process-dependency-links
- try to build again?

**Comment by qstanczyk** [comment]
Also note that openAI version has been increased (#1), which might be relevant to you.
Did you manage to resolve the problem?
I am closing this issue for now, please reopen if this is still a problem.

**Comment by zhangyiru** [comment]
> Do you run this in Docker on macOS?
> `play_game` script isn't supposed to work in Docker (because of rendering issues), but `python3 -m gfootball.examples.run_ppo2` should work.
> 
> Did the docker image build properly or there were some issues?
> It looks like the installation failed, can you try following steps:
> 
> * clone the repo from scratch
> * comment out line baselines dependency from setup.py
> * add to Dockerfile:
>   RUN pip3 install "git+https://github.com/openai/baselines.git@master#egg=baselines-0.1.6"
>   before the line
>   RUN cd /gfootball && pip3 install .[tf_$DEVICE] --process-dependency-links
> * try to build again?

I use your new version to run the code "python3 -m gfootball.examples.run_ppo2",but it has the same error "no module named 'gfootball-engine'",the gfootball-engine is a folder,  the "import gfootball-engine as libgame' has wrong? looking forward to your reply~

**Comment by Hallam-Liu** [comment]
i am using ubuntu 16 and have the same issue, I ran the program successfully but get this issue after pull updated code
