### ISSUE TITLE
Makefile:83: recipe for target 'all' failed

### ISSUE THREAD

**Issue by DavidBert** [google-research/football#84]
Hi I'm facing the following error when trying to install football on Ubuntu 18.04 with the pip command:

[57%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/ball.cpp.o
    [ 58%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/match.cpp.o
    [ 58%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/referee.cpp.o
    [ 59%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/AIsupport/mentalimage.cpp.o
    [ 60%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/AIsupport/AIfunctions.cpp.o
    [ 61%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/proceduralpitch.cpp.o
    [ 62%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/team.cpp.o
    [ 63%] Building CXX object CMakeFiles/gamelib.dir/src/onthepitch/teamAIcontroller.cpp.o
    [ 63%] Linking CXX static library libgamelib.a
    [ 63%] Built target gamelib
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    gfootball/build_game_engine.sh: line 19: pushd: third_party/gfootball_engine: No such file or directory
    Google Research Football compilation failed
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-b4nu5qlk-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6rqel3v4-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-b4nu5qlk-build/'

Does someone know how to fix it?

**Comment by AntonRaichuk** [comment]
Could you paste the exact command that you ran? I just tried running commands from README on a clean ubuntu 18.04 instance and they worked just fine.

In your case there might be something wrong with directories.
It runs the build ("gfootball/build_game_engine.sh") from "gfootball" directory. But then it complains that "third_party/gfootball_engine" is not there. This directory is/should be inside "gfootball" directory. Maybe somehow it is trying to find it one level higher.

**Comment by qstanczyk** [comment]
Could you verify that third_party/gfootball_engine directory exists after compilation fails?
build_game_engine.sh script looks as follows:

18> pushd third_party/gfootball_engine && cmake . && make -j `nproc` && popd
19> pushd third_party/gfootball_engine && ln -sf libgame.so _gameplayfootball.so && popd
So given that it fails on line 19 while line 18 works it suggests third_party/gfootball_engine directory goes missing between line 18 and 19. You can also modify this script to see the content of the directories between lines 18 and 19. We are not able to reproduce your problem, so need your debugging help on this.

**Comment by DavidBert** [comment]
Thanks for your help.
An echo $(pwd) command before line 19 indicates :
/tmp/pip-7bbn24ar-build/third_party/gfootball_engine

I tried to modify line 19 to 
"pushd ../gfootball_engine && ln -sf libgame.so _gameplayfootball.so && popd"
but got the following error:

Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    /tmp/pip-u8y4exh2-build/third_party/gfootball_engine /tmp/pip-u8y4exh2-build/third_party/gfootball_engine /tmp/pip-u8y4exh2-build
    /tmp/pip-u8y4exh2-build/third_party/gfootball_engine /tmp/pip-u8y4exh2-build
    cp: cannot stat 'third_party/gfootball_engine/_gameplayfootball.so': No such file or directory
    Google Research Football compilation failed

**Comment by qstanczyk** [comment]
We need to get an error which seems to be invisible at the moment.
Can you try to run "pip3 install" with -v (verbose). That hopefully will show what is the problem during compilation.
If that doesn't help you can also add "VERBOSE=1" to the 'make -j `nproc`' call in build_game_engine.sh

**Comment by cyfra** [comment]
Hey @DavidBert 

We're working on having pre-compiled library - please see #94 

You can try it out and see if it works for you.

**Comment by kkurach** [comment]
The new version was pushed today (v2.0), so please re-open the bug if the issue still exists there.
