### ISSUE TITLE
[Docker installation] This version of TensorFlow Probability requires TensorFlow version >= 1.15

### ISSUE THREAD

**Issue by Neira1991** [google-research/football#85]
Hello 
when I run the command `python3 -m gfootball.examples.run_ppo2 --dump_full_episodes=True ` then I have this error
 <img width="1435" alt="Capture d’écran 2019-10-03 à 18 04 35" src="https://user-images.githubusercontent.com/10520379/66144045-6fb88000-e608-11e9-982e-f031d215ca99.png">

so, I try to install the right version but...
<img width="1438" alt="Capture d’écran 2019-10-03 à 18 12 16" src="https://user-images.githubusercontent.com/10520379/66144704-a04ce980-e609-11e9-9927-3f03876d571e.png">

someone else with the same problem?
MacOS Mojave 10.14
installation CPU

Thanks for the great job

**Comment by wilkinsjle** [comment]
Yeah a solid +1, I have this issue too, running your same command on `Ubuntu 18.04.3 LTS`, without Docker.

According to Tensorflow's site, https://www.tensorflow.org/install/pip, the latest version before 2.0 was `1.15rc2`. However when I try to install it via pip3, I also get the same error as you. Seems like the latest version available is 1.14.0.

**Comment by UmashankarTriforce** [comment]
@Neira1991 Have you tried out `pip3 install tensorflow==2.0.0b1`?

**Comment by wilkinsjle** [comment]
I don't think this is compatible with Tensorflow 2.0 @UmashankarTriforce

**Comment by Neira1991** [comment]
@UmashankarTriforce "tensorflow<2.0" as dependence :( but I tried anyway and this does not work

**Comment by Neira1991** [comment]
I updated PIP then installed tensorflow==1.15rc2 and it's work, thanks @cyrilou242
