### ISSUE TITLE
Unable to install on cluster

### ISSUE THREAD

**Issue by julienroyd** [google-research/football#86]
When I run `pip install .` in football directory on cluster I get the following error:

```
running build_ext
  /tmp/pip-req-build-nzvnptrm/third_party/gfootball_engine /tmp/pip-req-build-nzvnptrm
  -- The C compiler identification is GNU 7.3.0
  -- The CXX compiler identification is GNU 7.3.0
  -- Check for working C compiler: /cvmfs/soft.computecanada.ca/custom/bin/cc
  -- Check for working C compiler: /cvmfs/soft.computecanada.ca/custom/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/bin/c++
  -- Check for working CXX compiler: /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-7.3.0/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found OpenGL: /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libGL.so
  CMake Error at CMakeModules/FindPackageHandleStandardArgs.cmake:110 (MESSAGE):
    Could NOT find SDL2_image (missing: SDL2_IMAGE_LIBRARIES
    SDL2_IMAGE_INCLUDE_DIRS)
  Call Stack (most recent call first):
    CMakeModules/FindPackageHandleStandardArgs.cmake:301 (_FPHSA_FAILURE_MESSAGE)
    CMakeModules/FindSDL2_image.cmake:104 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    CMakeLists.txt:35 (FIND_PACKAGE)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-nzvnptrm/third_party/gfootball_engine/CMakeFiles/CMakeOutput.log".
  gfootball/build_game_engine.sh: line 19: pushd: third_party/gfootball_engine: No such file or directory
  Google Research Football compilation failed
  ----------------------------------------
  ERROR: Failed building wheel for gfootball
  Running setup.py clean for gfootball
Failed to build gfootball
```

It seems that FindSDL2_image.cmake cannot find the paths to sdl2 library. I have tried to manually set environment variables for SDL2_IMAGE_LIBRARY and SDL2_IMAGE_INCLUDE_DIR to the right paths but I still get the same error.

Is it possible to provide a pre-built wheel?

(Note this is a re-opening of issue #69)

**Comment by cyfra** [comment]
Hey @julienroy13 

We're starting by having pre-built .so library (to avoid having C++ compilation).
Please look at #94  and let us know if it works for you.

**Comment by julienroy13** [comment]
I cloned the repo and installed using:
```
GFOOTBALL_USE_PREBUILT_SO=1 pip3 install .
```
However I still get the same error message as mentioned above. It seems like it is still trying to compile the c++ files.

**Comment by kkurach** [comment]
Hi Julien,

we just pushed a v2.0 version of the game, which should fix many issue. Could you please re-try and let us know if you still see the problem?  

git clone https://github.com/google-research/football.git
cd football
pip3 install .

**Comment by julienroy13** [comment]
Thanks for the support.

I have re-cloned the repo and tried using both `pip3 install .` and `GFOOTBALL_USE_PREBUILT_SO=1 pip3 install .`. Either ways I get the same error as in my first post above.

**Comment by AntonRaichuk** [comment]
@julienroy13: cloning the repo is not sufficient. have you merged a pull request mentioned by cyfra@ to your repo? he has the change that defines semantics of GFOOTBALL_USE_PREBUILT_SO, without which it obviously won't have an effect. 
Could you make sure that his change is a part of your repo?

If that works we'll probably merge it to the main branch

**Comment by julienroy13** [comment]
@AntonRaichuk yes my mistake, I thought the changes he was referring to were already merged. 

I have since tried with [cyfra's fork](https://github.com/cyfra/football/tree/experimental) (commit 8e69c12) of gfootball and ran `GFOOTBALL_USE_PREBUILT_SO=1 pip3 install .` The installation went through, but unfortunately I still get an error when importing gfootball in python:

>> ImportError: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory

It seems the package is not linked to the correct Paths for libboost.

Here is the full traceback:
```
import gfootball
WARNING: Logging before flag parsing goes to stderr.
W1206 11:57:18.028326 47765011141632 __init__.py:43] Looks like game engine is not compiled, please run:
W1206 11:57:18.028580 47765011141632 __init__.py:46]   pushd /home/rojulien/virtualenvs/foot/lib/python3.7/site-packages/gfootball_engine && cmake . && make -j `nproc` && popd
W1206 11:57:18.028645 47765011141632 __init__.py:48]   pushd /home/rojulien/virtualenvs/foot/lib/python3.7/site-packages/gfootball_engine && ln -s libgame.so _gameplayfootball.so && popd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rojulien/virtualenvs/foot/lib/python3.7/site-packages/gfootball/__init__.py", line 17, in <module>
    from gfootball.env import scenario_builder
  File "/home/rojulien/virtualenvs/foot/lib/python3.7/site-packages/gfootball/env/__init__.py", line 21, in <module>
    from gfootball.env import config
  File "/home/rojulien/virtualenvs/foot/lib/python3.7/site-packages/gfootball/env/config.py", line 27, in <module>
    import gfootball_engine as libgame
  File "/home/rojulien/virtualenvs/foot/lib/python3.7/site-packages/gfootball_engine/__init__.py", line 39, in <module>
    from _gameplayfootball import *
ImportError: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory
```

**Comment by qstanczyk** [comment]
I think the easiest way here is to try with Docker setup.
