### ISSUE TITLE
[Ubuntu 16.04] libGL error when trying to play the game

### ISSUE THREAD

**Issue by OneFiveChen** [google-research/football#9]
when I run the `python3 -m gfootball.play_game` , error shows that:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Couldn't load GL function glBegin: No GL driver has been loaded
```
Also happen in `python3 -m gfootball.examples.run_ppo2 --dump_full_episodes=True --render=True`
But when I try another pygame example `python3 -m pygame.examples.aliens` , it works

**Comment by cyfra** [comment]
This looks like the issue with OpenGL. AFAIK other pygames are not using it for rendering, therefore might be running fine.

Can you try running "glxgears" (or "glgears") program ?
(this is a standalone tool for verifying if opengl is working correctly).

Also - please mention what version of the system you have.

**Comment by avijit9** [comment]
I am also facing the same issue. I can confirm that glxinfo, glxgears are working fine for me.

**Comment by cyfra** [comment]
What linux version are you running ? How did you install the football environment ?

The fact that glxgears is working means, that you do have a working driver (good), but now the question is, whether the football environment is using the same one.

Let's start by comparing the ".so" libraries that glxgears and the gfootball.so depends on:

ldd /usr/bin/glxgears | grep  -i gl
ldd PATH_TO_WHERE_GFOOTBALL_WAS_INSTALLED/_gameplayfootball.so | grep  -i gl

(on my machine it is in $HOME/.local/lib/python3.6/site-packages/gfootball_engine)

**Comment by avijit9** [comment]
Yes, you're right.

```
ldd /usr/bin/glxgears | grep -i gl : 
```
```
libGL.so.1 => /usr/lib/nvidia-410/libGL.so.1 (0x00007f237f084000)
libnvidia-glcore.so.410.104 => /usr/lib/nvidia-410/libnvidia-glcore.so.410.104 (0x00007f237c887000)
```
```
ldd build/lib.linux-x86_64-3.5/gfootball_engine/_gameplayfootball.so | grep -i gl
```
```
libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007f7595d83000)
```

**Comment by OneFiveChen** [comment]
`glxinfo` `glxgears` `xclock` works ok but it also shows the libGL error.
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
90167 frames in 5.2 seconds = 17355.412 FPS
...
```

I check my OpenGL version with `glxinfo | grep OpenGL`, I get that :
```
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: GDI Generic
OpenGL version string: 1.1.0
OpenGL extensions:
```
OpenGL version looks too low. I use TITAN RTX and my nvidia driver is 418.56. It seems that gpu is not used.(I am not familiar with x server. Maybe I should do something with xserver configuration ?)


Also check the `ldd` command：
```
ldd /usr/bin/glxgears | grep -i gl
```
```
libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007fd898553000)
libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007fd896cbf000)
libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007fd896287000)
```

```
ldd ./lib/python3.6/site-packages/gfootball_engine/_gameplayfootball.so | grep -i gl
```
```
libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007f560ab6e000)
```
Linux version: Ubuntu 16.04.03 LTS

**Comment by cyfra** [comment]
Seems that many things were not linked correctly.
Here's the example output from my machine:

ldd _gameplayfootball.so | grep -i gl
        libglee.so.0d1 => /usr/lib/x86_64-linux-gnu/libglee.so.0d1 (0x00007efdd0db4000)
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007efdce1e3000)
        libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007efdcdf74000)
        libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007efdcb6c6000)
        libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007efdc96f6000)
        libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007efdc9440000)


Could you do:
- go to gfootball/third_party/gfootball_engine
- run cmake .   (notice the dot)
Please paste the output of this command and contents of CMakeFiles/game.dir/link.txt

**Comment by fedorajzf** [comment]
I had the same problem.

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Couldn't load GL function glBegin: No GL driver has been loaded

**Comment by OneFiveChen** [comment]
`cmake .` output:
```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found SDL2_image: /usr/lib/x86_64-linux-gnu/libSDL2_image.so  
-- Found SDL2_ttf: /usr/lib/x86_64-linux-gnu/libSDL2_ttf.so  
-- Found SDL2_gfx: /usr/lib/x86_64-linux-gnu/libSDL2_gfx.so (found version "1.0.1") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable version "3.5.2", minimum required is "3") 
Using Python: 3.5.2
-- Could NOT find Boost
python3-py35 not found. Trying other names.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python-py35
Using python_boost: python-py35
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   signals
--   filesystem
--   python-py35
--   chrono
--   date_time
--   atomic
-- Found SGE: /usr/lib/x86_64-linux-gnu/libSGE.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chenjiali/football/third_party/gfootball_engine
```


contents of CMakeFiles/game.dir/link.txt
```
/usr/bin/c++  -fPIC   -fPIC -g -O3 -no-pie -L/usr/X11/lib -lX11 -lSDL2  -shared -Wl,-soname,libgame.so -o libgame.so CMakeFiles/game.dir/src/cmake/backtrace.cpp.o CMakeFi    les/game.dir/src/cmake/helpers.cpp.o CMakeFiles/game.dir/src/misc/perlin.cpp.o CMakeFiles/game.dir/src/misc/hungarian.c.o CMakeFiles/game.dir/src/gametask.cpp.o CMakeFile    s/game.dir/src/utils.cpp.o CMakeFiles/game.dir/src/main.cpp.o CMakeFiles/game.dir/src/cmake/main.cpp.o CMakeFiles/game.dir/src/synchronizationTask.cpp.o CMakeFiles/game.d    ir/src/dbquery.cpp.o CMakeFiles/game.dir/src/gamedefines.cpp.o CMakeFiles/game.dir/ai.cpp.o CMakeFiles/game.dir/src/ai/ai_keyboard.cpp.o libgamelib.a libhidlib.a libmenul    ib.a libdatalib.a libleaguelib.a -lglee libblunted2.a -lrt -lboost_system -lboost_thread -lboost_signals -lboost_filesystem -lboost_python-py35 -lboost_chrono -lboost_dat    e_time -lboost_atomic -lpthread -lpython3.5m -lSDL2_image -lSDL2_ttf -lSDL2_gfx -lSGE -ldl -lm -lsqlite3 -lGLU -lGL

```

**Comment by cyfra** [comment]
I think I know what's going on - this is due to the older version of the c++ compiler that you're using.

Could you please path the one-line change from:
https://github.com/google-research/football/pull/12

And try compiling and installing again.

**Comment by OneFiveChen** [comment]
After changing CMakeList.txt, I run `cmake .`:

```
Using Python: 3.5.2
-- Could NOT find Boost
python3-py35 not found. Trying other names.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python-py35
Using python_boost: python-py35
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   signals
--   filesystem
--   python-py35
--   chrono
--   date_time
--   atomic
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chenjiali/football/third_party/gfootball_engine
```

```
/usr/bin/c++  -fPIC   -fPIC -g -O3 -no-pie -L/usr/X11/lib -lX11 -lSDL2  -Wl,--no-as-needed -shared -Wl,-soname,libgame.so -o libgame.so CMakeFiles/game.dir/src/cmak    e/backtrace.cpp.o CMakeFiles/game.dir/src/cmake/helpers.cpp.o CMakeFiles/game.dir/src/misc/perlin.cpp.o CMakeFiles/game.dir/src/misc/hungarian.c.o CMakeFiles/game.d    ir/src/gametask.cpp.o CMakeFiles/game.dir/src/utils.cpp.o CMakeFiles/game.dir/src/main.cpp.o CMakeFiles/game.dir/src/cmake/main.cpp.o CMakeFiles/game.dir/src/synchr    onizationTask.cpp.o CMakeFiles/game.dir/src/dbquery.cpp.o CMakeFiles/game.dir/src/gamedefines.cpp.o CMakeFiles/game.dir/ai.cpp.o CMakeFiles/game.dir/src/ai/ai_keybo    ard.cpp.o libgamelib.a libhidlib.a libmenulib.a libdatalib.a libleaguelib.a -lglee libblunted2.a -lrt -lboost_system -lboost_thread -lboost_signals -lboost_filesyst    em -lboost_python-py35 -lboost_chrono -lboost_date_time -lboost_atomic -lpthread -lpython3.5m -lSDL2_image -lSDL2_ttf -lSDL2_gfx -lSGE -ldl -lm -lsqlite3 -lGLU -lGL
```

The error still exists

**Comment by cyfra** [comment]
Can you check that the ldd started showing the GL libraries ?

Also - please make sure that your game is using the library that you've just compiled.
(the cmake/make will put the library locally, but gfootball will try to load it from the $HOME/.local/lib/python3.6/site-packages/gfootball_engine or similar location.

**Comment by fedorajzf** [comment]
LABEL_DEBUG=verbose glxinfo

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  26
  Current serial number in output stream:  25

**Comment by OneFiveChen** [comment]
`ldd` get a same result after running the new CMakeFile
```
ldd /usr/bin/glxgears | grep -i gl
```

```
libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f21815a1000)
libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f217fd0d000)
libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f217f2d5000)
```

```
ldd ~/anaconda3/envs/gfootball/lib/python3.6/site-packages/gfootball_engine/_gameplayfootball.so | grep -i gl
```

```
libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007efc6acc0000)
```

And **libgame.so** does not exist. I check this with `find ~ -name libgame.so`

**Comment by cyfra** [comment]
@OneFiveChen  - sorry, I was not clear:

- go to the directory where you've run the cmake / make
- there should be a libgame.so there (assuming that make finished successfully)
- verify that this libgame.so has additional ldd GL dependencies
- copy this libgame.so to replace ~/anaconda3/envs/gfootball/lib/python3.6/site-packages/gfootball_engine/_gameplayfootball.so
- check if the game works


On my side: I've verified that things work on Ubuntu with Nvidia's OpenGL driver. I'll also try to find a computer with similar setup that you have.

**Comment by WOWNICE** [comment]
I got the same problem as @OneFiveChen: 

The fact is that there is no **libgame.so** generated after adding the additional line to **CMakeLists.txt** and rerun cmake .  command.

Wondering how to fix it.

**Comment by WOWNICE** [comment]
Now I've successfully generated the **libgame.so** with the correct dependencies, here is what I did: 

1. uninstall the gfootball package
2. modify the **CMakefileLists.txt** as mentioned in #12 
3. `pip install -e .[tf_cpu] --process-dependency-links`
This installation process would fail, while it does generate the **libgame.so** file with correct dependencies under **third_party/gfootball_engine** directory. 'pip -e' means install from the local .git repo, check the following link: [https://stackoverflow.com/questions/14159482/pip-install-a-local-git-repository](url) 
4. reinstall the gfootball package using `pip install gfootball[tf_cpu] --process-dependency-links`
5. replace the [python-environment-path]/site-packages/gfootball_engine/_gameplayfootball.so with libgame.so 

Though the whole process is a little bit beyond my comprehension, it did generates that important .so file @cyfra mentioned. And the dependencies look exactly like the correct one you post:
```
libglee.so.0d1 => /usr/lib/x86_64-linux-gnu/libglee.so.0d1 (0x00007f344bf0a000)
libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f34493eb000)
libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f3449177000)
libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f34460bc000)
libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f344534a000)
libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007f3443348000)
```

The problem is that I still can't get the rendering engine running. It now gives me "Couldn't load GL function glBegin: Video subsystem has not been initialized" error. 

I'm confused, and any advice would be welcomed.

**Comment by cyfra** [comment]
Unfortunately it seems that my solution didn't work. Thanks for verifying it @WOWNICE  and @OneFiveChen.

I am still trying to reproduce it on one of my machines .

**Comment by Gezx** [comment]
when I run"python3 -m gfootball.play_game"，the problem is that:
Wed Jun 26 15:36:39 2019 [Warning] in [OpenGLRenderer3D::CreateContext]: OpenGL version not equal to or higher than 3.2 (or not reported as such)
shader compilation error (media/shaders/simple.vert)
Wed Jun 26 15:36:39 2019 [Warning] in [::LoadGLShader]: shader compilation error (media/shaders/simple.vert)
shader compilation info: 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
......................


and when I run the "glxinfo | grep OpenGL" result is:
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: SVGA3D; build: RELEASE;  LLVM;
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:


so how to upgrate it?I don't konw what to to?

**Comment by cyfra** [comment]
@Gezx  - your case is different, and fortunately we have a workaround in FAQ in README.md 

MESA_GL_VERSION_OVERRIDE=3.2 MESA_GLSL_VERSION_OVERRIDE=150 python3 -m gfootball.play_game

**Comment by Gezx** [comment]
@cyfra Thank you! It works. I am so sorry that I don't see that.

**Comment by ranahanocka** [comment]
I also ran into this same issue (Ubuntu 18.04, Cuda 10, and my OpenGL was working). I tried all the things suggested here, including the one given by @WOWNICE , but still didn't work for me. I finally got it to work, so sharing it in case it helps anyone else.

I noticed that `/usr/lib/x86_64-linux-gnu/libGL.so` pointed to `/usr/lib/x86_64-linux-gnu/libGL.so.1.0.0` (which was a broken link). So I remove the broken link and then created a new one:

`sudo rm libGL.so`
`sudo ln -s libGL.so.1 libGL.so`

Then I went back to the root football directory and ran:
`pip3 install .[tf_gpu]`

and it worked.

Note that I did add the line to the CMakeLists.txt from [#12](https://github.com/google-research/football/pull/12) (but I don't know if it would have worked without it).

**Comment by cyfra** [comment]
@WOWNICE @OneFiveChen @avijit9 @fedorajzf - Did the solution provided by @ranahanocka work for you?  (do you also have broken library links for some reason?)

**Comment by Shengyu-Feng** [comment]
@cyfra When I have the broken library links, I cannot even install the package. I've tried to link to different OpenGL library, but it always shows me 

> Couldn't load GL function glBegin: No GL driver has been loaded

**Comment by Shengyu-Feng** [comment]
Does the new version deal with this problem either?

**Comment by qstanczyk** [comment]
Head version of the environment supports off screen rendering which doesn't require display. Hope many rendering issues are solved there.
