### ISSUE TITLE
SystemError: Sonnet requires tensorflow_probability (minimum version 0.4.0) to be installed. If using pip, run `pip install tensorflow-probability` or `pip install tensorflow-probability-gpu`

### ISSUE THREAD

**Issue by weisong82** [google-research/football#91]
run throw exceptions：

`$ python3 -m gfootball.examples.run_ppo2 --level=academy_empty_goal_close
/home/song/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/song/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/song/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/song/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/song/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/song/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/song/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/song/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/song/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/song/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/song/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/song/.local/lib/python3.5/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/home/song/.local/lib/python3.5/site-packages/sonnet/__init__.py", line 47, in _ensure_dependency_available_at_version
    pkg = importlib.import_module(package_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/song/.local/lib/python3.5/site-packages/tensorflow_probability/__init__.py", line 68, in <module>
    _ensure_tf_install()
  File "/home/song/.local/lib/python3.5/site-packages/tensorflow_probability/__init__.py", line 65, in _ensure_tf_install
    present=tf.__version__))
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 1.15; Detected an installation of version 1.14.0. Please upgrade TensorFlow to proceed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/gfootball/examples/run_ppo2.py", line 28, in <module>
    from gfootball.examples import models
  File "/usr/local/lib/python3.5/dist-packages/gfootball/examples/models.py", line 23, in <module>
    import sonnet as snt
  File "/home/song/.local/lib/python3.5/site-packages/sonnet/__init__.py", line 64, in <module>
    _ensure_dependency_available_at_version('tensorflow_probability', '0.4.0')
  File "/home/song/.local/lib/python3.5/site-packages/sonnet/__init__.py", line 54, in _ensure_dependency_available_at_version
    package_name, min_version, pip_name, pip_name))
SystemError: Sonnet requires tensorflow_probability (minimum version 0.4.0) to be installed. If using pip, run `pip install tensorflow-probability` or `pip install tensorflow-probability-gpu``

with my pip3 list：
 pip3 list
absl-py (0.8.1)
astor (0.8.0)
baselines (0.1.6)
blinker (1.3)
chardet (2.3.0)
Click (7.0)
cloud-init (18.5)
cloudpickle (1.1.1)
command-not-found (0.3)
configobj (5.0.6)
contextlib2 (0.6.0.post1)
cryptography (1.2.3)
decorator (4.4.0)
dm-sonnet (1.35)
enum34 (1.1.6)
future (0.18.1)
gast (0.2.2)
gfootball (1.5)
google-pasta (0.1.7)
grpcio (1.24.3)
gym (0.15.3)
h5py (2.10.0)
idna (2.0)
Jinja2 (2.8)
joblib (0.14.0)
jsonpatch (1.10)
jsonpointer (1.9)
Keras-Applications (1.0.8)
Keras-Preprocessing (1.1.0)
language-selector (0.1)
Markdown (3.1.1)
MarkupSafe (0.23)
numpy (1.17.3)
oauthlib (1.0.3)
opencv-python (4.1.1.26)
pip (8.1.1)
prettytable (0.7.2)
protobuf (3.10.0)
pyasn1 (0.1.9)
pycurl (7.43.0)
pygame (1.9.6)
pyglet (1.3.2)
pygobject (3.20.0)
PyJWT (1.3.0)
pyserial (3.0.1)
python-apt (1.1.0b1+ubuntu0.16.4.4)
python-debian (0.1.27)
python-systemd (231)
PyYAML (3.11)
requests (2.9.1)
scipy (1.3.1)
semantic-version (2.8.2)
setuptools (41.4.0)
six (1.12.0)
ssh-import-id (5.5)
tensorboard (1.14.0)
tensorflow (1.14.0)
tensorflow-estimator (1.14.0)
tensorflow-probability (0.4.0)
termcolor (1.1.0)
tqdm (4.36.1)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.13.1)
Werkzeug (0.16.0)
wheel (0.33.6)
wrapt (1.11.2)

**Comment by AntonRaichuk** [comment]
Are you sure you are using the latest version of the code?

Few weeks ago we pushed a fix: https://github.com/google-research/football/pull/88/commits/19b13b26efa4885ecd196449ba20593b8b509328

**Comment by weisong82** [comment]
Caused by my pip version is too old .  use this:  tf<=2.0  , will got  tensorflow (1.14.0) , that not match python3.5

`You are using pip version 8.1.1, however version 19.3.1 is available.`

**Comment by louislee617** [comment]
pip install tensorflow_probability==0.7.0
