### ISSUE TITLE
GPU-based Rendering on remote server

### ISSUE THREAD

**Issue by IouJenLiu** [google-research/football#96]
In the README, for pixels_gray representation, it says "In order to use this representation you have to enable rendering in create_environment call (and run on GPU)". Does it mean rendering should be performed on GPU? 
How to enable GPU-based rendering? Currently in my machine, rendering is performed only on cpus when I use pixels_gray representation.  Thanks!

**Comment by qstanczyk** [comment]
It is fine to use software rendering, but you need to keep in mind it is significantly slower than GPU rendering. As long as there are no errors thrown by the environment you should be good. I will update a README and remove mention of a GPU.

**Comment by IouJenLiu** [comment]
Thanks for your reply. I would like to use GPU rendering, software rendering is too slow. My question is it possible to enable GPU rendering on remote server? Thanks!

**Comment by IouJenLiu** [comment]
Follow the instruction https://carla.readthedocs.io/en/latest/carla_headless/
solves the issue.
