### ISSUE TITLE
QUESTION: Training (e.g. using PPO) against an opponent using a checkpoint

### ISSUE THREAD

**Issue by cwilliamstats** [google-research/football#98]
In the paper there is a section called Multiplayer Experiments where training an agent against a frozen previously trained agent, which I guess is a standard training output checkpoint, as opposed to the standard in-built AI is discussed.

How do you set up the training to do this, e.g. within the run_ppo2.py script? I can see config options for changing the difficulty and making the default opponent lazy, but I can't see a way to change the opponent away from default.

Many Thanks

**Comment by AntonRaichuk** [comment]
In order to train against a checkpoint, you can pass 'extra_players' argument to create_environment function.
For example extra_players='ppo2_cnn:left_players=1,policy=gfootball_impala_cnn,checkpoint=$CHECKPOINT'.

**Comment by AntonRaichuk** [comment]
One correction:
extra_players='ppo2_cnn:right_players=1,policy=gfootball_impala_cnn,checkpoint=$CHECKPOINT'.

**Comment by cwilliamstats** [comment]
I'm getting an error with that addition when running run_ppo2.py:

The error I'm getting is:
```
Exception "unhandled EOFError"
File: /usr/lib/python3.6/multiprocessing/connection.py, Line: 383
```
I'm runnning with the following:

```
def create_single_football_env(seed):
  """Creates gfootball environment."""
  env = football_env.create_environment(
      env_name=FLAGS.level, stacked=('stacked' in FLAGS.state),
      rewards=FLAGS.reward_experiment,
      logdir=logger.get_dir(),
      enable_goal_videos=FLAGS.dump_scores and (seed == 0),
      enable_full_episode_videos=FLAGS.dump_full_episodes and (seed == 0),
      render=FLAGS.render and (seed == 0),
      dump_frequency=1 if FLAGS.render and seed == 0 else 0,
      extra_players='ppo2_cnn:right_players=1,policy=cnn,checkpoint=/tmp/cnn-CA-5M-randB0_05/checkpoints/27000')
  env = monitor.Monitor(env, logger.get_dir() and os.path.join(logger.get_dir(),
                                                               str(seed)))
  return env
```

and:

```
ppo2.learn(network='cnn',
             total_timesteps=FLAGS.num_timesteps,
             env=vec_env,
             seed=FLAGS.seed,
             nsteps=FLAGS.nsteps,
             nminibatches=FLAGS.nminibatches,
             noptepochs=FLAGS.noptepochs,
             gamma=FLAGS.gamma,
             ent_coef=FLAGS.ent_coef,
             lr=FLAGS.lr,
             log_interval=1,
             save_interval=FLAGS.save_interval,
             cliprange=FLAGS.cliprange,
             load_path='/tmp/cnn-CA-5M-randB0_05/checkpoints/36000')
```

this works fine with the extra_players line omitted. I'm using the regular cnn model rather than the gfootball_impala_cnn. 
```
python3 -m gfootball.play_game --players "ppo2_cnn:left_players=1,policy=cnn,checkpoint=/tmp/cnn-CA-5M-randB0_05/checkpoints/27000" 
```
runs fine.

**Comment by AntonRaichuk** [comment]
Try passing it as an array, so like this:
extra_players=['ppo2_cnn:right_players=1,policy=cnn,checkpoint=/tmp/cnn-CA-5M-randB0_05/checkpoints/27000']
