### ISSUE TITLE
Getting data from environment

### ISSUE THREAD

**Issue by bWENTURA** [google-research/football#99]
Hi,
me and my friend want to use data from your project to test reinforced learning supported by evolutionary algorithm. We want to train player to deal with one of the scenarios.
We read that gfootball use gym API. We have run your project and simulations, but we don't know if all of the operations run from the level of gym API. Is there any possibility that you could help us? 

Regards,
bWENTURA

**Comment by qstanczyk** [comment]
Hi, GFootball supports base Gym API, but we also provide a number of scripts (like play_game), which enables a number of functionalities. We are happy to help if you ask about some more concrete thing (what exactly is your problem)?

**Comment by qstanczyk** [comment]
Please reopen if you have any further questions.
